### ISSUE TITLE
[doc] 10.3 Upgrading the MON, MGR, and OSD nodes - add bluestore_fsck_quick_fix_on_mount information

### ISSUE THREAD

**Issue by tserong** [SUSE/doc-ses#1004]
When upgrading from Ceph Nautilus to Pacific, there's a format conversion necessary for OSDs, to improve the accounting for "omap" data. This does not happen automatically. There's a few ways to make it happen:

1. Run `ceph config set osd bluestore_fsck_quick_fix_on_mount true` _before_ adopting any OSDs. As all the OSDs are adopted and started, they will do the format conversion automatically.
2. Run `ceph config set osd bluestore_fsck_quick_fix_on_mount true` _after_ adopting all the OSDs, then restart the OSDs later (they'll do the conversion on startup).
3. Don't set that option, and instead go through an irritating manual procedure using `ceph-bluestore-tool` for each OSD. For each individual OSD, this would be something like the following:

```
# cephadm unit --name osd.1 stop
# cephadm shell --mount /var/lib/ceph/f8645ef8-a3bf-46ce-9f67-6514afd211c1:/var/lib/ceph
[ceph: root@node1 /]# ceph-bluestore-tool quick-fix --path /var/lib/ceph/osd.1
(...some command output here...)
[ceph: root@node1 /]# exit
# cephadm unit --name osd.1 start
```

We need to mention how to do this conversion in the documentation, because if you _don't_ do it, `ceph status` will tell you your cluster is in HEALTH_WARN state, and `ceph health detail` will say something like this for each OSD:

```
HEALTH_WARN on 2 OSD(s)
BLUESTORE_NO_PER_POOL_OMAP on 2 OSD(s)
    osd.1 legacy (not per-pool) omap detected, suggest to run store repair to benefit from per-pool omap usage statistics
    osd.5 legacy (not per-pool) omap detected, suggest to run store repair to benefit from per-pool omap usage statistics
```

Note also that this conversion "may take a few minutes to as much as a few hours (for an HDD with lots of omap data)" (see point 4 under https://docs.ceph.com/en/latest/releases/pacific/#upgrading-non-cephadm-clusters).

So, the question is: how best do we describe the issue, and which procedure should we recommend?

- Options 1 and 2 are both a lot easier to _do_ than option 3.
- Option 1 may mean that upgrading each storage node is very slow (if it has to wait a long time to do the conversion as part of the upgrade), but it means that once all the OSDs are adopted, the cluster will be HEALTH_OK, not HEALTH_WARN
- Option 2 means there's no potential delay getting the cluster upgraded, but leaves you in HEALTH_WARN, then you have to go restart the OSDs to do the conversion (possibly good to just try restart a couple, see how long it takes in your environment, then if it's slow, do it in a staged fashion so not too many are down at once). It _also_ means that if you happen to reboot a node, the conversion will happen automatically next time that node comes up (this may not be desirable if it's going to take a long time).
- Option 3 gives you the finest control, but is, frankly, a PITA.

**Comment by mgfritch** [comment]
option 1 seems like the most pragmatic approach since any issue that might occur would be uncovered before the upgrade, whereas option 2 would force the user to either immediately fix any issue that occurred and/or preform a downgrade ...

**Comment by tbazant** [comment]
fixed by https://github.com/SUSE/doc-ses/commit/adca5608fa685e83137ec8722dcd2af9c289379c
