### ISSUE TITLE
Fix external links

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#1012]
**Summary**
Run `daps checklink`
 There are issues reported for the versions 5.5 and 6 in English and for 5.5, 6, and 7 for the languages.

**Comment by jfaltenbacher** [comment]
Please find a list of all broken links in this spreadsheet. The green ones are already done. Thanks a million
[SES_broken_links.xlsx](https://github.com/SUSE/doc-ses/files/8387218/SES_broken_links.xlsx)
