### ISSUE TITLE
[doc] Issue in "Upgrade from SUSE Enterprise Storage 7 to 7.1"

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#1030]
### Type of report
   - [x] bug
   - [x] feature request

### Source Document
https://documentation.suse.com/ses/7.1/html/ses-all/upgrade-to-pacific.html#

### Summary
Can not find the information about upgrading the monitoring components (alertmanager, grafana, node-exporter, prometheus)

### Steps To Reproduce
Read the docs and try to find the information about how to upgrade the "non ceph" images when upgrading from SES 7 to SES7.1.

### Expected Results
Steps should be there

### Actual Results
Steps are missing

**Comment by tbazant** [comment]
@tserong what we have is https://susedoc.github.io/doc-ses/main/html/ses-deployment/upgrade-to-pacific.html#upgrade-ses-services - is that enough for upgrading the abovementioned monitoring components ?

**Comment by Martin-Weiss** [comment]
For me this was not enough - this is just updating the components that are using the ceph image.. but alertmanager, grafana, prometheus, node-exporter are not listed, here...

Assumption is that you have to configure the new image and then run "redeploy" and/or "reconfig" or?? Maybe there is a cephadm or an orch command?

**Comment by tserong** [comment]
AIUI `ceph orch upgrade` will do the monitoring stack automatically if you're using registry.suse.com (i.e. haven't overridden any of the `mgr/cephadm/container_image_*` options in order to use a local registry). If you _are_ using a local registry, then I suspect you do have to set those various container image URLs in order to upgrade the monitoring stack, and if so, the details should be added to the docs. I'm not sure who best to confirm this - @mgfritch @s0nea @p-se?

**Comment by p-se** [comment]
> AIUI `ceph orch upgrade` will do the monitoring stack automatically if you're using registry.suse.com (i.e. haven't overridden any of the `mgr/cephadm/container_image_*` options in order to use a local registry). If you _are_ using a local registry, then I suspect you do have to set those various container image URLs in order to upgrade the monitoring stack, and if so, the details should be added to the docs. I'm not sure who best to confirm this - @mgfritch @s0nea @p-se?

I'm not sure if `ceph orch upgrade` handles the upgrade of monitoring containers (IIRC, it did not, but it may in the meantime. @mgfritch might know for sure) but if it does and Ceph has been upgraded (specifically the mgr), then it'll just work. If it does not handle the upgrade, `ceph orch reconfig <service>` will do the upgrade, provided that an updated container image is configured, which will be the case if no container image has been set manually. However, setting a container image manually is a requirement for using local registries. In this case, the registry would need to host the container images and the tags to the container images in the cephadm configuration would need to be updated as well, before either, a `ceph orch upgrade` or `ceph orch reconfig <service>` can successfully be executed.

This is in accordance to the documented way of upgrading container images of minor releases as [documented in the administration (section "upgrading monitoring services")](https://documentation.suse.com/ses/7.1/html/ses-all/monitoring-alerting.html#monitoring-applying-updates) guide. You can simply follow that guide.

For the purpose of being able to find out which versions of the container images are the ones to be used, we added them to the [administration guide (section configuring custom or local images)](https://documentation.suse.com/ses/7.1/html/ses-all/monitoring-alerting.html#monitoring-custom-images) as well (as in the 7.0 documentation).

We may want to add something along the lines of "For upgrading the monitoring container images, please refer to the Administration guide section ... and section .... Upgrading the container images involves the same steps as upgrading container images in a maintenance update." to the upgrade documentation.

**Comment by tserong** [comment]
Thanks @p-se!
