### ISSUE TITLE
[doc] Issue in "Removing nodes"

### ISSUE THREAD

**Issue by ebl-nde** [SUSE/doc-ses#1051]
### Type of report
   - [X] bug
   - [ ] feature request

### Source Document
https://documentation.suse.com/ses/7.1/single-html/ses-admin/#salt-node-removing

### Summary

The docs state to remove the remaining services (e.g. node-exporter, crash) after the host has been removed (step 2: "ceph orch host rm ses-min2"). This leads to an error:
```
storage01:~ # ceph orch host rm storage14
Error EINVAL: Not allowed to remove storage14 from cluster. The following daemons are running in the host:
type                 id             
-------------------- ---------------
node-exporter        storage14      
crash                storage14      

Please run 'ceph orch host drain storage14' to remove daemons from host

```
So it's required to remove all services first, then remove the host from ceph.

### Steps To Reproduce

Try removing a host according to the documentation:

1. Remove OSDs (draining)
2. Remove host from service specs
3. Remove host from ceph

### Expected Results

Host is removed.

### Actual Results

Host is not removed.

### Notes

Steps 2 and 3 should be switched.

**Comment by ebl-nde** [comment]
Draining the services after running step 3 (cephadm rm-daemon) is not possible anymore:
```
storage01:~ # ceph health detail
HEALTH_WARN Failed to apply 2 service(s): crash,node-exporter
[WRN] CEPHADM_APPLY_SPEC_FAIL: Failed to apply 2 service(s): crash,node-exporter
    crash: cephadm exited with an error code: 1, stderr:ERROR: Daemon not found: crash.storage14. See `cephadm ls`
    node-exporter: cephadm exited with an error code: 1, stderr:ERROR: Daemon not found: node-exporter.storage14. See `cephadm ls`
```
Now I'll need to figure out, how to remove the failed services. I'll update if I managed to. It seems that the procedure has changed between SES 7 and 7.1, because I removed the same node successfully in 7 before the upgrade.

**Comment by ebl-nde** [comment]
Sorry for the noise, the situation cleared automatically after a few minutes. The warning cleared and then I could remove the host with `ceph orch host rm storage14`. But the order of the commands should be fixed.

**Comment by tbazant** [comment]
@ebl-nde can you pls review #1054 ?
