### ISSUE TITLE
Expired SSL certificates and how to renew them

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#1060]
Ceph services use SSL certificates for secure communication. Their validity is temporary and has to be renewed in case it expires.

**Comment by tserong** [comment]
I'm presently working my way through services testing cert renewal. For iSCSI, it's:

1. Renew the certificate (however you want to do that, whether it's through a commercial CA, or an in-house CA, or generating another self-signed certificate with `openssl` -- I don't think we need to describe how to do this bit, just so long as you end up with a certificate and key file)
2. Plug those certificates into an iSCSI service spec yaml, as you do during initial deployment (see https://documentation.suse.com/ses/7.1/single-html/ses-deployment/#id-1.3.4.6.6.7.7)
3. Apply the service spec (e.g. `ceph orch apply -i iscsi.yaml`)
4. Reconfigure the service, to pick up the new certificate (e.g. `ceph orch reconfig iscsi.iscsi_service`, but replace `iscsi.iscsi_service` with the actual name of your iSCSI service.

For step 2, a handy trick is to use `ceph orch ls --format=yaml --service-type=iscsi > iscsi.yaml` to save the existing iSCSI service spec(s), then you just go edit that file and apply it. I'm not sure if we've covered doing that already elsewhere in the docs.

**Comment by tserong** [comment]
For RGW, it's:

1. Renew the certificate.
2. Concatenate the certificate and key into a single file if they're not already
3. Use `ceph config-key set` to apply the new certificate and key (as in the Tip at the bottom of https://documentation.suse.com/ses/7.1/single-html/ses-deployment/#cephadm-deploy-using-secure-ssl-access)
4. Restart RGW by running `ceph orch restart rgw.default.default` (but replace `rgw.default.default` with your actual RGW service name)

Note that if you originally deployed by specifying a `rgw_frontend_ssl_certificate` in the rgw spec, the spec will now be out of sync with the certificate that's actually being used. It may be best to delete rgw_frontend_ssl_certificate from the spec to avoid future confusion.

**Comment by tbazant** [comment]
progress tracked inhttps://github.com/SUSE/doc-ses/pull/1061

**Comment by tserong** [comment]
For renewing the Ceph Dashboard SSL certificate, the procedure is essentially the same as initial SSL configuration as documented in https://documentation.suse.com/ses/7.1/html/ses-all/dashboard-initial-configuration.html#dashboard-ssl.

If you're using self-signed certificates, generate a new one with `ceph dashboard create-self-signed-cert` then restart ceph mgr as mentioned in "Tip: Restarting the Ceph Manager processes".

If you're using certificates signed by a CA, once you've got the new certificate and key, use `ceph dashboard set-ssl-certificate -i dashboard.crt` and `ceph dashboard set-ssl-certificate-key -i dashboard.key`, then restart ceph mgr as described in that tip.

**Comment by tserong** [comment]
For HA RGW (i.e. RGW behind haproxy/keepalived), the procedure is pretty similar to iSCSI:

1. Renew the certificate.
2. Plug the new certificate and key into an ingress service spec yaml, as you do during initial deployment (see https://documentation.suse.com/ses/7.1/html/ses-all/deploy-core.html#ceph-ogw-ha)
3. Apply the service spec (e.g. `ceph orch apply -i ingressyaml`)
4. Reconfigure the service, to pick up the new certificate (e.g. `ceph orch reconfig ingress.rgw.default.default`, but replace ingress.rgw.default.default with the actual name of your ingress service).

**Comment by tserong** [comment]
OK, that's all the SSL certificates I'm aware of. @mgfritch do you mind reviewing to see if I've missed anything?
