### ISSUE TITLE
[doc] Issue in "Using certificates signed by CA"

### ISSUE THREAD

**Issue by alex-ioma** [SUSE/doc-ses#1073]
### Type of report
   - [ ] bug
   - [X] feature request

### Source Document
Using certificates signed by CA:

https://documentation.suse.com/ses/7.1/html/ses-all/dashboard-initial-configuration.html#cert-sign-CA

### Summary

How to remove or reset a certificate that was set globally or individually after the application of this command? In my case the certificate is stuck after `set-ssl-certificate` whereas there should exist a command like `unset` or `reset-ssl-certificate` and key.

**Comment by tbazant** [comment]
The upstream docs (https://docs.ceph.com/en/latest/mgr/dashboard/#ssl-tls-support) do have a line for disabling SSL:

```
ceph config set mgr mgr/dashboard/ssl false
```

which was not included in our downstream docs,  but we don’t think the cli formally implements a rm-ssl-certificate command (even though you probably could delete the config-key and restart the mgrs). Regarding replacing an older cert, it’s the same command he referenced:
```
ceph dashboard set-ssl-certificate -i dashboard.crt
ceph dashboard set-ssl-certificate-key -i dashboard.key
```

**Comment by alex-ioma** [comment]
@tbazant thank you for the reply. You are right, removing the key and restarting the mgrs works as well.
