### ISSUE TITLE
[doc] 6.8.1  Manual Node Upgrade Using the Installer DVD

### ISSUE THREAD

**Issue by ajaeger** [SUSE/doc-ses#235]
6.8.1  Manual Node Upgrade Using the Installer DVD

https://documentation.suse.com/ses/6/single-html/ses-deployment/#upgrade-one-node-manual

The next quarterly update medium - to be released next week - will contain a fix for https://bugzilla.suse.com/show_bug.cgi?id=1162545, see also https://download.suse.com/Download?buildid=0Hf9s7nDqOw~

The change adds an option "YAST_ACTIVATE_LUKS=0" that can be given on the YaST command line when booting from DVD so that no password is asked for for encrypted disks.

Let's document the option and state that this needs the Quarterly update from April 2020.

**Comment by asettle** [comment]
https://github.com/SUSE/doc-ses/pull/237
