### ISSUE TITLE
[doc] 18.2.9  Starting the Services

### ISSUE THREAD

**Issue by aaroneg** [SUSE/doc-ses#241]
18.2.9  Starting the Services

https://documentation.suse.com/ses/6/html/ses-all/cha-ses-cifs.html#cephfs-ad-services

As of SLES15SP1, the names are 'smb.service' , 'nmb.service' and 'winbind.service'.

**Comment by asettle** [comment]
Good catch, thanks @aaroneg

**Comment by ddiss** [comment]
Indeed, thanks for catching this. The confusion is due to Samba systemd services carrying a different name to the underlying processes, i.e. the _smb_ service starts the _smbd_ process / daemon.

**Comment by asettle** [comment]
Resolved, thanks
