### ISSUE TITLE
[doc] 18.2.9  Starting the Services assumes non-HA

### ISSUE THREAD

**Issue by ddiss** [SUSE/doc-ses#244]
18.2.9  Starting the Services

https://documentation.suse.com/ses/6/html/ses-all/cha-ses-cifs.html#cephfs-ad-services

As discussed earlier in https://github.com/SUSE/doc-ses/pull/243 , the AD join procedure assumes that Samba services should be enabled / started via systemctl, but this is incorrect if Samba services are managed by Pacemaker, as is the case for High Availability configurations (https://documentation.suse.com/ses/6/html/ses-all/cha-ses-cifs.html#sec-ses-cifs-ha).

**Comment by asettle** [comment]
Thanks for filing @ddiss 
To clarify the intention for this doc bug, are you looking to split the current instructions into two: 
1. Samba services enabled by systemctl
2. Samba services enabled by Pacemaker for HA

Included both in the same (current) location, or are you looking to update teh sec-ses-cifs-ha section and link back to the cephfs-ad-services section?

**Comment by ddiss** [comment]
> To clarify the intention for this doc bug, are you looking to split the current instructions into two:
> 
>     Samba services enabled by systemctl
>     Samba services enabled by Pacemaker for HA
> 
> Included both in the same (current) location, or are you looking to update teh sec-ses-cifs-ha section and link back to the cephfs-ad-services section?

The AD join section is mostly only concerned with the winbind service, so I think it makes sense to keep it where it is. I'm happy to provide content for this.

**Comment by asettle** [comment]
> > To clarify the intention for this doc bug, are you looking to split the current instructions into two:
> > ```
> > Samba services enabled by systemctl
> > Samba services enabled by Pacemaker for HA
> > ```
> > 
> > 
> > Included both in the same (current) location, or are you looking to update teh sec-ses-cifs-ha section and link back to the cephfs-ad-services section?
> 
> The AD join section is mostly only concerned with the winbind service, so I think it makes sense to keep it where it is. I'm happy to provide content for this.

That's great :D thanks @ddiss

**Comment by asettle** [comment]
@ddiss any update? :)
