### ISSUE TITLE
[doc] 19.5  Setting the Log Level

### ISSUE THREAD

**Issue by rbeldin** [SUSE/doc-ses#250]
19.5  Setting the Log Level

https://documentation.suse.com/ses/6/html/ses-all/cha-ceph-nfsganesha.html#ceph-nfsganesha-loglevel

"You change the default debug level NIV_EVENT by editing the file /etc/sysconfig/nfs-ganesha"

This file doesn't exist, but /etc/sysconfig/ganesha exists.   I think the /etc/sysconfig/ganesha  is created in one of nfs-ganesha's rpm scriptlet.  This was seen with nfs-ganesha-2.8.3+git0.d504d374e-3.3.1.x86_64

**Comment by asettle** [comment]
Confirmed, Thanks @rbeldin
