### ISSUE TITLE
[doc] 2.3  Hardware and Software - SES 5.5 on SLES 15 SP1?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#256]
2.3  Hardware and Software

https://documentation.suse.com/ses/6/single-html/ses-tuning/#tuning-hardware-software

SUSE Enterprise Storage 5.5 
-------------------------------
I assume this SES 5.5 line is wrong and should read 6 ?

**Comment by asettle** [comment]
Good catch!
