### ISSUE TITLE
[doc] 3.3.1  RocksDB and WAL - add the info that we do not use separate WAL in case of two device setups

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#257]
3.3.1  RocksDB and WAL

https://documentation.suse.com/ses/6/single-html/ses-tuning/#id-1.5.3.2.8.2

----------------------------------------
In case we have slow (HDD) and fast (NVMe) - we do not create a separate WAL partition (WAL=0) and instead size the RocksDB 64 GB..

**Comment by asettle** [comment]
Pinged @dmbyte for more on this one

**Comment by dmbyte** [comment]
Isn't that covered in the deployment guide?

**Comment by Martin-Weiss** [comment]
True - but if we discuss the calculation of the size in the tuning guide it needs to be complete, too.
So probably remove the calculation and put it into the deployment guide?

**Comment by asettle** [comment]
We want to make sure we're not duplicating :) if we discuss in the deployment guide, I can simply cross-link.

**Comment by asettle** [comment]
With no other ideas on this one, I will simply cross-ref to https://documentation.suse.com/ses/6/single-html/ses-deployment/#ses-bp-mindisk and close. Thanks.
