### ISSUE TITLE
[doc] 4.1  SUSE Linux Enterprise Install and Validation of Base Performance - install only whats required

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#258]
4.1  SUSE Linux Enterprise Install and Validation of Base Performance

https://documentation.suse.com/ses/6/single-html/ses-tuning/#tuning-sles

-------------------

It is fine to install x-server as long as the default target is NOT graphical and X is only started on demand. In this case X would not require memory and CPU.

However - during install, upgrade and patch the more packages are installed the longer it takes and the more load can be caused.. so recommendation is to install only what is required and not more.. (might be minimal plus some packages)

**Comment by asettle** [comment]
@Martin-Weiss - I'm not sure what you want us to change here. I believe it is our recommendation to stick to saying "During the OS installation, do not select an install pattern that includes an X-server." Unless @ajaeger believes we should change our specific _product recommendations_.

Keeping in mind this is our product documentation, and we need to have a singular recommendation, and be consistent in that. This sounds like it could make a good TID, to explain other options.

**Comment by ajaeger** [comment]
Martin, do you have a specific rewording proposal? Otherwise let's stay with what we have...

**Comment by Martin-Weiss** [comment]
The whole sentence about "x-server" should be something like:

Please install only the minimum of required patterns for the servers.  In case you decide to add X-Server pattern ensure to configure the server for multiuser.target and NOT use graphical.target.

**Comment by dmbyte** [comment]
I would rather suggest leaving it as is.  If the x-server is there, it may inadvertently be left on.  Better to recommend it not be installed at all.

**Comment by Martin-Weiss** [comment]
For the recommendation not to install it at all we are aligned. I just would like to see the additional recommendation for "runlevel =3" - so NOT "graphical target" as we have so many customers that install X because they are more familiar with graphics.. and a manual "startx" helps them.

**Comment by asettle** [comment]
I will leave this open until an agreement is made. No further action from docs at this time.

**Comment by asettle** [comment]
I will go ahead and close this. The original author and the product manager have both indicated that it is fine as it is. Please discuss offline if there's an issue, and reopen only if there is an agreement :) thanks all.
