### ISSUE TITLE
[doc] 3.1.1  Network Tuning  - details about LACP settings - especially the hash mode

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#259]
3.1.1  Network Tuning

https://documentation.suse.com/ses/6/single-html/ses-tuning/#id-1.5.3.2.6.7

----------------------

We should add the recommendation to use hash mode 2 or 2+3.
(3+4 can cause problems)

**Comment by asettle** [comment]
@Martin-Weiss why is this the recommendation? Could you provide a little more context to this change?

**Comment by Martin-Weiss** [comment]
See bonding.txt https://www.kernel.org/doc/Documentation/networking/bonding.txt explanation for xmit_hash_policy

**Comment by asettle** [comment]
This looks like a potential request duplicate to: https://github.com/SUSE/doc-ses/issues/261

**Comment by asettle** [comment]
@Martin-Weiss I will close this out as it is a duplicate, and add this content into the best practices guide as we suggested. Cheers.
