### ISSUE TITLE
[doc] 4.1.2  Storage Performance - add fio command examples

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#260]
4.1.2  Storage Performance

https://documentation.suse.com/ses/6/single-html/ses-tuning/#id-1.5.3.3.4.6

------------------------------
Similar to the iperf3 command we should also give a fio command example, here.

**Comment by asettle** [comment]
Same question as the other bug reports: Could you please explain what issue you ran into to prompt the bug report? 

What kind of fio command exmaples are you looking for? IOPS? Latency? Throughput?

**Comment by Martin-Weiss** [comment]
Ever tried to run fio and compare it? Basically to have a comparable result the same parameters need to be used and due to that I believe we should give the right example.

Examples for all - latency, throughput and IOPS.

**Comment by asettle** [comment]
I'm not sure I agree with this addition. the `--bs` (block size) and `--size` values would depend on your hardware/configuration/setup etc. It's quite hard to have a 1 size fits all "fio config file/examples" that would be adequate for this doc 

The presumption in documents like this is that the user is able to look at other resources, such as: https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd#how-and-why

If you don't know how to use `fio`, I do not believe we should be encouraging people to just follow some random config file/examples

**Comment by Martin-Weiss** [comment]
How useful is the document if it opens up more questions than it answers? I really believe we have to give a guideline and not just non-detailed high level recommendations..

**Comment by asettle** [comment]
This Tuning Guide is delivered entirely as a reference point, as we noted in the introduction also, _"This reference guide is targeted at architects and administrators who need to tune their SUSE Enterprise Storage cluster for optimal performance. Familiarity with Linux and Ceph are assumed."_

This type of document is not as exhaustive as traditional product documentation, and is designed to only be prescriptive. If you want to change the way this document is designed, the entire scope needs to be revised, and that is not possible for SES 6. Please speak to David if you have any more questions.

**Comment by Martin-Weiss** [comment]
Ok - I give up - I tried to help but I do not go down this road and discuss scope vs. delivery.  This is out of my scope and I have not been involved in defining the scope for this document.

I can just provide feedback based on what I read and match that to what the customers I had to deal with would expect - maybe the scope is for other customers.

**Comment by asettle** [comment]
If you have examples, Martin, I'd be happy to include them. But I'm just trying to explain that including examples for using FIO isn't as simple as copying and pasting commands for customers to use. I don't want to include "just anything" because it might be helpful because it could very well be just as useless in this scenario. If @dmbyte is willing to run these commands, and provide examples based on his setup, I'll include those.

My comment about it being a reference guide is that a reference guide traditionally does not cover the A-B stuff. It is designed to be a more advanced version of a user guide, created for the users who are familiar with the software but need some details or a quick guidance. So it can't be treated or reviewed the same way as our other product documentation.

**Comment by Martin-Weiss** [comment]
I believe when we explain how to tune the motor of a car - we also have to explain which screw driver needs to be used and how. So far the biggest challenge for customers was to find out how to use fio, interpret the results and compare them with others.

So while I know and understand the complexity and also recommend to use fio these are the standard commands I use:

Simple destructive write bandwidth test:
dd if=/dev/zero of=/dev/$DISK bs=1G count=10 oflag=direct

Simple destructive write latency test:
dd if=/dev/zero of=/dev/$DISK bs=4k count=10000 oflag=direct

Simple write bandwidth test with fio i.e. against an RBD:
fio --ioengine=psync --rw=write --size=100G --direct=1 --bs=1G --refill_buffers --numjobs=1 --name=test --filename=/dev/rbd/iscsi-images/rbd01

Simple write latency test with fio i.e. against an RBD:
fio --ioengine=psync --rw=write --size=400M --direct=1 --bs=4k --refill_buffers --numjobs=1 --name=test --filename=/dev/rbd/iscsi-images/rbd01

I know that this is far away from measuring the full IO patterns but this gives a good start and helps..
I will also send you a document with more information on what I test most often.. maybe we can just take some examples and add them here to make it easier for our customers.

**Comment by asettle** [comment]
Attaching the document in question for @dmbyte to review.

**Comment by asettle** [comment]
[SES Appliance 3.0 @ Thomas Krenn v0.3.docx](https://github.com/SUSE/doc-ses/files/4540600/SES.Appliance.3.0.%40.Thomas.Krenn.v0.3.docx)

**Comment by dmbyte** [comment]
perhaps the use of FIO commands are better targetted for a best practice doc?  That would allow it to be developed more fully and to discuss use of the various engines, S3, aio, RADOS, etc?

**Comment by Martin-Weiss** [comment]
Good point - yes - in the best practice guide the performance measurements and tuning need to be covered anyway!

**Comment by asettle** [comment]
> Good point - yes - in the best practice guide the performance measurements and tuning need to be covered anyway!

Martin - I'm going to close this out, but you can still link to it :) here's the best practices doc we were working on (but moved to a suse etherpad) to be added to: https://etherpad.nue.suse.com/p/bestpractices-ses7
