### ISSUE TITLE
[doc] 4.1.1  Network Performance - explain a bit about the trunk

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#261]
4.1.1  Network Performance

https://documentation.suse.com/ses/6/single-html/ses-tuning/#id-1.5.3.3.4.5
---------------------

Depending on the hash mode and client vs. server bandwidth we might have to use multiple iperf in parallel to measure the full combined bandwidth possible. (single connection vs. multiple parallel connections)

**Comment by asettle** [comment]
@Martin-Weiss could you please add more information?

What is the scenario in which we _might_ need to use multiple iperf? What is the issue you ran into that prompted this bug report?

**Comment by Martin-Weiss** [comment]
> 
> 
> @Martin-Weiss could you please add more information?
> 
> What is the scenario in which we _might_ need to use multiple iperf? What is the issue you ran into that prompted this bug report?

Depending on the hash settings for your bond - even with LACP only one channel might be used. And depending on these hash settings you need to adjust your test case.

Hash on layer 2 -> mac address based load distribution
Hash on layer 3 -> ip address based load distribution
Hash on layer 3+4 -> ip address and port based load distribution (but has issues)

details can also be found in bonding.txt i.e. https://www.kernel.org/doc/Documentation/networking/bonding.txt

**Comment by Martin-Weiss** [comment]
To be more clear - I mean xmit_hash_policy

**Comment by dmbyte** [comment]
Martin, I'd say feel free to write up the revised text for the section.

**Comment by Martin-Weiss** [comment]
I would do that if I had the time to do so.. ;-)

**Comment by asettle** [comment]
In that case, since this is a documentation feature request and there is no time to offer further text, I will close this bug out by COB.

**Comment by Martin-Weiss** [comment]
At least add a link to bonding.txt with the proper reference to the xmit_hash_policy section and recommend reading that section.

**Comment by asettle** [comment]
We do not link to external sources in product documentation as it does not build appropriate in PDF format, and has issues with our external customer base that cannot access such files. This is our policy :)

**Comment by asettle** [comment]
So, you'd specifically want this section:

`xmit_hash_policy

	Selects the transmit hash policy to use for slave selection in
	balance-xor, 802.3ad, and tlb modes.  Possible values are:

	layer2

		Uses XOR of hardware MAC addresses and packet type ID
		field to generate the hash. The formula is

		hash = source MAC XOR destination MAC XOR packet type ID
		slave number = hash modulo slave count

		This algorithm will place all traffic to a particular
		network peer on the same slave.

		This algorithm is 802.3ad compliant.

	layer2+3

		This policy uses a combination of layer2 and layer3
		protocol information to generate the hash.

		Uses XOR of hardware MAC addresses and IP addresses to
		generate the hash.  The formula is

		hash = source MAC XOR destination MAC XOR packet type ID
		hash = hash XOR source IP XOR destination IP
		hash = hash XOR (hash RSHIFT 16)
		hash = hash XOR (hash RSHIFT 8)
		And then hash is reduced modulo slave count.

		If the protocol is IPv6 then the source and destination
		addresses are first hashed using ipv6_addr_hash.

		This algorithm will place all traffic to a particular
		network peer on the same slave.  For non-IP traffic,
		the formula is the same as for the layer2 transmit
		hash policy.

		This policy is intended to provide a more balanced
		distribution of traffic than layer2 alone, especially
		in environments where a layer3 gateway device is
		required to reach most destinations.

		This algorithm is 802.3ad compliant.

	layer3+4

		This policy uses upper layer protocol information,
		when available, to generate the hash.  This allows for
		traffic to a particular network peer to span multiple
		slaves, although a single connection will not span
		multiple slaves.

		The formula for unfragmented TCP and UDP packets is

		hash = source port, destination port (as in the header)
		hash = hash XOR source IP XOR destination IP
		hash = hash XOR (hash RSHIFT 16)
		hash = hash XOR (hash RSHIFT 8)
		And then hash is reduced modulo slave count.

		If the protocol is IPv6 then the source and destination
		addresses are first hashed using ipv6_addr_hash.

		For fragmented TCP or UDP packets and all other IPv4 and
		IPv6 protocol traffic, the source and destination port
		information is omitted.  For non-IP traffic, the
		formula is the same as for the layer2 transmit hash
		policy.

		This algorithm is not fully 802.3ad compliant.  A
		single TCP or UDP conversation containing both
		fragmented and unfragmented packets will see packets
		striped across two interfaces.  This may result in out
		of order delivery.  Most traffic types will not meet
		this criteria, as TCP rarely fragments traffic, and
		most UDP traffic is not involved in extended
		conversations.  Other implementations of 802.3ad may
		or may not tolerate this noncompliance.

	encap2+3

		This policy uses the same formula as layer2+3 but it
		relies on skb_flow_dissect to obtain the header fields
		which might result in the use of inner headers if an
		encapsulation protocol is used. For example this will
		improve the performance for tunnel users because the
		packets will be distributed according to the encapsulated
		flows.

	encap3+4

		This policy uses the same formula as layer3+4 but it
		relies on skb_flow_dissect to obtain the header fields
		which might result in the use of inner headers if an
		encapsulation protocol is used. For example this will
		improve the performance for tunnel users because the
		packets will be distributed according to the encapsulated
		flows.

	The default value is layer2.  This option was added in bonding
	version 2.6.3.  In earlier versions of bonding, this parameter
	does not exist, and the layer2 policy is the only policy.  The
	layer2+3 value was added for bonding version 3.2.2.`

Included in the docs? After the example is the only place I can see it being? @dmbyte would you like to review?

**Comment by Martin-Weiss** [comment]
I am find with referring to the source of that information and give a clear advice to use layer 2 / layer 2+3 and also explain how to measure with multiple parallel iperf3 sessions if the combined and expected bandwidth will be achieved. No need to copy and maintain the information duplicated.

**Comment by asettle** [comment]
> I am find with referring to the source of that information and give a clear advice to use layer 2 / layer 2+3 and also explain how to measure with multiple parallel iperf3 sessions if the combined and expected bandwidth will be achieved. No need to copy and maintain the information duplicated.

I'll look into it, but I don't think we can just recommend for customers to look up a document on a server. Esp an "unofficial" document, as such. I'll check in and see what's protocol for that. 

But in general, I'm still going to need more information on the _"clear advice to use layer 2 / layer 2+3 and also explain how to measure with multiple parallel iperf3 sessions if the combined and expected bandwidth will be achieved."_

**Comment by Martin-Weiss** [comment]
bonding.txt is an official document that is even part of our kernel-source rpm package. If you want to read it - zypper in kernel-source ..

SUSE recommends to configure bonding with xmit_hash_policy layer 2+3 or layer 2. This will distribute the load among the interfaces based on source and target MAC address (layer 2) or based on source and target IP address (layer 2+3). So testing with a single session and using only two IP addresses or two MAC addresses with the test will not allow to see and measure the combined bandwidth of  multiple NICs in one LACP bond. To test this it is required to run multiple iperf3 -s -p 5901 && iperf3 -s -p5902 ..." on the target host and then execute multiple iperf3 on other servers in parallel using i.e. "iperf3 -c <target server> -p 5901" on client server1 and "iperf3 -c <target server> -p 5902" on client server2..

**Comment by asettle** [comment]
> bonding.txt is an official document that is even part of our kernel-source rpm package. If you want to read it - zypper in kernel-source ..

Right, Martin, I am very aware. We do not link to kernel-source rpm package documents because we have publishable guidelines. I will find out what is the best option here, and get back to you.

**Comment by asettle** [comment]
Good thing I checked in with the team, we can probably simply link to this: https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-network.html#sec-network-iface-bonding after your text

The other option they did agree to was of course, `For more information refer to /usr/<FOOBAR>/kernel/doc/README.baz (requires the installation of teh package kernel-source)"` but that won't link to anything, it will be dead. I think it's better to link to the SLES15-SP1 document.

**Comment by asettle** [comment]
> bonding.txt is an official document that is even part of our kernel-source rpm package. If you want to read it - zypper in kernel-source ..
> 
> SUSE recommends to configure bonding with xmit_hash_policy layer 2+3 or layer 2. This will distribute the load among the interfaces based on source and target MAC address (layer 2) or based on source and target IP address (layer 2+3). So testing with a single session and using only two IP addresses or two MAC addresses with the test will not allow to see and measure the combined bandwidth of multiple NICs in one LACP bond. To test this it is required to run multiple iperf3 -s -p 5901 && iperf3 -s -p5902 ..." on the target host and then execute multiple iperf3 on other servers in parallel using i.e. "iperf3 -c -p 5901" on client server1 and "iperf3 -c -p 5902" on client server2..

@ajaeger do you have any issue with this recommendation wording? Thanks.

**Comment by ajaeger** [comment]
I'm fine, like to have @dmbyte to give final blessing.

**Comment by dmbyte** [comment]
looks fine to me
