### ISSUE TITLE
[doc] 4.2.1  CPU Mitigations - explain how to do this via grub settings

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#262]
4.2.1  CPU Mitigations

https://documentation.suse.com/ses/6/single-html/ses-tuning/#id-1.5.3.3.5.3
-----------------------------
mitigations=off is set in the grub2.cfg via adjusting /etc/default/grub and executing grub2-install.. and reboot.

**Comment by asettle** [comment]
@Martin-Weiss could you please be more verbose as to what you're expecting here?

Why do we need grub settings instructions? What is the bug prompting this change in the steps?

**Comment by Martin-Weiss** [comment]
Maybe it is sufficient to refer to https://www.suse.com/support/kb/doc/?id=000019439 and explain the changes in  https://documentation.suse.com/ses/6/single-html/ses-tuning/#tuning-appendix-a 

(not all the servers in a SES cluster might be salt minions and not every customer is familiar with creating and adjusting salt states)

P.S. https://documentation.suse.com/ses/6/single-html/ses-tuning/#tuning-appendix-a seems to be outdated regarding the mitigation settings..

**Comment by dmbyte** [comment]
Martin is right, the appendix-a needs to reflect mitigations=off vs the individual callouts.

**Comment by asettle** [comment]
Aside from referencing the product documentation (which I found available, here for future reference: https://documentation.suse.com/sles/15-SP1/single-html/SLES-deployment/#sec-boot-parameters-advanced-cpu-mitigations )

I think I would need to see what changes your expecting in the example. My understanding is that we alter the steps to say:

1. Set `mitigations=off` in the grub2.cfg by adjusting `/etc/default/grub` and executing `grub2-install`. For more information see (the link above to the SLES information on cpu mitigation)
2. Reboot.
3. Create directory named my_kerntune in /srv/salt/.
.... Continue as normal.

@dmbyte @Martin-Weiss ?

**Comment by Martin-Weiss** [comment]
Yes - that is fine for me. Just the reference to the salt state is what I would not add as "mandatory 3." - I would more call it "please find an example for a salt state adjusting the grub2 config in appendix...".

**Comment by asettle** [comment]
@dmbyte let me know if that's correct and I'll go ahead :) thanks!

**Comment by dmbyte** [comment]
Yes, what Martin suggests is fine
