### ISSUE TITLE
[doc] 4.2.4.1.1  Jumbo Frames - MTU needs to be set for all the respective devices in their ifcfg files.

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#270]
4.2.4.1.1  Jumbo Frames

https://documentation.suse.com/ses/6/single-html/ses-tuning/#id-1.5.3.3.5.6.4.2

-----------------------------

<SNIP>
To set this persistently, utilize YaST to set the MTU for the bonded interface. 
</SNIP>

should be adjusted to

<SNIP>
To set this persistently, utilize YaST to set the MTU for all the used network interfaces or adjust the /etc/sysconfig/network/ifcfg-* files MTU settings and restart the network.

Please ensure to have the Jumbo frames enabled on all switches, routers and network cards that will transport these packets.
</SNIP>

**Comment by dmbyte** [comment]
I think this is a reasonable addition to the language there.
