### ISSUE TITLE
[doc] 4.2.4.1.2  PCIe Bus Adjustment - how to make this persistent?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#271]
4.2.4.1.2  PCIe Bus Adjustment

https://documentation.suse.com/ses/6/single-html/ses-tuning/#id-1.5.3.3.5.6.4.3

-------------------------------

salt cmd.run just adjusts settings "on the fly" and after a reboot they are back on default. So when using these tunings we also should advice on how to make this persistent so it survives a reboot.

(this needs to be done for the whole document - so search for all salt '*' cmd.run.. and add the info how to make this persistent)

**Comment by asettle** [comment]
@dmbyte - thoughts?

**Comment by dmbyte** [comment]
mmmm.. good question.. probably a udev rule to do that.

**Comment by Martin-Weiss** [comment]
And this also might have to move over to best practice guide.. all the salt things are not really tuning and IMO have to be best practice..

Just for reference a quick example:

/etc/udev/rules.d/70-persistent-net.rules

SUBSYSTEM=="net", ACTION=="add", DRIVERS=="virtio-pci", ATTR{dev_id}=="0x0", KERNELS=="0000:00:03.0", ATTR{type}=="1", KERNEL=="eth*", NAME="eth0"

--> use "KERNELS" instead of the Mac address.

**Comment by asettle** [comment]
Just because the linking is a little off, are you suggesting the `PCIe Bus Adjustment` section is moved to BP? Do we want to expand this section so it reflects tuning?

**Comment by dmbyte** [comment]
if you read the context of the doc, it talks about using the salt commands to build an iterative total configuration that should later be made persistent.  The focus of the doc is identifying those things that made a positive improvement and understanding what they are and the indicators that they may need to be adjusted.

**Comment by asettle** [comment]
Rolling back to this, without the consideration that this should move to the best practices guide - as this is for SES 6 and the BP guide does not exist - could we please be clear about what changes need to occur here? All I've got so far is that after the user runs `salt '*' cmd.run...` we need to add advice on how to make this persistent so it survives a reboot. The suggestion was to add a udev rule.

Do we have a rule? Is that what @Martin-Weiss has provided? Or do we need  to write up about udev rules, and the user can do that themselves? @dmbyte any advice appreciated on going forward here.

**Comment by asettle** [comment]
Based on David's comment, I'll be closing this for now :) we can continue to iterate and improve for the SES 7 version.
