### ISSUE TITLE
[doc] 5.1  Obtaining Ceph Metrics - how to interprete the output of "ceph daemon osd.0 perf dump"?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#272]
5.1  Obtaining Ceph Metrics

https://documentation.suse.com/ses/6/single-html/ses-tuning/#tuning-obtaining-metrics

---------------------------

Here I read this:

<SNIP>
it is helpful to have an understanding of the critical metrics to monitor and what they indicate
</SNIP>

So this automatically generates the question - where can I get the explanations for this so I can understand the output of "ceph daemon osd.0 perf dump|less". I would have expected the relevant parameters and values being explained, here or getting a pointer to the place where I can find that information..

**Comment by dmbyte** [comment]
the relevant items are covered in the OSD tuning section.  Do we simply need to make it more clear that we are showing the proper form of the command to get data?

**Comment by Martin-Weiss** [comment]
Maybe we just need to re-phrase this sentence or remove it. But looking at "ceph daemon osd.0 perf dump" just gives endless question marks and I am not sure if there are many people that understand this output in detail at all ;-).

**Comment by asettle** [comment]
I'll add a cross reference to the OSD tuning section rather than remove. That should be suitable for now :) thanks all.
