### ISSUE TITLE
[doc] 5.3.1  Logging - add the warning that SUSE will not recommend to do this in production clusters

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#273]
5.3.1  Logging

https://documentation.suse.com/ses/6/single-html/ses-tuning/#id-1.5.3.4.10.2

---------------------------
From my understanding we should not recommend to set this in any production environment this way.. and we should be very clear about this.

**Comment by dmbyte** [comment]
I'll let the engineers decide if the warnings are sufficient.  Keep in mind that anyone tuning ceph and doing a google search will find this in plenty of upstream docs and suggestions.  In my opinion, it's better to show it with the big red flag caveat like we do in the current form.

**Comment by Martin-Weiss** [comment]
Finding something in the internet vs. finding it in an officially and SUSE supported document makes a big difference once it comes to problems..

**Comment by asettle** [comment]
> I'll let the engineers decide if the warnings are sufficient. Keep in mind that anyone tuning ceph and doing a google search will find this in plenty of upstream docs and suggestions. In my opinion, it's better to show it with the big red flag caveat like we do in the current form.

How should we proceed here?

**Comment by dmbyte** [comment]
I'd let @l-mb answer that.

**Comment by l-mb** [comment]
It's fine to document this for performance, but indeed, it does make support/debugging harder and might require the user to recreate the problem with more logging re-enabled.

**Comment by asettle** [comment]
> It's fine to document this for performance, but indeed, it does make support/debugging harder and might require the user to recreate the problem with more logging re-enabled.

Is the current warning we have in the docs sufficient?
`This tuning should be used with caution and understanding that logging will need to be re-enabled should support be required. This implies that an incident would need to be reproduced after logging is re-enabled.`

**Comment by l-mb** [comment]
LGTM!

**Comment by asettle** [comment]
Brilliant. Closing as LGTM ;)
