### ISSUE TITLE
[doc] 5.5.1  MDS Tuning - Typo: ceph-daemon perf dump -> ceph daemon perf dump

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#274]
5.5.1  MDS Tuning

https://documentation.suse.com/ses/6/single-html/ses-tuning/#id-1.5.3.4.12.3

---------------------
I assume

ceph-daemon perf dump

should read

ceph daemon perf dump

**Comment by Martin-Weiss** [comment]
Maybe you can add "ceph daemon mds.<short-host-name> perf dump"

Took me a while how to call the command for the MDS daemon.. - in my case:

ceph daemon mds.ses-5-1 perf dump

**Comment by dmbyte** [comment]
Martin is completely right.  not sure how I missed this in the checking, but yes, it should be as he shows.  Thanks Martin.  I also like the idea of showing the mds example command, though I would make it a little more obvious for the casual reader:
ceph daemon mds.node3 perf dump

**Comment by asettle** [comment]
Added the example command the best way I knew how: https://github.com/SUSE/doc-ses/pull/275/files#diff-6bbfb44b26ddfc527ec621ffca0e9f83
