### ISSUE TITLE
[doc] 6.3.3  Deploy Cluster

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#294]
6.3.3  Deploy Cluster

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-deploy

Ricardo Marques: "It would be great to document that, when reboot is enabled in ceph-salt config (it's enable by default), after package updates, minions will reboot automatically (if needed).
if salt master (the host where you are running the ceph-salt apply command) is part of the ceph cluster (is a /ceph_cluster/minion) and needs a reboot, this reboot should be done manually and after rebooting the master, the user must run ceph-salt apply again to continue the deployment"

**Comment by ricardoasmarques** [comment]
We should use this issue to document `ceph-salt` system updates and reboots in general, those options are configured under:

- **/system_update/packages**
When enabled, `ceph-salt` will update packages.

- **/system_update/reboot**
When enabled, `ceph-salt` will automatically reboot hosts to apply system package updates (if needed)

**Comment by ricardoasmarques** [comment]
I wonder if we should use this issue to also document that it's NOT recommended to use Salt Master as a Ceph Cluster Node (separate node for the salt-master is a best practice).
