### ISSUE TITLE
[doc] 6.4.3.1  Deploy Ceph Monitors and Ceph Managers

### ISSUE THREAD

**Issue by SchoolGuy** [SUSE/doc-ses#295]
6.4.3.1  Deploy Ceph Monitors and Ceph Managers

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-day2-service-mon

I guess this is a docs problem but may also be something we want to support feature wise. For now the docs are wrong at and it's following terminal examples:

`If all MONs or MGRs are on the same subnet, specify the short host names of the MONs or MGRs you need to add:`

If you try to use multiple hostnames then the command returns the following

```enno2:~ # ceph orch apply mon enno3 enno1
enno1 not valid:  enno1 not one of 'true', 'false'
Invalid command: unused arguments: ['enno1']
orch apply [mon|mgr|rbd-mirror|crash|alertmanager|grafana|node-exporter|prometheus] [<placement>] [--unmanaged] :  Update the size or placement for a service or apply a large yaml spec
Error EINVAL: invalid command```

If I then try this with only one hostname, everything is working out correctly.

**Comment by bk201** [comment]
The first example
```
ceph orch apply mon ses-min1 ses-min2 ses-min3
```
can be changed to
```
ceph orch apply mon ses-min1,ses-min2,ses-min3
```
to support deploy two additional MONs in one command.
