### ISSUE TITLE
monitoring: document Prometheus' security model

### ISSUE THREAD

**Issue by p-se** [SUSE/doc-ses#297]
**Link To Section**

The documentation should be probably be added to the "Deployment" guide, as its content seems to fit there most. But maybe it makes sense to have it in the "Administration" guide as well.

The monitoring stack is automatically deployed alongside the Ceph cluster, when `cephadm` is used for the deployment and isn't explicitly told not to deploy the monitoring stack. So `cephadm` is the right context, though I do not see a `Monitoring` heading in the `cephadm` chapter in the SES7 documentation where that might fit.

**Summary**

We need to document a non-obvious security model of Prometheus (part of our monitoring stack) to make users aware of it.

**Basic Example**

Basically, the information contained in the note block of https://github.com/ceph/ceph/pull/34902/files#diff-e5580505067bb51bc581a57fbb91df28R391-R403 (marked in the link) needs to be added. It may make sense or be necessary to add the paragraph above it, too, to have a short introduction to that the monitoring topic.

**Motivation**

The security model and its implications may not be obvious and we hence should briefly describe it and have a reference to the full documentation.

**Notes**

"Monitors" or "Mons" are a component of Ceph and are not related to "Monitoring" where its about collecting metadata of the Ceph cluster and related machines to graphically visualize them and provide alerting.

**Comment by asettle** [comment]
Thanks for writing this up, @p-se

**Comment by asettle** [comment]
@tbazant something for the SES 7 deploy guide.

**Comment by asettle** [comment]
@p-se I've added this to our Administration guide, specifically in our Monitoring section, sub-chapter "Prometheus": https://susedoc.github.io/doc-ses/ses6/single-html/ses-admin/#prometheus

I've included a sub-section of Prometheus as "Security Model". PR available now for review :)
