### ISSUE TITLE
[doc] 19.2.1  Automatic Cache Sizing

### ISSUE THREAD

**Issue by BlaineEXE** [SUSE/doc-ses#299]
19.2.1  Automatic Cache Sizing

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#config-auto-cache-sizing

Document does not provide guidance for selecting an osd_memory_target value. This is important, as this selection will further drive hardware requirements.

**Comment by asettle** [comment]
@BlaineEXE so, I'm looking into this for you. But with regards to guidance we do include the minimum requirements here: https://documentation.suse.com/ses/6/single-html/ses-deployment/#sysreq-osd

Could you elaborate a little bit on what you're expecting for hardware requirements?

**Comment by asettle** [comment]
@martin-weiss - do you have any recommendations or advice on this? We usually are not so prescriptive about using a value, but if there's a specific use case for it, we can include in the product docs. But I'm not quite sure I understand the context just yet :)

**Comment by smithfarm** [comment]
As I understand it, @BlaineEXE is asking for this chapter to provide information on:

* what the default value is (4 gigabytes)
* under what circumstances it might be desirable to change it, and 
* how to go about doing so. 

I'm not sure that the `osd_memory_target` setting so much "drives" HW requirements as "is driven by" the HW configuration. In other words, the `osd_memory_target` setting might need to be tweaked to get the most out of the HW.

**Comment by BlaineEXE** [comment]
That is good clarification @smithfarm. I can include that hardware config and num OSDs can lead us to optimize `osd_memory_target`.

**Comment by Martin-Weiss** [comment]
From the history of SES and Ceph the memory allocation and usage for OSDs changed very often so there is a huge misunderstanding and also wrong deployments out there as customers did not realize these changes (also patchlevel in SES 5.x changed behavior).

AFAIK the current sizing for memory is at a minimum of 1 GB + 4 GB per OSD (do not know where the 1 GB is coming from as the 4 GB in `osd_memory_target` already cover the total memory usage.

Based on history some customers had sized their OSD servers memory on the ~1 to ~2 GB per TB plus 2 GB per OSD deamon rule or what ever other rule existed in the past and have i.e. 192 or 256 GB RAM in a server hosting 10 OSDs  (10 * 8 * 2 GB + 20 * 2 GB + some memory for the OS and some other daemons) .

Now after the deployment of SES 5.x patches or SES 6 we can see that the OSDs are just using 40 GB RAM (10 * 4 GB `osd_memory_target`) and the rest of the servers memory is just "ignored". So this is where we have to give customers advice and I would even add a warning in the dashboard and ceph status like "your servers memory is underutilized".

For existing environments we take "memory in the server minus memory for the OS and other daemons and then divide the rest by the number of OSDs and increase osd_memory_target to a value "somewhat smaller". So i.e. with 10 OSDs in a server with 192 GB I would take "( 192 - 32 (for the OS and other daemons)  / 10 ) which would give me 16 - so go to the safe side and use 12 GB for `osd_memory_target`  and see where this leads to.

For new deployments the question is "how much read cache do you need / do you want to have for your workload". With the default of 4 GB we are at a minimum and there is no read-cache so every second read of an object will have to go to the slow disk again. Some systems have client side caching so the cache in the cluster might not be needed but if multiple systems need to read the same objects or if the same clients re-read the same objects and especially if the disks are slow / spinners - there can be a huge improvement of more read-cache RAM and by increasing `osd_memory_target`.

IMO - the `osd_memory_target` setting should be self-tuning based on memory available vs. OSDs and other daemons running on the system - but that is more a nice feature request for the future :-).
