### ISSUE TITLE
[doc] 6.4.5  DriveGroups

### ISSUE THREAD

**Issue by bk201** [SUSE/doc-ses#305]
6.4.5  DriveGroups

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#drive-groups

> In the simplest case this could be the 'rotational' flag (all solid-state drives are to be db_devices, all rotating ones data devices) or something more involved such as 'model' strings, or sizes. 

Providing only `rotational: true` doesn't create WAL/DB devices on SSDs. @jschmid1 Can you confirm this, thanks!

> DeepSea will provide code that translates these DriveGroups into actual device lists for inspection by the user. 

DeepSea -> cephadm

**Comment by jschmid1** [comment]
> In the simplest case this could be the 'rotational' flag (all solid-state drives are to be db_devices, all rotating ones data devices) or something more involved such as 'model' strings, or sizes.

Yes, that's not true and should be removed from the introductory paragraph.

Also, the reference files are not correct anymore.. The whole section needs an overhaul, I assume :/

**Comment by jschmid1** [comment]
I'd suggest to mirror the changes we have in the upstream docs -> https://docs.ceph.com/docs/master/cephadm/drivegroups/
