### ISSUE TITLE
[doc] 6.4.5.1  Specification

### ISSUE THREAD

**Issue by bk201** [SUSE/doc-ses#306]
6.4.5.1  Specification

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#drive-groups-specs

>  For FileStore setups, drive_groups.yml can be as follows: 

No filestore in SES7, this section can be dropped. We need to info user to migrate filestore OSDs to bluestore in upgrade section.

**Comment by tbazant** [comment]
Fixed in https://github.com/SUSE/doc-ses/commit/3866c9540c14a8324a247af864822ca8730d6b1f
