### ISSUE TITLE
SES6: msgr V2 no longer "Tech Preview" (release notes)

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#310]
**Link To Section**

https://www.suse.com/releasenotes/x86_64/SUSE-Enterprise-Storage/6/#Intro.Support.Techpreviews

**Summary**

As of the next SES6 documentation maintenance update (the one that will deliver the related doc changes), msgr V2 is no longer considered a Tech Preview, but rather a fully supported feature of SES6.

**What This Means for the SES6 Release Notes**

In the "Tech Previews" section, the following "Ceph Core" bullet point should be dropped:

New network protocol, or “wire protocol” version 2 (enhancing current protocol, version 1), adding support for on-the-wire encryption. Ceph daemons use this protocoll internally to communicate with one another (called the Messenger and often abbreviated to "msgr"). 

In the immediately following section ("Features"), a new subsection should be added as part of "4.6 RADOS (Ceph core)". It should look like this:

Messenger V2:

SES6 brings a new network protocol, or “wire protocol” version 2 (enhancing the current protocol, version 1). The new protocol brings support for on-the-wire encryption. Ceph daemons use this protocol (called the Messenger and often abbreviated to "msgr") internally to communicate with one another.

**Comment by asettle** [comment]
Sounds good, thanks @smithfarm please shoot a ping when the next SES 6 maintenance update goes through, and I'll update the release notes.

**Comment by smithfarm** [comment]
> Sounds good, thanks @smithfarm please shoot a ping when the next SES 6 maintenance update goes through, and I'll update the release notes.

Thanks, @asettle. Though I think the release notes actually need to be updated **before** the maintenance update goes through...

**Comment by asettle** [comment]
@smithfarm unless I've misunderstood your request, release notes are always updated concurrently/post-mortem to the update. If we are not able to provide our customer with the most recent update and changes, we don't want to document that ahead of time...

**Comment by smithfarm** [comment]
@asettle In this particular case, there is no connection between the ceph maintenance update and the documentation changes related to msgr V2 support. We can document msgr V2 support at any time - no reason to hold it up waiting for completely unrelated code changes in ceph.

**Comment by asettle** [comment]
> @asettle In this particular case, there is no connection between the ceph maintenance update and the documentation changes related to msgr V2 support. We can document msgr V2 support at any time - I'd say the sooner the better. No reason to hold it up waiting for completely unrelated code changes in ceph.

Perfect! Thanks for the heads up :)

**Comment by smithfarm** [comment]
@asettle I reworded the "Summary". It's not waiting for the ceph maintenance update at all... Sorry!

**Comment by asettle** [comment]
@smithfarm as the release notes are hosted in GitLab, I've updated them there. From here, we need to make the package and undergo the MU :) Stefan Knorr is now looking after this. Thank you! 
Here's the update: https://gitlab.suse.de/documentation/release-notes-ses/-/blob/SES_6/xml/release-notes.xml#L520

**Comment by sknorr** [comment]
Opened request 218866 at:

  https://build.suse.de/request/show/218866
