### ISSUE TITLE
SES6: upstream Nautilus point releases section is duplicated, each time with a different letter

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#311]
**Links To Duplicated Sections**

https://documentation.suse.com/ses/6/single-html/ses-admin/#id-1.3.10
https://documentation.suse.com/ses/6/single-html/ses-deployment/#id-1.4.7
https://documentation.suse.com/ses/6/single-html/ses-tuning/#id-1.5.7

**Summary**

The chapter/section "Ceph Maintenance Updates Based on Upstream 'Nautilus' Point Releases" appears in each documentation book. This is perhaps by design (though I personally would not do it this way), but we also have the Glossary which is also so duplicated.

The difference between "Glossary" and "Ceph Maintenance Updates Based on Upstream 'Nautilus' Point Releases" is that the former has no letter associated, while the latter gets an automatically assigned letter (Appendix B, Appendix D, etc.) which is different for each book. In my mind, this unique letter makes me expect the material to also be unique to the book in question.

**Steps To Reproduce**

1. Read Appendix B of Admin Guide
2. Read Appendix A of Deployment Guide
3. Read Appendix D of Tuning Guide
4. Note that they are all identical, except that each has a different letter

**Expected Results**

To ease maintenance and lessen overall confusion, I would expect that we would not duplicate entire sections, and that given material would appear in the documentation in only one place.

If we really want to duplicate this material and have it in each book, I would prefer to have it as an unnumbered appendix like the Glossary, which is also identical in each book.

**Comment by asettle** [comment]
This is actually something we're working on, as a whole, across the entirity of documentation - better content re-use and strategy. This isn't something I can necessarily fix as part of this release. I will close this from the doc-ses POV, but know that I am copying this request out to the team as a whole, and working on it :)

**Comment by smithfarm** [comment]
Thanks, @asettle
