### ISSUE TITLE
SES6 Deployment Guide: add new "Final Steps" section to SES5.5->6 upgrade procedure

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#315]
**Link To Section**

This issue is about adding a new section in between the following two sections:

https://documentation.suse.com/ses/6/single-html/ses-deployment/#upgrade-main-osd
https://documentation.suse.com/ses/6/single-html/ses-deployment/#filestore2bluestore

**Summary**

The purpose of the new section is to give users some tips on final steps they should take after completing the SES5.5 -> 6 upgrade, as described in the upstream Mimic -> Nautilus upgrade procedure [1].

[1] https://ceph.io/releases/v14-2-0-nautilus-released/#instructions

**What Exact Changes to Make to the SES6 Deployment Guide**

Immediately after existing section "6.12 Upgrade Ceph OSDs", and immediately before existing section "6.13 OSD Migration to BlueStore", insert a completely new section with the following content:

6.13 Final Steps

Final steps to take to complete the upgrade:

1. For each host that has been upgraded (not just OSD nodes, but also MON, MGR, MDS and Gateway nodes, as well as client hosts), you should update your ceph.conf file so that it either specifies no monitor port (if you are running the monitors on the default ports) or references
both the `v2` and `v1` addresses and ports **explicitly**. (Things will still work if only the `v1` IP and port are listed, but each CLI instantiation or daemon will need to reconnect after learning that the monitors also speak the `v2` protocol, slowing things down a bit and preventing a full transition to the `v2` protocol.)

2. Finally, consider enabling the telemetry module to send anonymized usage statistics and crash information to the upstream Ceph developers. To see what would be reported (without actually sending any information to anyone):

        ceph mgr module enable telemetry

        ceph telemetry show

    If you are comfortable with the high-level cluster metadata that will be reported, you can opt-in to automatically report it:

        ceph telemetry on

**Comment by smithfarm** [comment]
@jan--f @tserong: Does this look right to you?

**Comment by tserong** [comment]
The telemetry bits are good, but (unless I'm mistaken) the assimilate conf and generate-minimal-conf bits are going to be problematic, because DeepSea will still want to blat out its default config next time you run stage 3.

**Comment by smithfarm** [comment]
@tserong I dropped the part that mentioned assimilate-conf and generate-minimal-conf. Thanks.
