### ISSUE TITLE
[doc] 6.3.2.10  Configure Cluster Update Behavior

### ISSUE THREAD

**Issue by votdev** [SUSE/doc-ses#316]
6.3.2.10  Configure Cluster Update Behavior

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-reboots

I would like to see an explanation or arguments why or in which situation it might make sense to disable updating the packages or prevent automatic node reboots during cluster deployment.

**Comment by tbazant** [comment]
@ricardoasmarques @sebastian-philipp do we have use cases for changing the default reboot behavior?
