### ISSUE TITLE
[doc] 6.3.2.11  Verify Cluster Configuration

### ISSUE THREAD

**Issue by tspmelo** [SUSE/doc-ses#317]
6.3.2.11  Verify Cluster Configuration

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-verify

in [6.3.2.4 Specify First MON/MGR Node](https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-mon) there is an important note telling you to also add the `admin` role to the `bootstrap` node.
I think this should be reflected in the  `ceph-salt config ls` example.

Current:
```
ceph-salt config ls
o- / ............................................................... [...]
  o- ceph_cluster .................................................. [...]
  | o- minions .............................................. [Minions: 5]
  | | o- ses-master.example.com .................................. [admin]
  | | o- ses-min1.example.com ................................ [bootstrap]
  | | o- ses-min2.example.com ................................. [no roles]
```
Purposed: 
```
ceph-salt config ls
o- / ............................................................... [...]
  o- ceph_cluster .................................................. [...]
  | o- minions .............................................. [Minions: 5]
  | | o- ses-master.example.com .................................. [admin]
  | | o- ses-min1.example.com ......................... [bootstrap, admin]
  | | o- ses-min2.example.com ................................. [no roles]
```

**Comment by tbazant** [comment]
This issue was fixed by another one in the meantime, see
https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-verify
