### ISSUE TITLE
Include selected topics into SES7 Deployment Guide

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#319]
2 Best Practices Introduction

        2.1 Preparing your Documentation
        2.2 Review the Environment
        2.3 Requirements Assessment
        2.4 Review the Design

    3 Infrastructure Services Preparation

        3.1 Prepare Fault Tolerant Time Synchronisation Sources
        3.2 Ensure Proper Name Resolution

    4 Server Installation Preparation

        4.1 Software Staging System
        4.2 Server Installation Framework
        4.3 Image Repository
        4.4 Helm Chart Repository
        4.5 Installing the Operating System
        4.6 Optional: Deploy CaaSP

    5 Server Installation

        5.1 Hardware Preparation
        5.2 Data Center Preparation
        5.3 Update Firmware and BIOS
        5.4 Configure Firmware and BIOS Settings
        5.5 Configure Hardware Date and Time
        5.6 Configure Networking
        5.7 Deploy the Operating System

    6 Server Configuration

        6.1 Configuration Management Using Salt

    7 Verifying the Deployment

        7.1 Test the Deployment
        7.2 Verify Time Synchronization
        7.3 Verify Name Resolution
        7.4 Test Storage Devices
        7.5 Test Network Connections

    8 Cluster Deployment

        8.1 Adjust Ceph Parameters
        8.2 Deploying with cephadm
        8.3 Deploying on top of CaaSP
        8.4 Cluster DNS

    9 Ceph Configuration

        9.1 Adjust Ceph CRUSH Map
        9.2 Adjust Existing Pools
        9.3 Adjust Gateway Settings
        9.4 Verify Functionality

    10 Testing Best Practices

        10.1 Documenting Testplans
        10.2 Functional Testing
        10.3 Fault Tolerance Testing
        10.4 Performance Testing

    11 Operation Best Practices

        11.1 Adding and Removing Disks
        11.2 CRUSH Map Adjustments

    12 Upgrade Practices

**Comment by asettle** [comment]
I think Chapter 9 can go into the Administration Guide, 10 in the Tuning Guide, and 11 in the Administration Guide too.
Check it out and let me know what you think :)

**Comment by tbazant** [comment]
> I think Chapter 9 can go into the Administration Guide, 10 in the Tuning Guide, and 11 in the Administration Guide too.
> Check it out and let me know what you think :)

yes, i agree

**Comment by tbazant** [comment]
got much more urgent stuff, reopen if needed
