### ISSUE TITLE
Part II Cluster Deployment and Upgrade

### ISSUE THREAD

**Issue by brownowski** [SUSE/doc-ses#320]
**Link To Section**
https://documentation.suse.com/ses/6/single-html/ses-deployment/#ses-deployment

**Summary**
The description for "7 Customizing the Default Configuration" is incomplete and finishes with "whi..."

**Comment by asettle** [comment]
Hey @brownowski that is indeed correct, although confusing. The "summary" it is showing is the beginning of the paragraph from here: https://documentation.suse.com/ses/6/single-html/ses-deployment/#ceph-deploy-ds-custom 
I'm just checking in to see if this is something we can change at this time, as the summaries are derived from a character limit set.

**Comment by asettle** [comment]
Sorry, but looks like the way it is setup to take the first para and assumes that isn't optimized to work as a teaser. This is something we can look at potentially being more vigilant about for SES 7. Thanks :)
