### ISSUE TITLE
Add placement specification into day2 deployment section

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#325]
UPDATE: recommend applying services by `apply -i yaml_file` instead of CLI specification
get insipred with
https://ceph.readthedocs.io/en/latest/mgr/orchestrator/#placement-specification

**Comment by sebastian-philipp** [comment]
placement spec in only a part of the service spec. see https://docs.ceph.com/docs/master/mgr/orchestrator/#service-specification

**Comment by sebastian-philipp** [comment]
and export via https://docs.ceph.com/docs/master/mgr/orchestrator/#service-status
