### ISSUE TITLE
[doc] 2  Reporting Software Problems

### ISSUE THREAD

**Issue by tserong** [SUSE/doc-ses#331]
### Type of report
   - [ ] bug
   - [x] feature request

### Source Document
2  Reporting Software Problems:

https://susedoc.github.io/doc-ses/master/single-html/ses-troubleshooting/#report-software

### Summary
Add more information about what supportutils-plugin-ses captures, and what it needs in order to do its job. Ideally something like what I've proposed below :-)

### Notes
supportutils-plugin-ses will try to capture as much useful information as it can about both the ceph cluster as a whole, and about the host on which it is running. Some information, including ceph daemon status, podman image information, rpm verification and some relevant configuration data will be saved to the plugin-ses.txt file inside the supportconfig tar archive. A lot more information, including overall cluster status, logs, and diagnostic data for each currently running ceph daemon will be saved to files in the ceph subdirectory inside the supportconfig tar archive.

When supportconfig is run on an admin node (i.e. a host that has the ceph.conf file and admin keyring), it will be able to capture the overall status of the entire cluster (e.g. `ceph status`, `ceph health`, etc.). If the ceph.conf file and admin keyring are not present, it won't be able to capture overall cluster status, but will *still* capture diagnostic data for each currently running ceph daemon.

In general, when using supportconfig, you will want to run it on an admin node (to ensure the overall cluster status is captured), as well as on any other nodes that are experiencing problems, to ensure it captures diagnostic data for anything and everything that may be relevant.

For example, pretend you have a misbehaving nfs ganesha instance, but nfs ganesha is running on a node that doesn't have the ceph.conf file or admin keyring. In this case you will want to run supportconfig on at least two hosts; the admin node, and the node that's running the misbehaving nfs ganesha instance. If you are having trouble with three OSDs, on three different hosts, you will want to run supportconfig on each of those three hosts, in addition to running it on the admin node.

**Comment by asettle** [comment]
@tserong is this for SES 6 as well as 7?

**Comment by tserong** [comment]
@asettle yes-ish :-)

SES6 doesn't use podman, so my note about "podman image information" doesn't apply there. SES6 also *may* do a better job of getting overall cluster status when run on non-admin nodes, as it will try to find other keys to use to get cluster status, but that's not foolproof, so I'd still advise to run it on an admin node, as well as on any other misbehaving nodes.

**Comment by asettle** [comment]
Thanks @tserong - I'll add @tbazant to this report as he's working on the deploy atm. I'll look into this for SES 6.
