### ISSUE TITLE
[doc] 2.1.1.1  Adding a Private Network to a Running Cluster

### ISSUE THREAD

**Issue by dthpulse** [SUSE/doc-ses#332]
### Type of report
   - [ ] bug

### Source Document
2.1.1.1  Adding a Private Network to a Running Cluster:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#storage-bp-net-private

### Summary

There is another way in SES7 how to edit Ceph configuration. Instead of editing ceph.conf directly there is a command `ceph config` that can do the task. In thi particular example:
`ceph config set global cluster_network 10.0.0.0/24`
And there is no need to restart the services.

**Comment by asettle** [comment]
@ricardoasmarques could I get you to take a look at this one? I've tested, and the command doesn't work. https://docs.ceph.com/docs/master/rados/configuration/network-config-ref/#public-network clearly stated that it must go through ceph.conf, but I'm not sure if that means that upstream is wrong? Would really appreciate any input :)

**Comment by asettle** [comment]
Closing, I've had this open for 20+ days and I can't verify the action suggested, and nor can @ricardoasmarques - if this comes up again, we can revisit.
