### ISSUE TITLE
[doc] 6.3.2.4  Specify Admin Node

### ISSUE THREAD

**Issue by matthewoliver** [SUSE/doc-ses#335]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.3.2.4  Specify Admin Node:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-admin

### Summary
Output of command when following the guide is incorrect. In the last step we've added the admin node to the cephadm role, but the output after now adding a node to the admin group in the doc says:

```
ceph-salt config /ceph_cluster/roles/admin ls
o- admin ................................................... [Minions: 1]
  o- ses-master.example.com ............................ [no other roles]
```

Where as it should end in `[Other roles: cephadm]`.

### Steps To Reproduce
Add all the nodes to cephadm:
 ```ceph-salt config /ceph_cluster/roles/cephadm add '*'```

Then add the master node to (included in the * above) to the admin role:
```
ceph-salt config /ceph_cluster/roles/admin add master.ses7-testing.com
```
### Expected Results (from doc)
```
ceph-salt config /ceph_cluster/roles/admin ls
o- admin ................................................... [Minions: 1]
  o- ses-master.example.com ............................ [no other roles]
```

### Actual Results (what is correct)
```
ceph-salt config /ceph_cluster/roles/admin ls
o- admin .............................................................................................................. [Minions: 1]
  o- master.ses7-testing.com ................................................................................ [Other roles: cephadm]

```

### Notes
This obviously only applies if the doc is to be read as a step by step guide, if your just jumping to assigning an unused minion to an admin role then it's currently correct.

**Comment by asettle** [comment]
Thanks @matthewoliver! Does this apply for SES 7 and SES 6?

**Comment by tbazant** [comment]
Fixed in https://github.com/SUSE/doc-ses/commit/f197d298ce90eb0a8db3f4a8f8d4afad20256824
