### ISSUE TITLE
[doc] 6.3.2.10  Configure Container Registry

### ISSUE THREAD

**Issue by jan--f** [SUSE/doc-ses#338]
### Type of report
   - [x] bug

### Source Document
6.3.2.10  Configure Container Registry:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-registry

### Summary

The steps as documented result in an error due to missing CNI default network.

### Steps To Reproduce

Follow documentation to deploy a registry mirror.

### Expected Results

Working registry mirror.

### Actual Results

Failed podman command:
```
# > podman run -d  --restart=always  --name registry  -p 5000:5000  registry:2 
Error: error configuring network namespace for container 3ff5aee125cceebb68aa1c3da9d48d8b83453d26d3317d2c232149f15fbff5fc: Missing CNI default network

### Notes
<!-- Add any other context about the problem here. -->

This is a multi-network VM cluster. Maybe multiple NICs play a role here.

**Comment by jan--f** [comment]
Looking into necessary steps.

**Comment by jan--f** [comment]
Adding `--net=host` does the trick. As I believe this is what we use for cephadm(@sebastian-philipp can you confirm please?), we should probably use that.

**Comment by jan--f** [comment]
Lets also add two (or one) step to this section before current step 1 that both podman and skopeo need to be installed via zypper:
```
1. Install podman and skopeo:
zypper install ...
```

**Comment by sebastian-philipp** [comment]
﻿﻿

> Adding `--net=host` does the trick. As I believe this is what we use for cephadm(@sebastian-philipp can you confirm please?), we should probably use that.

hm, we're doing this for the cephadm's daemons. That however doesn't mean it's required for the registry. On the contrary, I never needed this for deploying any registries. Including in Sepia a few days ago

**Comment by jan--f** [comment]
> hm, we're doing this for the cephadm's daemons. That however doesn't mean it's required for the registry. On the contrary, I never needed this for deploying any registries. Including in Sepia a few days ago

Which os runs on Sepia? Seems like podman on SLE15SP2 creates not default network configuration, so not specifying anything fails to deploy the registry.

**Comment by jan--f** [comment]
The podman command that ended up working for me was
`podman run -d  --restart=always  --net=host --name registry  -p 5000:5000  registry:2`
