### ISSUE TITLE
[doc] 6.3.2.13  Export Cluster Configuration

### ISSUE THREAD

**Issue by ddiss** [SUSE/doc-ses#339]
6.3.2.13  Export Cluster Configuration

http://docserv.nue.suse.com/documents/SES_current/ses-deployment/single-html/#deploy-cephadm-configure-export

Assuming the user has gone through `6.3.2.6 Generate SSH Key Pair`, the exported json config includes an ssh private key. The user should be very careful when dumping this to a file to ensure that it can't be accessed by others.
I think it makes sense to add a note about this. Another extra precaution might be to change the procedure to:
```
umask 077
ceph-salt export > cluster.json
```

The umask change avoids accidental granting of non-root access (on the same host).

**Comment by asettle** [comment]
@ddiss is this the same for SES 6?

**Comment by ddiss** [comment]
> @ddiss is this the same for SES 6?

I don't think so. SES6 deployment is all salt based, and I don't think we dump any private keys for backup.

**Comment by LenzGr** [comment]
Wouldn't it make more sense for `ceph-salt` to export the file with the appropriate permissions right away? Using `umask` or `chown` sounds like a workaround to me. @ricardoasmarques - what do you think?

**Comment by denisok** [comment]
why we exporting that key at all? maybe export it only with `--yes-i-really-want-priv-key-i-know-what-i-am-doing` option ?
