### ISSUE TITLE
[doc] 6.5.3.2  Deploy Ceph OSDs

### ISSUE THREAD

**Issue by theanalyst** [SUSE/doc-ses#340]
6.5.3.2  Deploy Ceph OSDs

http://docserv.nue.suse.com/documents/SES_current/ses-deployment/single-html/#deploy-cephadm-day2-service-osd

Drive groups syntax has changed to https://docs.ceph.com/docs/master/cephadm/drivegroups/ 
(cc @jschmid1 @ddiss)

**Comment by jschmid1** [comment]
captured here: https://github.com/SUSE/doc-ses/issues/305
