### ISSUE TITLE
SES7 admin guide: explictly mention the mons IP usage when mount cephfs

### ISSUE THREAD

**Issue by luis-henrix** [SUSE/doc-ses#341]
Section "14.1.1 Client Preparation" in this document already recommends the installation of ceph-common package to use the full mount syntax when mounting a ceph filesystem.

It's worth explicitly mentioning that, without this package (and thus without the mount.ceph helper), the monitors IPs will need to be used instead of their names, as the kernel client won't be doing name resolution.

**Comment by luis-henrix** [comment]
Forgot to add a reference to the kernel docs: https://www.kernel.org/doc/html/latest/filesystems/ceph.html#mount-syntax

**Comment by asettle** [comment]
> Forgot to add a reference to the kernel docs: https://www.kernel.org/doc/html/latest/filesystems/ceph.html#mount-syntax

I won't be able to link this in the physical docs I'm afraid - is that what you were after? Is there a specific bit of content from this link you want referenced?

**Comment by luis-henrix** [comment]
Sure, I wasn't expecting this to be linked in the docs.  I just wanted to mention some official kernel docs where this is referred.  Specifically the sentence:

> If /sbin/mount.ceph is installed, a hostname can be used instead of an IP address.

(mount.ceph is provided by the ceph-common package)

Anyway, feel free to ignore that link ;-)

**Comment by asettle** [comment]
@luis-henrix do you want the basic mount syntax included? I'm putting your note in an `<important>` call out after the last sentence.
