### ISSUE TITLE
[doc] 6.5.3.1  Deploy Ceph Monitors and Ceph Managers

### ISSUE THREAD

**Issue by denisok** [SUSE/doc-ses#343]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
6.5.3.1  Deploy Ceph Monitors and Ceph Managers:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-day2-service-mon

### Summary
```If there are five or more nodes in the cluster, we recommend deploying five MONs. A good practice is to have MGRs deployed on the same nodes as MONs.```

it makes sense, if you have 5 we recommend 5.

**Comment by asettle** [comment]
@denisok I'm not sure I'm clear on what you're requesting here. Are you looking for that sentence to be rewritten to clearly state "if you have 5, we recommend 5"?

**Comment by denisok** [comment]
hm, now I see my confusion "nodes" and then "mons", five, five. I just don't read "nodes" somehow it sounds for me as mons mons )))

So you could just disregard, maybe just me.

**Comment by asettle** [comment]
@denisok not at all! Haha, let me check in with @tbazant and see if maybe we can improve it.

**Comment by asettle** [comment]
@tbazant and I agree this makes sense as-is. Thanks!
