### ISSUE TITLE
[doc] 6.3.2.10  Configure Container Registry

### ISSUE THREAD

**Issue by bk201** [SUSE/doc-ses#344]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
6.3.2.10  Configure Container Registry:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-registry

### Summary

The config path needs to be updated after https://github.com/ceph/ceph-salt/pull/262 is merged

**Comment by asettle** [comment]
@ricardoasmarques could you please confirm the details here? :)

**Comment by bk201** [comment]
Sure! I will update more information after:
(1) The PR is merged.
(2) New ceph-salt packages are published to factory.

> @ricardoasmarques could you please confirm the details here? :) The PR linked doesn't provide any details on what is required for a doc update, @bk201 - if you could please provide some more information?

**Comment by asettle** [comment]
Thanks @bk201!

**Comment by asettle** [comment]
Hey @bk201 it looks like the PR is merged, how are the ceph-salt packages going?

**Comment by bk201** [comment]
Thanks, @asettle!
This issue had been resolved by https://github.com/SUSE/doc-ses/pull/375 and https://github.com/SUSE/doc-ses/pull/378.
