### ISSUE TITLE
RBD documentation - mirroring docs are faulty

### ISSUE THREAD

**Issue by trociny** [SUSE/doc-ses#346]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
11.4  Mirroring:

https://susedoc.github.io/doc-ses/master/html/ses-admin/ceph-rbd.html#ceph-rbd-mirror

### Summary

~The mirroring section needs update for SES7:~

~1) The section that describes the rbd-mirror daemon deploy is wrong now:~

 ~https://susedoc.github.io/doc-ses/master/html/ses-admin/ceph-rbd.html#rbd-mirror-daemon~

~I think we have to use the ceph orchestrator now. See this bugzilla ticket for details:~

~https://bugzilla.suse.com/show_bug.cgi?id=1169077~

~2) The upstream documentation is much more superior:~

 ~ https://docs.ceph.com/docs/octopus/rbd/rbd-mirroring/~

~As it includes description for new features -- snapshot based mirroring and bootstrapping peers. The second one simplifies mirroring~ ~configuration significantly. We need to sync our documentation with the upstream.~

The above is completed and this is now for tracking the RBD mirroring docs issue

**Comment by asettle** [comment]
Reopening - we still need to ask the cephadm team about how to properly deploy (enable) rbd-mirror service cc @trociny

**Comment by asettle** [comment]
### Source Document
10.4.1.4  Add Cluster Peer:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#id-1.4.4.5.10.8.9

### Summary

This wouldn't work as in example the non existing client is used (client.remote, client.local).
We can see the client name by running command on both sites:

```
# ceph auth get-or-create client.rbd-mirror-peer
[client.rbd-mirror-peer]
        key = AQC1WHxf90D2BRAAtdnCgcUIoZhN7GJIMEFtDw==
```

so example should looks like:

```
rbd --cluster local mirror pool peer add POOL_NAME client.rbd-mirror-peer@remote
rbd --cluster remote mirror pool peer add POOL_NAME client.rbd-mirror-peer@local
```

It's described in nice detail in official doc:

https://docs.ceph.com/en/latest/rbd/rbd-mirroring/#add-cluster-peer-manually

**Comment by asettle** [comment]
### Source Document
1.5.6  RBD Mirroring:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#dash-rbd-mirror

### Summary

Missing instructions to copy _ceph.conf_ and _keyring_ from primary to secondary cluster.

So that in example that is used in doc (these commands are run from secondary node)

```
cephadm@secondary > rbd --cluster primary mirror pool enable image-pool image
cephadm@secondary > rbd --cluster secondary mirror pool enable image-pool image
```

so on secondary it should looks like 

```
/etc/ceph/primary.conf
/etc/ceph/primary.client.admin.keyring
/etc/ceph/secondary.conf
/etc/ceph/secondary.client.admin.keyring
```


It's good to give an example. So to continue with more detail on what I wrote first it should looks like:

```
cephadm@secondary > cp /etc/ceph/ceph.conf /etc/ceph/primary.conf
cephadm@secondary > cp /etc/ceph/ceph.admin.client.keyring /etc/ceph/primary.client.admin.keyring
cephadm@secondary > scp primary:/etc/ceph/ceph.conf /etc/ceph/secondary.conf
cephadm@secondary > scp primary:/etc/ceph/ceph.client.admin.keyring /etc/ceph/secondary.client.admin.keyring
```

**Comment by asettle** [comment]
The last two bugs are from Denis Polom - combing together as one big doc bug

**Comment by asettle** [comment]
Also tracking in various bugzilla requests: 

1. https://bugzilla.suse.com/show_bug.cgi?id=1177308
2. https://bugzilla.suse.com/show_bug.cgi?id=1177374

**Comment by asettle** [comment]
Bug: #642

### Source Document
1.5.6.2  Enable the <code class="systemitem">rbd-mirror</code> Daemon:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#rbd-mirror-daemon-enable

### Summary
We need an example placement specification as at this point we have not enabled the daemon

**Comment by dthpulse** [comment]
another one 
https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#id-1.4.4.5.10.9.6

you use example:

```
rbd --cluster local feature enable POOL_NAME/IMAGE_NAME journaling
```

but _journaling_ feature doesn't exist.  

Correct is:

```
rbd --cluster local feature enable POOL_NAME/IMAGE_NAME journal
```

**Comment by asettle** [comment]
In https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-rbd-mirror

Would like to see these in the examples:
```
cephadm@local >
```
and for remote

```
cephadm@remote >
```

Rather than:

```
cephadm@adm
```

**Comment by asettle** [comment]
> another one
> https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#id-1.4.4.5.10.9.6
> 
> you use example:
> 
> ```
> rbd --cluster local feature enable POOL_NAME/IMAGE_NAME journaling
> ```
> 
> but _journaling_ feature doesn't exist.
> 
> Correct is:
> 
> ```
> rbd --cluster local feature enable POOL_NAME/IMAGE_NAME journal
> ```

This is quite possibly a bug upstream also: https://docs.ceph.com/en/latest/rbd/rbd-mirroring/#enable-image-journaling-feature

**Comment by tbazant** [comment]
i've resurrected subissues, rest in peace
