### ISSUE TITLE
[doc] 6.5.3.4  Deploy Object Gateways

### ISSUE THREAD

**Issue by theanalyst** [SUSE/doc-ses#347]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.5.3.4  Deploy Object Gateways:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-day2-service-ogw

### Summary

`ceph orch apply rgw REALM_NAME ZONE_NAME \
 --placement="NUM_OF_DAEMONS HOST1,HOST2,..."`

syntax is invalid 

Also dropping the --placement arg probably leads to another health error with cephadm too many values to unpack

**Comment by sebastian-philipp** [comment]
yes. please follow https://docs.ceph.com/docs/master/cephadm/install/#deploy-rgws instead.
