### ISSUE TITLE
SES 7 Release Notes: add SES7 Release Note about end of FileStore support

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#351]
**Link To Section**

This issue is a request to add a Release Note to the SES7 Release Notes.

**Summary**

The new release note should say:

End of FileStore support: As of SES7, FileStore is no longer supported. All FileStore OSDs should be migrated to BlueStore before upgrading from SES6 to SES7.

**Comment by asettle** [comment]
Documented: https://confluence.suse.com/display/SUSEEnterpriseStorage/SES+7+Release+Notes
