### ISSUE TITLE
[doc] 6.5.3.5  Deploy NFS Ganesha

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#352]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.5.3.5  Deploy NFS Ganesha:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-day2-service-nfs

### Summary

The "ceph orch apply nfs" command is presented like this:

```
cephadm@adm> ceph orch apply nfs SERVICE_ID \
 POOL_NAME NAMESPACE \
 --placement="HOST1,HOST2,..."
```

The preceding section, "6.5.3.4 Deploy Object Gateways", presents the following for `--placement`:

```
--placement="NUM_OF_DAEMONS HOST1,HOST2,..."
```

Now, as far as I can tell, the parsing of the `--placement` option is the same for all `ceph orch apply` commands, so I think we should use the same format. In other words, please change the command to:

```
cephadm@adm> ceph orch apply nfs SERVICE_ID \
 POOL_NAME NAMESPACE \
 --placement="NUM_OF_DAEMONS HOST1,HOST2,..."
```

And please add the following additional info right under the command:

```

Where:

SERVICE_ID is an arbitrary string
POOL_NAME is the name of the pool where the NFS-Ganesha RADOS configuration object will be stored
NAMESPACE (optional) is the desired NFS namespace (e.g. "nfs"). For more information on NFS namespaces, see https://docs.ceph.com/docs/master/radosgw/nfs/#namespace-conventions
```

**Comment by smithfarm** [comment]
@sebastian-philipp I'm not sure if everything I wrote, above, is perfectly "kosher". Who could review this?

**Comment by sebastian-philipp** [comment]
lgtm

* instead of advertising the CLI, I'd encourage users to write a cluster.yaml instead and simply call `ceph orch apply -i cluster.yaml`
* yes. placement is the same thing everywhere.
* and yes, we'd probably need a documentation of how to setup cephfs-nfs or rgw-nfs. Something like https://docs.ceph.com/docs/master/cephfs/nfs/ maybe. or https://docs.ceph.com/docs/master/radosgw/nfs/

**Comment by tbazant** [comment]
@sebastian-philipp Please ask for cephfs-nfs or rgw-nfs documentation in a separate issue
