### ISSUE TITLE
Document how to deploy "NFS backed by CephFS" and "NFS backed by RGW"

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#354]
**Link To Section**

Section presumably does not exist yet (?)

**Summary**

This section should describe how to deploy an NFS Gateway in SES7 so that it exports:

* CephFS over NFS
* RGW buckets over NFS

**Some upstream docs to refer to**

* https://docs.ceph.com/docs/master/cephfs/nfs/
* https://docs.ceph.com/docs/master/radosgw/nfs/#configuring-an-nfs-ganesha-instance

**Caveats**

This section should be linked to from "6.5.3.5 Deploy NFS Ganesha". A person trying to deploy NFS over CephFS/RGW might start from that section, yet it describes only "ceph orch apply nfs" which only enables/starts the NFS-Ganesha daemon(s), without any setup or configuration.

**Comment by asettle** [comment]
For this specific request, do you mean these configuration details specifically: https://docs.ceph.com/docs/master/radosgw/nfs/#configuring-an-nfs-ganesha-instance If not, do you think we should be including everything that is upstream?  

For later context, a link to Deploy NFS Ganesha: https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-day2-service-nfs

**Comment by asettle** [comment]
I'm going to combine this bug with https://github.com/SUSE/doc-ses/issues/355 so I can keep track of everything that needs to be update for NFS.

**Comment by asettle** [comment]
*Request*: This section should describe how to deploy an NFS Gateway in SES7 so that it exports CephFS over RGW.
*Summary*: This section should be linked to from "6.5.3.5 Deploy NFS Ganesha". A person trying to deploy NFS over CephFS might start from that section, yet it describes only "ceph orch apply nfs" which only enables/starts the NFS-Ganesha daemon(s), without any setup or configuration.

**Comment by smithfarm** [comment]
> For this specific request, do you mean these configuration details specifically: https://docs.ceph.com/docs/master/radosgw/nfs/#configuring-an-nfs-ganesha-instance If not, do you think we should be including everything that is upstream?

That link describes NFS backed by RGW, but this issue was originally intended to cover deploying NFS backed by CephFS,  which is a different topic. The "NFS backed by RGW" topic was supposed to be the subject matter of #355. But if you want to combine both into a single issue, that's fine with me.

**Comment by asettle** [comment]
> > For this specific request, do you mean these configuration details specifically: https://docs.ceph.com/docs/master/radosgw/nfs/#configuring-an-nfs-ganesha-instance If not, do you think we should be including everything that is upstream?
> 
> That link describes NFS backed by RGW, but this issue was originally intended to cover deploying NFS backed by CephFS, which is a different topic. The "NFS backed by RGW" topic was supposed to be the subject matter of #355. But if you want to combine both into a single issue, that's fine with me.

Answers my question, sorry for the backwards application :)

**Comment by asettle** [comment]
Notes:
- NFS Ganesha was used in SES6 and SES5 as well (but for SES 7 DeepSea references will need to change)
- Nothing has changed in how NFS Ganesha works - just the commands to deploy it are a little different
- Still in active development

@supriti would you have any insight here? :)

**Comment by asettle** [comment]
I'm thinking the content should either go into:
1. The NFS Ganesha chapter: https://susedoc.github.io/doc-ses/ses6/single-html/ses-admin/#cha-ceph-nfsganesha
2. Split into two

**Comment by smithfarm** [comment]
The following upstream tracker issue is relevant for the "NFS backed by RGW" part of this ticket:

* https://tracker.ceph.com/issues/46335

**Comment by asettle** [comment]
Update: Spoke to @supriti about this issue, and she'll take a look through the issue and content.

**Comment by asettle** [comment]
Note: NFS Ganesha will not be deployed using the `ceph nfs` CLI (see #423 - the CLI won't be ready). Everything `ganesha.conf` related will be put into the `service_type: nfs` spec. It will still be accessible using the dashboard.

**Comment by asettle** [comment]
Closing due to NFS Ganesha no longer being backed by `ceph fs`. 

New NFS Ganesha issue: https://github.com/SUSE/doc-ses/issues/477
