### ISSUE TITLE
Document how to configure NFS over RGW

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#355]
**Link To Section**

Section presumably does not exist yet (?)

**Summary**

This section should describe how to deploy an NFS Gateway in SES7 so that it exports CephFS over RGW.

**Basic Example**

https://docs.ceph.com/docs/master/radosgw/nfs/

**Caveats**

This section should be linked to from "6.5.3.5 Deploy NFS Ganesha". A person trying to deploy NFS over CephFS might start from that section, yet it describes only "ceph orch apply nfs" which only enables/starts the NFS-Ganesha daemon(s), without any setup or configuration.

**Comment by asettle** [comment]
Closing this and combining it with #354
