### ISSUE TITLE
[doc] 6.3.2.1  <code class="systemitem">ceph-salt</code> Shell

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#357]
### Type of report
   - [ X ] bug
   - [ ] feature request

### Source Document
6.3.2.1  <code class="systemitem">ceph-salt</code> Shell:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-shell

### Summary
The first command output from `ceph-salt config` does not show any minions under "ceph_cluster->minions" but the next output from `cd /ceph_cluster/minions/` does show a master and a minion. But in between are no steps described how to actually get any masters/minions listed.

In my test env, there are no minions (or master) listed in "ceph_clusters->minions" but `salt '*' test.ping` does work fine and I have 67 minions listed.

**Comment by toabctl** [comment]
Ok. So the steps to add minions to ceph-salt is described in https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-minions . But that's confusing because in the output, minions are already listed but added later in the docs.

**Comment by asettle** [comment]
> Ok. So the steps to add minions to ceph-salt is described in https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-minions . But that's confusing because in the output, minions are already listed but added later in the docs.

I had the same concerns. I might leave this one open and see if anyone else files something similar.

**Comment by LenzGr** [comment]
While it's just an example of how to use the `ls` command, it could indeed be confusing. I'll fix this along with another small improvement suggestion I had for this chapter.
