### ISSUE TITLE
[doc] 6.3.2.7  Configure Time Server

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#358]
### Type of report
   - [ ] bug
   - [ X ] feature request

### Source Document
6.3.2.7  Configure Time Server:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-ntp

### Summary
In the time-server docs, it should be mentioned that it's also possible to disable time server handling (in case the nodes already have ntp configured).

```
/time_server> ls
o- time_server .......................................................................................................... [disabled]
  o- external_servers ...................................................................................................... [empty]
  o- server_hostname ..................................................................................................... [not set]
  o- subnet .............................................................................................................. [not set]
/time_server>
```

**Comment by asettle** [comment]
@toabctl where would I be able to find the instructions on how to disable time server handling?

**Comment by toabctl** [comment]
@asettle I found out by trying (which was not difficult given that I've seen the PR on github implementing this). But I think it would be good to mention that you can disable `chrony` configuration if you already have time management (via chrony or ntp or something) available on the nodes.

**Comment by asettle** [comment]
> @asettle I found out by trying (which was not difficult given that I've seen the PR on github implementing this). But I think it would be good to mention that you can disable `chrony` configuration if you already have time management (via chrony or ntp or something) available on the nodes.

For the sake of tracking, do you have a link to the PR? :)

**Comment by toabctl** [comment]
https://github.com/ceph/ceph-salt/commit/a87c5be4ae0c4fb14d2462afc5b53cbd43aa0423
