### ISSUE TITLE
Consider moving these sections to Troubleshooting Guide

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#360]
The following sections in teh Admin Guide have content that belongs to Troubleshooting (or other) Guide:

- https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#op-pg-stuck-states
- https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#op-osd-not-running

**Comment by asettle** [comment]
OSD section already existed in the Troubleshooting guide, but wasn't removed: https://susedoc.github.io/doc-ses/master/html/ses-troubleshooting/bp-troubleshooting-osds.html#bp-troubleshooting-not-running

I've removed it from the admin guide in the linked PR
