### ISSUE TITLE
[doc] 6.1  Install and Configure SUSE Linux Enterprise Server

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#362]
### Type of report
   - [ X ] bug
   - [ ] feature request

### Source Document
6.1  Install and Configure SUSE Linux Enterprise Server:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-os

### Summary
The listed SLE modules are not enough. We also need the `Containers Module 15 SP2` to have `podman` available.

**Comment by toabctl** [comment]
let's wait for input from @smithfarm on that.

**Comment by smithfarm** [comment]
I think this is invalid. We are shipping podman in SES7.

**Comment by toabctl** [comment]
Seems to be invalid. We want to have podman from the SES7 repos.
