### ISSUE TITLE
Document how to configure multiple networks (eg. cluster/public/gateway networks) with SES 7

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#363]
Similar to https://documentation.suse.com/ses/6/single-html/ses-deployment/#network-overview (for SES 6), we need documentation how different networks can be used for different parts of ceph.

**Comment by asettle** [comment]
@toabctl this is very new, and was co-written by David Byte. Who do you recommend to work alongside with to gather this kind of information for SES 7? Do we have a network specialist?

**Comment by asettle** [comment]
Emailed Martin Weiss and Cameron Seader to see if they know of any network specialist after speaking with @capri1989

**Comment by asettle** [comment]
1. Client traffic goes over the public network
2. Cluster network is optional
3. If cluster is not configured, traffic goes over the public network
4. Update diagram to be similar to the upstream version: https://docs.ceph.com/docs/master/rados/configuration/network-config-ref/#network-configuration-reference
5. You will see performance improvement with a cluster network for large cluster configurations
6. All traffic on the cluster network is OSD-to-OSD. Only nodes with OSDs on them need an address on the cluster network

Note: Gateways might have their own special client networks

**Comment by asettle** [comment]
Things wrong with the current doc:

1. Assumes VLAN is required to work, this is incorrect. You can create VLANs to isolate different types of traffic over a bond as it's better to bond the NICs and either just have one network, or - if they must have two - then use VLANs over the bond
