### ISSUE TITLE
[doc] 6.5.2.2.2  Matching Disk Devices

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#364]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.5.2.2.2  Matching Disk Devices:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#id-1.3.4.3.10.3.8.7

### Summary
I'm trying to select the devices (on the internal blueshark cluster) but it's difficult to find out which device models are actually available. I'm not sure if that is a software or a docs bug.
I first use `cephadm` to get the devices for the hosts (in our case only blueshark-6):
```
blueshark-1:~ # ceph orch device ls blueshark-6
HOST         PATH          TYPE   SIZE  DEVICE                                  AVAIL  REJECT REASONS
blueshark-6  /dev/nvme0n1  ssd    745G  INTEL SSDPEDMD800G4_CVFT5505000D800CGN  True
blueshark-6  /dev/nvme1n1  ssd    745G  INTEL SSDPEDMD800G4_CVFT60750012800CGN  True
blueshark-6  /dev/sda      ssd    223G  Micron_5200_MTFDDAK240TDN_18532045B0E6  True
blueshark-6  /dev/sdc      ssd    372G  INTEL_SSDSC2BA400G4_BTHV608300VE400NGN  True
blueshark-6  /dev/sdd      ssd    372G  INTEL_SSDSC2BA400G4_BTHV608204YX400NGN  True
blueshark-6  /dev/sde      ssd    372G  INTEL_SSDSC2BA400G4_BTHV608203EX400NGN  True
blueshark-6  /dev/sdf      ssd    372G  INTEL_SSDSC2BA400G4_BTHV608300WN400NGN  True
blueshark-6  /dev/sdg      ssd    372G  INTEL_SSDSC2BA400G4_BTHV608203ET400NGN  True
blueshark-6  /dev/sdh      ssd   29.8G  SATA_SSD_AF340757042400152847           True
blueshark-6  /dev/sdi      ssd   29.8G  SATA_SSD_B4500756122400100246           True
blueshark-6  /dev/sdb      ssd    372G  INTEL_SSDSC2BA400G4_BTHV6082036S400NGN  False  locked
```

So here we see the `DEVICE` column.
Now I use `ceph-volume` to get the `MODEL` for the disks:
```
blueshark-6:~ # cephadm ceph-volume inventory
INFO:cephadm:Using recent ceph image registry.suse.de/devel/storage/7.0/containers/ses/7/ceph/ceph:latest

[...]

Device Path               Size         rotates available Model name
/dev/nvme0n1              745.21 GB    False   True      INTEL SSDPEDMD800G4
/dev/nvme1n1              745.21 GB    False   True      INTEL SSDPEDMD800G4
/dev/sda                  223.57 GB    False   True      Micron_5200_MTFD
/dev/sdc                  372.61 GB    False   True      INTEL SSDSC2BA40
/dev/sdd                  372.61 GB    False   True      INTEL SSDSC2BA40
/dev/sde                  372.61 GB    False   True      INTEL SSDSC2BA40
/dev/sdf                  372.61 GB    False   True      INTEL SSDSC2BA40
/dev/sdg                  372.61 GB    False   True      INTEL SSDSC2BA40
/dev/sdh                  29.82 GB     False   True      SATA SSD
/dev/sdi                  29.82 GB     False   True      SATA SSD
/dev/sdb                  372.61 GB    False   False     INTEL SSDSC2BA40
```

There is the `MODEL` column, but it's different to the `DEVICE` column.

So the questions I have:
- what is the correct column to use for the DriveSpec ?
- why do `DEVICE` and `MODEL` differ?

I think there needs to be some docs how to get the different attributes for filtering devices.

**Comment by toabctl** [comment]
@sebastian-philipp @jan--f is the difference intended? Is that a doc bug? or a bug in cephadm or ceph-volume ?

**Comment by jschmid1** [comment]
The `DEVICE` and the `MODEL` columns are indeed two different things. see https://tracker.ceph.com/issues/45872

It seems that we should resurrect this issue and finally come to a conclusion here.

In the meanwhile we should clear up the difference in the docs, @asettle @toabctl ?

**Comment by asettle** [comment]
> In the meanwhile we should clear up the difference in the docs, @asettle @toabctl ?

As far as I can see @jschmid1, yes. What are the filters? Which are the incorrect filters in https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#id-1.3.4.3.10.3.8.7?

**Comment by jschmid1** [comment]
`DEVICE` is not covered by the drivegroup filters (and it probably won't).

To make this less awkward I went ahead and created the needed fix upstream.

See: https://github.com/ceph/ceph/pull/35946

When this is in, we can reference the `device ls` output in the docs.

**Comment by asettle** [comment]
@jschmid1 PR is now merged. Do we still want to reference `device ls`?

**Comment by asettle** [comment]
@tbazant do you still have a cluster up for correcting the relevant snippits?

**Comment by jschmid1** [comment]
@asettle yes, let's use the `device ls` (the most recent with ceph/ceph#35946 included) as a reference in the docs.
