### ISSUE TITLE
[doc] 6.5.2.3  Applying Cluster Specification

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#365]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
6.5.2.3  Applying Cluster Specification:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#cephadm-appply-cluster-specs

### Summary
After the command `ceph orch apply -i cluster.yml`, there should be some information about how the status of the cluster can be queried. Otherwise it's unclear how to check if everything is fine after applying the cluster.

**Comment by asettle** [comment]
Also just noticed that the ID name has a spelling mistake `cephadm-appply-cluster-specs`

**Comment by asettle** [comment]
@toabctl does `ceph orch status` not solve this issue? We do detail in this chapter: https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-day2
