### ISSUE TITLE
[doc] 6.5.3  Adding a New Node

### ISSUE THREAD

**Issue by ryg-** [SUSE/doc-ses#369]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.5.3  Adding a New Node:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-day2-addnode

### Summary

command  **ceph-salt deploy teuthida-2.ses.suse.de**  failed

### Steps To Reproduce
1 . setup cluster
2. add minion
3. ceph-salt config /ceph_cluster/minions add teuthida-2.ses.suse.de

### Expected Results
Node should be added

### Actual Results

> teuthida-9:~ # ceph-salt deploy teuthida-2.ses.suse.de
> Usage: ceph-salt [OPTIONS] COMMAND [ARGS]...
> Try "ceph-salt --help" for help.
> 
> Error: No such command "deploy".

**Comment by tbazant** [comment]
This was fixed by #371
