### ISSUE TITLE
Suspicious Admin Guide sections (mainly from DeepSea perspective)

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#370]
This issue lists sections which are obviously wrong and need to be either removed from the guide or updated to match SES7:

- [x] --- Admin Tasks ---
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ds-osd-recover
- manually deploy OSDs: ceph-volume to create devices, deploy OSDs from containers, we need a seprate JIRA issue here https://jira.suse.com/browse/SES-2110
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#moving-saltmaster
- deploy new node + restore salt-master + ceph-salt import  from exported backup
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#deepsea-rolling-updates
- underlying OS: ceph-salt update (https://github.com/ceph/ceph-salt/pull/303)
- containerized services: cephadm (https://docs.ceph.com/docs/master/cephadm/upgrade/)
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#sec-salt-cluster-reboot
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#admin-apparmor
- remove the whole section
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#deepsea-ceph-purge
- ceph-salt purge

- [x] --- Cluster Backup ---
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#sec-deployment-backup-deepsea
- remove
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#backup-config-files
- no openattic, no ceph.conf
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#restore-ceph
- remove step 4, 9-end

- [ ] --- Monitoring & Alerting ---
- [ ] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#monitoring-alerting
- talk to Patrick Seidensal @p-se 
- not as flexible as in SES7, config options must be passed to cephadm command, it re-generates their config files
- https://jira.suse.com/browse/SES-1194
- move '7.5 Troubleshooting Alerts' to Troubleshooting guide
- replace systemd units with `ceph orch demon restart osd.123`

- [x] --- RGW ---
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ogw-deploy
- YAML based import
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-rgw-operating
- dont use systemd unit files
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ogw-selfcert (is there a common SSL section?)
- remove DS specific stuff + https://confluence.suse.com/pages/viewpage.action?pageId=505119148 has most of the info
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ogw-ssl-simple, https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ogw-ssl-advanced
- not needed, ceph-salt takes care
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-rgw-sync-zones-configure (bullet 5)
- dont use systemd unit files but `ceph orch restart rgw.realm.zone`
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-rgw-fed-masterzone-startrgw
- dont use systemd unit files but `ceph orch restart rgw.realm.zone`
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-rgw-fed-secondzone-startrgw
- dont use systemd unit files but `ceph orch restart rgw.realm.zone`
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-rgw-failover-dr (bullets 3,4,7)
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-rgw-single-site-multi (bullet 7)
- move to the upgrade process
- [x] 12.13.3.3 Update the Ceph Configuration File
- remove the section
- [x] 6.5.3.4 Deploy Object Gateways
- steps 1-3 are optional, if realm, zone do not exist, they are created 

12.14 Load Balancing the Object Gateway Servers with HAProxy is going to be handled by orchestrator automatically

- [ ] --- NFS Ganesha ---
- [ ] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-nfsganesha-config
- Bug filed to ensure we have man page access #SES-2108
- [ ] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-nfsganesha-config-service-general
- @mgfritch  required here. The files are wrong, and the config files are actually stored in the middle layer. See: https://confluence.suse.com/display/SUSEEnterpriseStorage/nfs-ganesha
- [ ] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-nfsganesha-customrole-rgw-multiusers
- @mgfritch  to review. Config files are all different now. https://github.com/ceph/ceph/blob/master/src/pybind/mgr/cephadm/templates/services/nfs/ganesha.conf.j2
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-nfsganesha-customrole-rgw-cephfs
- Remove chapter completely.
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-nfsganesha-services
- Use the `ceph orch restart nfs.<service.id>` command instead

- [x] --- Ceph Point Releases ---
- [x] https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#id-1.4.9

**Comment by asettle** [comment]
Reviewing NFS Ganesha with @sebastian-philipp regarding #34

**Comment by asettle** [comment]
NFS Ganesha notes

- Chapter _16.2 Configuration_: Bug filed to ensure we have man page access #SES-2108 
- Chapter _16.2.1 Service Configuration_: Michael Fritch required here. The files are wrong, and the config files are actually stored in the middle layer.
- Chapter  _16.3.1 Different Object Gateway Users for NFS Ganesha_: Michael Fritch to review. Config files are all different now. 
- Chapter _16.3.2 Separating CephFS and Object Gateway FSAL_: Remove chapter completely.
- Chatper _16.4 Starting or Restarting NFS Ganesha_: Use the `ceph orch restart nfs.<service.id>` command instead

**Comment by asettle** [comment]
Also the Ganesha config files: https://github.com/ceph/ceph/blob/master/src/pybind/mgr/cephadm/templates/services/nfs/ganesha.conf.j2

**Comment by asettle** [comment]
Adding user-defined configs to the ganesha config rados objects: https://github.com/ceph/ceph/pull/36351/files

**Comment by asettle** [comment]
@tbazant here's the remaining deepsea references - but they're only in the admin guide :) 

admin_ds_backup.xml: <sect2 xml:id="sec-deployment-backup-deepsea">
admin_ds_backup.xml:  <title>Back Up &deepsea; Configuration</title>
admin_ds_backup.xml:   All files required by &deepsea; are stored in
admin_ds_backup.xml:     Manual changes to <filename>ceph.conf</filename> outside of &deepsea;.
admin_ds_backup.xml:     Manual changes to the &iscsi; configuration outside of &deepsea;.
admin_ds_backup.xml:   If you need to redeploy the &adm;, install the &deepsea; package on the new
admin_ds_backup.xml:   node and move the backed up data back into the directories. &deepsea; can
admin_ds_backup.xml:   &deepsea; again, make sure that all &salt; minions are correctly registered
admin_ds_backup.xml:     Install &salt; and &deepsea;. (See <link
admin_ds_backup.xml:     Restore the old, saved &deepsea; and &salt; configuration files.
admin_gui_dashboard.xml:  The &dashboard; is automatically enabled and configured with &deepsea;'s
admin_gui_dashboard.xml:     <xref linkend="deepsea-ceph-purge"/>.
admin_gui_dashboard.xml:       <xref linkend="deepsea-ceph-purge"/>.
admin_monitoring_alerting.xml:  In &productname; 6, &deepsea; no longer deploys a monitoring and alerting
admin_monitoring_alerting.xml:  (exporting daemons) are setup automatically by &deepsea;. &deepsea; also
admin_monitoring_alerting.xml:    &deepsea; does not ship any related defaults. You need to provide your own
admin_monitoring_alerting.xml:    &alertmanager; configuration managed by &deepsea;, add the following key to
admin_monitoring_alerting.xml:      the <option>monitoring:custom_alerts</option> key. &deepsea; Stage 2 or
admin_monitoring_alerting.xml:       file, &deepsea; will create the
admin_monitoring_alerting.xml:    &deepsea;. To do so you need to enable it in the Pillar under the
admin_monitoring_alerting.xml:    &deepsea; Stage 2 or the <command>salt
admin_ceph_gateway.xml:   The recommended way of deploying the &cogw; is via the &deepsea;
admin_ceph_gateway.xml:   running the required &deepsea; stages.
admin_ceph_gateway.xml:     Users can also be added via the &deepsea; file
admin_ceph_gateway.xml:    By default, &deepsea; expects the certificate file in
admin_ceph_gateway.xml:      Run &deepsea; stages 2, 3, and 4 to apply the changes:
admin_ceph_gateway.xml:      Run &deepsea; stage 3 and 4 to apply the changes:
admin_ceph_upgrade.xml:       &deepsea;'s default <filename>ceph.conf</filename> which is compiled
admin_ceph_upgrade.xml:       <title>Default &deepsea; Configuration</title>
admin_ceph_upgrade.xml:        configuration settings we ship as part of &deepsea; (stored in
admin_ceph_upgrade.xml:     using &deepsea;.
admin_ceph_upgrade.xml:     default, &aa; management was integrated into &deepsea; stage 0. The
admin_ceph_upgrade.xml:     before attempting to upgrade to &productname; &productnumber;. &deepsea;
admin_ceph_upgrade.xml:      <xref linkend="upgrade-prepare-repos" />) and run &deepsea; stage 0:
admin_ceph_upgrade.xml:      newer. Verify that the <package>deepsea</package> package is version
admin_ceph_upgrade.xml:  <title>Update <filename>policy.cfg</filename> and Deploy &dashboard; Using &deepsea;</title>
admin_ceph_upgrade.xml:     Update the &spillar; by running &deepsea; stage 1 and stage 2:
admin_ceph_upgrade.xml:     Finally, run through &deepsea; stages 0-4:
admin_ceph_upgrade.xml:      &deepsea; stage 3 may fail with an error similar to the following:
admin_ceph_upgrade.xml:      Then refresh the &spillar; and re-run &deepsea; stage.3:
admin_ceph_upgrade.xml:      After &deepsea; successfully finished stage.3, the &dashboard; will be
admin_ceph_upgrade.xml:   In &productname; &prevproductnumber;, &deepsea; offered so called 'profiles'
admin_ceph_upgrade.xml:    file, and run &deepsea; stage 2 to refresh the &spillar;.
admin_nfsganesha.xml:   file are overwritten when &deepsea; stage 4 is executed. To persistently
admin_nfsganesha.xml:    &deepsea; stage 4 is executed. To persistently change the settings, edit
admin_nfsganesha.xml:        &deepsea;, it is not necessary to change this value.
admin_nfsganesha.xml:     &deepsea; already takes care of correctly generating this URL, and you do
admin_nfsganesha.xml:    &deepsea; already provides example configuration files.
admin_nfsganesha.xml:      created for each role. The original template of &deepsea; is a good
admin_nfsganesha.xml:      Execute &deepsea; Stages 0 to 4.
admin_nfsganesha.xml:      created for each role. The original template of &deepsea; is a good
admin_nfsganesha.xml:      Execute &deepsea; Stages 0 to 4.
admin_saltcluster.xml:     Run &deepsea; stages 1 to 5:
admin_saltcluster.xml:     Run &deepsea; stage 0:
admin_saltcluster.xml:   &smaster; and &deepsea; files. Use your favorite synchronization tool for
admin_saltcluster.xml:     Verify that the <package>deepsea</package> package is installed and
admin_saltcluster.xml:<screen>&prompt.smaster;zypper install deepsea</screen>
admin_saltcluster.xml:     Now you can run &deepsea; stages from the new &adm;. Refer to DEAD LINK
admin_saltcluster.xml: <sect1 xml:id="deepsea-rolling-updates">
admin_saltcluster.xml:      Update the <package>deepsea</package>, <package>salt-master</package>,
admin_saltcluster.xml:   &deepsea; provides three states for &aa; profiles: 'enforce', 'complain',
admin_saltcluster.xml:salt -I "deepsea_minions:*" state.apply ceph.apparmor.default-<replaceable>STATE</replaceable>
admin_saltcluster.xml:&prompt.smaster;salt -I "deepsea_minions:*" state.apply ceph.apparmor.default-enforce
admin_saltcluster.xml:&prompt.smaster;salt -I "deepsea_minions:*" state.apply ceph.apparmor.default-complain
admin_saltcluster.xml:&prompt.smaster;salt -I "deepsea_minions:*" state.apply ceph.apparmor.default-disable
admin_saltcluster.xml:    not, and starts and enables the related &systemd; service. &deepsea; will
admin_saltcluster.xml:    therefore runs without &deepsea; profiles.
admin_saltcluster.xml: <sect1 xml:id="deepsea-ceph-purge">
admin_saltcluster.xml:   cluster is reverted back to the state at the end of &deepsea; stage 1. You
