### ISSUE TITLE
[doc] 6.3.2.10  Configure Container Registry -> we must not recommend "insecure=true"

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#374]
### Type of report
   - [ x] bug
   - [ ] feature request

### Source Document
6.3.2.10  Configure Container Registry:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-configure-registry

### Summary
It is possible to setup proper security and we should never advice to use "insecure".

### Notes
The only thing that is required is to add the public key (chain) of the signing certificate authority to /etc/pki/trust/anchors on all servers and execute "update-ca-certificates".

**Comment by asettle** [comment]
@sebastian-philipp could you please confirm? :)
