### ISSUE TITLE
[doc] 6.5.3.3  Deploy Metadata Servers (missing command)

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#380]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.5.3.3  Deploy Metadata Servers:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-day2-service-mds

### Summary

After applying the service spec, one must issue the following command:

```
ceph fs volume create <volume_name>
```

**Comment by tbazant** [comment]
fixed by https://github.com/SUSE/doc-ses/commit/6ee7c987c63a8a224c99a1f427aace1bf559d5a5
