### ISSUE TITLE
[doc] 6.3.2.10  Configure Container Registry - link to SLES containers documentation

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#383]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.3.2.10  Configure Container Registry:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-configure-registry

### Summary
The way how to setup an on-premise registry is part of the CaaSP and of the Containers documentation for SLES.  We should also not point to an upstream image "registry" and use our SUSE one instead.

### Notes
See above - I would recommend to link this to the other SUSE documentations.

**Comment by tbazant** [comment]
A link to CaaSP docs was already added - see https://github.com/SUSE/doc-ses/blob/master/xml/deploy_cephadm.xml#L635

by "registry" you mean the `podman`'s `-name` option? what do you suggest?

**Comment by Martin-Weiss** [comment]
> 
> by "registry" you mean the `podman`'s `-name` option? what do you suggest?

https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-registry-installation.html

**Comment by tbazant** [comment]
i've added a link to the suggested SLE doc, review it and add what is needed, it's unclear to me what to do with the "registry"
@Martin-Weiss see https://github.com/SUSE/doc-ses/pull/417
