### ISSUE TITLE
[doc] 6.5.4.3  Deploy Metadata Servers - no cephfs pools created?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#385]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.5.4.3  Deploy Metadata Servers:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-day2-service-mds

### Summary
cephfs pools not created when MDS are created

### Steps To Reproduce
create and apply:

service_type: mds
service_id: cephfs
placement:
 hosts:
  - ses7-01
  - ses7-02
  - ses7-03

### Expected Results
Would have expected that the cephfs is getting created and we get the standard pools for data and meta-data.

### Actual Results
MDS were created but no new pools:

```
ses7-admin:~ # ceph -s
  cluster:
    id:     40c6ac7e-b48c-11ea-ac77-52540020a5c7
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum ses7-01,ses7-02,ses7-03 (age 16m)
    mgr: ses7-01.jixzru(active, since 78m), standbys: ses7-02.pvegop, ses7-03.vabfxk
    mds:  3 up:standby
    osd: 12 osds: 12 up (since 49m), 12 in (since 49m)

  data:
    pools:   1 pools, 1 pgs
    objects: 0 objects, 0 B
    usage:   12 GiB used, 228 GiB / 240 GiB avail
    pgs:     1 active+clean

```
```
ses7-admin:~ # rados lspools
device_health_metrics

```

### Notes
Why are no cephfs pools created?

**Comment by tbazant** [comment]
fixed by https://github.com/SUSE/doc-ses/commit/6ee7c987c63a8a224c99a1f427aace1bf559d5a5 - have a look there please
