### ISSUE TITLE
Update link to CaaSP air-gapped scenario once version 5 is released

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#389]
**Link To Section**
https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-registry

**Comment by asettle** [comment]
Fixed.

**Comment by tbazant** [comment]
CaaSP 5 not yet released, still a valid issue

**Comment by asettle** [comment]
CaaSP 5 won't be released, only 4.5 is released. Linked to the airgapped 4.5 doc. @tbazant can we close now?

**Comment by asettle** [comment]
Link has been updated

```To avoid re-syncing the local registry when new updated containers appear, you can configure a registry cache. Find more information about containers and air-gapped scenarios in https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-airgap/```
