### ISSUE TITLE
[doc] 6.5.3.2  Deploy Ceph OSDs

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-ses#391]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.5.3.2  Deploy Ceph OSDs:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-day2-service-osd

### Summary
After running `ceph orch apply -i MON.yml`, the command should have updated `ceph.conf` on node1 (admin node) to point to the new MONs IPs, but it did not. This resulted in the `ceph` command being unable to query the cluster. 

### Steps To Reproduce
See the steps in the linked doc.

### Expected Results
Running `ceph orch apply -i FILE.yml` results in an updated `ceph.conf`. 

### Notes
Add a general troubleshooting section to the guide, such as "Fixing ceph.conf that refers wrong MONs IP addresses". In theory, this should be fixed by: https://github.com/ceph/ceph/pull/35576

**Comment by sebastian-philipp** [comment]
hm. I hope real users will not run into this issue.

**Comment by asettle** [comment]
> hm. I hope real users will not run into this issue.

You'd want to hope so. But either way, it's worth documenting. If I've run into it and @tbazant had to help me with it, it's highly likely someone could have a similar config.

**Comment by sebastian-philipp** [comment]
btw, `ceph orch apply -i NAME` is a bit incorrect.  I mean, `-i` takes a file argument. not a name.

**Comment by asettle** [comment]
> btw, `ceph orch apply -i NAME` is a bit incorrect. I mean, `-i` takes a file argument. not a name.

Correct. I just quickly typed this when I was running through the deploy. It is meant to be NAME.yml. If need be, I'll update it.
