### ISSUE TITLE
[doc] 4  Troubleshooting cephadm: restarting a daemon with a specific container image

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/doc-ses#399]
### Type of report
   - [ ] bug
   - [x] feature request

### Source Document
4  Troubleshooting <code class="systemitem">cephadm</code>:

https://susedoc.github.io/doc-ses/master/single-html/ses-troubleshooting/#bp-troubleshooting-cephadm

### Summary

run this:

```
ceph config set <config-entity> container_image <container_image>
```

eg.

```
ceph config set client.iscsi container_image <container_image>
```

where ` <config-entity>` is like

```python
if daemon_type in ['rgw', 'rbd-mirror', 'nfs', 'crash', 'iscsi']:
    return 'client.' + daemon_name
if daemon_type in ['mon', 'osd', 'mds', 'mgr', 'client']:
    return daemon_name
```

And then run this:

```
ceph orch redeploy <daemon_name>
```

**Comment by asettle** [comment]
@sebastian-philipp I need more context for this, please. I don't know what the issue is, are you filing this against content that already exists? Or are you suggesting a new section?

**Comment by sebastian-philipp** [comment]
ok the context is:

### How do we distribute PTFs? 

1. user complains that something is broken. 
1. turns out, this is a bug that needs a temporary fix. 
1. we'll then build a container image containing a specific fix. 
1. the user then needs to be able to deploy the container to a specific daemon in order to test the fix. 

Turns out, this is already possible by telling cephadm to `redeploy` a specific daemon with a specific `container_image`. Which means we have to first change the `container_image` config entry for this specific daemon and then restart the daemon. 

Does this help?

**Comment by sebastian-philipp** [comment]
with ceph/ceph#36426, this will get simplified to 

```
ceph orch daemon redeploy <daemon> --image=myregistry.com/myimage:mytag
```
