### ISSUE TITLE
[doc] Missing step during recovering a reinstalled OSD node

### ISSUE THREAD

**Issue by cupracer** [SUSE/doc-ses#400]
**Link To Section**
https://documentation.suse.com/ses/6/html/ses-all/storage-salt-cluster.html#ds-osd-recover

**Summary**
A SUSE consultant used this procedure on a customer cluster, but failed due to a missing "ceph-volume lvm activate --all".

**Steps To Reproduce**
Follow steps 1-3 of chapter "2.9 Recovering a Reinstalled OSD Node"

**Expected Results**
It is expected that step 3 successfully runs DeepSea stages 1 to 5.

**Actual Results**
DeepSea stage 3 does not finish successfully.

**Notes**
DeepSea stage 3 does not finish successfully, because it expects that the OSD processes on the server are already running. But the OSDs on the server do not start because they cannot be mounted (in /var/lib/ceph/osd). This mounting issue was fixed by executing "ceph-volume lvm activate --all" and we believe that this required step is missing in the documentation.

**Comment by asettle** [comment]
@swiftgist would you mind taking a look at this one, please? :)

**Comment by swiftgist** [comment]
I am not aware of a related bug about this incident in particular.  For SES6, Stage 3 does call `salt-run disks.deploy` which then calls `ceph-volume` with a constructed set of arguments.  If there is a difference between calling `ceph-volume lvm activate --all` and calling `ceph-volume` for each individual OSD, then that is something that needs to be reported.

The note says that the OSD could not be mounted, but implies that the activation command fixed it.  I would need to see the output of `salt-run disks.c_v_commands` and have those commands run under the same initial conditions where the OSDs were not activated.

**Comment by asettle** [comment]
@cupracer could you take a look at the comment from @swiftgist and see if this applies? Looks like we need the output form `salt-run disks.c_v_commands`

**Comment by asettle** [comment]
@cupracer is reaching out to the external consultant to find the required information.

**Comment by cupracer** [comment]
Unfortunately the affected system is not usable for testing anymore since the re-installation was finished meanwhile and the system is back to production mode. Our consultant does not have any additional logs or console outputs available to investigate, so we'd need to wait for another occurrence of a situation which requires a recovering of an existing OSD node.

**Comment by asettle** [comment]
Thanks for letting me know, @cupracer - I'm going to close this out for now, but we'll be able to trace it if the customer experiences this issue again. Thanks for reaching out.
