### ISSUE TITLE
[doc] Part&nbsp;III  Upgrading from Previous Releases - wrong sentence about version 6

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#401]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
Part&nbsp;III  Upgrading from Previous Releases :

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#ses-upgrade

### Summary
This sentence is wrong: "Note that version 6 is basically 5 with all latest patches applied. "

-> seems to be a search/replace bug ;-).

### Notes
Just removing this sentence should be enough to fix this issue.

**Comment by Martin-Weiss** [comment]
this sentence is at least twice in the document!

**Comment by asettle** [comment]
@Martin-Weiss the whole document has not been finalised, a lot of these are entities that will be resolved when the publishing process goes through. Thanks for reading through and noticing, however I will be closing :)

**Comment by Martin-Weiss** [comment]
When we release a public document and ask for feedback - we have to implement and fix it!

Please add a disclaimer if the document is not ready for consumption!

Thanks
Martin

Am 30.06.2020 um 17:49 schrieb Alexandra Settle <notifications@github.com>:

﻿

@Martin-Weiss<https://github.com/Martin-Weiss> the whole document has not been finalised, a lot of these are entities that will be resolved when the publishing process goes through. Thanks for reading through and noticing, however I will be closing :)

**Comment by ajaeger** [comment]
Martin, the page has a pop up saying "This is a draft document that was built and uploaded automatically. It may document beta software and be incomplete or even incorrect. Use this document at your own risk." - with a button "I understand this is a draft".

**Comment by Martin-Weiss** [comment]
Yes - but there are feedback buttons - so if I provide feedback as requested and the feedback is rejected this is not the best for customers 😉

Martin
________________________________
Von: Andreas Jaeger <notifications@github.com>
Gesendet: Mittwoch, 1. Juli 2020 08:57
An: SUSE/doc-ses <doc-ses@noreply.github.com>
Cc: Martin Weiss <Martin.Weiss@suse.com>; Mention <mention@noreply.github.com>
Betreff: Re: [SUSE/doc-ses] [doc] Part&nbsp;III Upgrading from Previous Releases - wrong sentence about version 6 (#401)


Martin, the page has a pop up saying "This is a draft document that was built and uploaded automatically. It may document beta software and be incomplete or even incorrect. Use this document at your own risk." - with a button "I understand this is a draft".
