### ISSUE TITLE
60 or 64 GB for RocksDB?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#416]
**Link To Section**
Please provide a link to the section or chapter you are reporting this bug for.

**Summary**
In the deployment guide we write 64 GB for RocksDB: https://susedoc.github.io/doc-ses/ses6/single-html/ses-deployment/#rec-waldb-size

In the tuning guide we write 60 GB for RocksDB: https://github.com/SUSE/doc-ses/issues/new/choose?title=%5Bdoc%5D%204.3.1%20%20RocksDB%20and%20WAL&body=4.3.1%20%20RocksDB%20and%20WAL%3A%0A%0Ahttps%3A%2F%2Fdocumentation.suse.com%2Fses%2F6%2Fsingle-html%2Fses-tuning%2F%23id-1.5.3.2.8.2&assignee=asettle&labels=bug%2Cquestion%2Cfeature%20request

**Expected Results**
See above - both should be identical and I assume this should be 64 GB in both cases!

**Comment by asettle** [comment]
@Martin-Weiss are you referring to this section? You second link is for GitHub issues. https://susedoc.github.io/doc-ses/ses6/single-html/ses-tuning/#id-1.5.3.2.8.2.5

**Comment by Martin-Weiss** [comment]
Yes - one guide says 60 GB and the the other one 64 GB - so I have 64 GB in mind - but now that we have two different messages we need to find the right one and correct one or the other

**Comment by asettle** [comment]
@Martin-Weiss I believe this is because in the case of the deployment guide, the 64 GB assumes the 60 GB and then "We recommend reserving 4 GB for the WAL device." The Tuning Guide does not make this same assumption. I am just clarifying right now. If this is the correct assumption, I'll add a note to the Tuning Guide that states that we recommend 64 in total, including the 4 GB for the WAL device :)

**Comment by Martin-Weiss** [comment]
We do NOT use a separate WAL in case we use the two device setup. But I believe rocksDB needs 60 GB and we add 4 GB for the WAL in case WAL is not separated.

**Comment by asettle** [comment]
> We do NOT use a separate WAL in case we use the two device setup. But I believe rocksDB needs 60 GB and we add 4 GB for the WAL in case WAL is not separated.

Exactly what I said. Nowhere in the docs does it imply a separate WAL, and my addition would not imply this either.

**Comment by asettle** [comment]
Lars has confirmed this is the case. PR linked.
