### ISSUE TITLE
[doc] 8.8.2  Node Upgrade Using the SUSE Distribution Migration System

### ISSUE THREAD

**Issue by soothill** [SUSE/doc-ses#419]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
8.8.2  Node Upgrade Using the SUSE Distribution Migration System:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#upgrade-one-node-auto

### Summary
Point 1 says this "ceph fs get cephfs"
Point 2 says "ceph fs set FS_NAME max_mds 1"

### Expected Results
Point 1 should be the same as point 2 with FS_NAME instead of cephfs.

**Comment by tbazant** [comment]
@soothill The referenced section does not include the described points at all. Can you double-check that it belongs together?
NOTE: the upgrade chapter for SES7 has not been touched yet, it's in fact SES6 version with changed version numbers only, it's gonna be totally rewritten.

**Comment by asettle** [comment]
Moving content to confluence. Thanks.
