### ISSUE TITLE
[doc] 6.5.3.5  Deploy NFS Ganesha

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#423]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.5.3.5  Deploy NFS Ganesha:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-day2-service-nfs

### Summary

Users will be expected to deploy NFS Ganesha using the new `mgr/nfs` CLI. That means the current content of this section can be completely replaced by new content explaining how to deploy an NFS Ganesha cluster using the new CLI.

Source: https://docs.ceph.com/docs/octopus/cephfs/fs-nfs-exports/

Steps for NFS-backed-by-CephFS:

1. create a CephFS using `ceph fs volume create`. Take note of the volume (CephFS) name.
2. `ceph fs status` - verify that the volume (CephFS) name is listed
3. `ceph nfs cluster create cephfs <cluster_id> <placement>` where `<cluster_id>` is an arbitrary string that will be used to identify this NFS Ganesha cluster and `<placement>` is an Orchestrator Placement String (link to separate doc section) how many NFS Ganesha daemons will be in the cluster and which nodes they will run on
4. `ceph orch ls` and `ceph orch ps` should now show NFS daemons running in the cluster
5. `ceph nfs export create cephfs <vol_id> <cluster_id> <pseudo_root_path>` where `<vol_id>` is the volume (CephFS) name from step 1, `<cluster_id>` is the NFS Ganesha cluster ID from step 3, and `<pseudo_root_path>` is the absolute path under which this export will be available in the file system.
6. `ceph nfs export ls <cluster_id> --detailed` to review details of the export
7. `mount -t nfs4 <nfs_node>:<pseudo_root_path> <mount_point>` as root to mount the export

**Comment by smithfarm** [comment]
Note: `ceph nfs cluster create` currently only supports CephFS, but RGW support will be added at some point in the (relatively near?) future.

Note: `ceph nfs cluster create` only supports Orchestrator Placement Strings, not Orchestrator Placement YAML files. But, here again, the support for YAML Files is supposed to be added soon-ish.

**Comment by asettle** [comment]
Note to self, overall issue tracking here: https://github.com/SUSE/doc-ses/issues/354

**Comment by smithfarm** [comment]
Note to @asettle and @supriti - if you were thinking about testing this with `sesdev`, use `sesdev create octopus` instead of `sesdev create ses7`. The reason for this is:

The SES7 container contains nfs-ganesha version 3.2. Since the mgr/nfs CLI requires nfs-ganesha version 3.3 or above, it will not work in a ses7 cluster. It works in an "octopus" cluster because the "filesystems:ceph:octopus" container contains nfs-ganesha version 4.

**Comment by asettle** [comment]
Having spoken with Michael Fritch and @sebastian-philipp - I've been informed that using the mgr/nfs CLI is going to be revisited as it will not be ready in the SES 7 timeframe.

**Comment by asettle** [comment]
Closing due to NFS Ganesha no longer being backed by `ceph fs`. 

New NFS Ganesha issue: https://github.com/SUSE/doc-ses/issues/477
