### ISSUE TITLE
Document container registry setup

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-ses#427]
Document what container registry is and how to configure it with ceph-salt

"Under section 6.2.3.7, we reference setting the container image, but not configuring the registry.

Since I specifically needed the insecure option, which may be necessary for customers using a local registry, I did run
 

# ceph-salt config /containers/registries add location=registry.suse.de:5000
 insecure=true
 
 to connect to our registry. If we think this will always be an optional step, then we should at least add 

# ceph-salt config /containers/registries help
for seeing an example of configuring the /etc/containers/registries.conf.

**Comment by tbazant** [comment]
it's already included in the meanwhile, see https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-registry
