### ISSUE TITLE
Cross-stack not supported in SES 7

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-ses#429]
We should explicitly document that this cross-stack conversion/upgrade from non-kubernetes to Kubernetes-based is not (yet) supported in SES7.

**Comment by sknorr** [comment]
Hey -- note that I will need a draft for this, ideally before going on vacation for three weeks at the end of the week. :)

**Comment by asettle** [comment]
@sknorr the release isn't until October 19, does that not give enough time after your return or what is your process here? :)

**Comment by asettle** [comment]
Documented: https://confluence.suse.com/display/SUSEEnterpriseStorage/SES+7+Release+Notes
