### ISSUE TITLE
SES7 RGW Multisite documentation should mention that interoperability with SES5.5 is not supported

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-ses#431]
Since SES5.5 is based on Luminous and SES7 on Octopus, and since RGW Multisite does not support a Luminous-Octopus combination, the SES7 documention should mention that limitation.

**Comment by asettle** [comment]
@smithfarm this should definitely be part of the release notes, but I think we can probably also include a small note in https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-rgw-fed

**Comment by sknorr** [comment]
Hey -- note that I will need a draft for this, ideally before going on vacation for three weeks at the end of the week. :)

**Comment by asettle** [comment]
@sknorr the release isn't until October 19, does that not give enough time after your return or what is your process here? :)

**Comment by smithfarm** [comment]
@asettle Can you divulge your source for the statement "RGW Multisite does not support a Luminous-Octopus combination"?

**Comment by asettle** [comment]
> @asettle Can you divulge your source for the statement "RGW Multisite does not support a Luminous-Octopus combination"?

Since I thought it was you (having tagged you earlier) I have no idea now. I didn't file any reports like this without having spoken to someone, it may have been Sebastian. I'll check through some of my conversations/emails to see what's up. This could have been verbal.

**Comment by asettle** [comment]
> @asettle Can you divulge your source for the statement "RGW Multisite does not support a Luminous-Octopus combination"?

It's you: https://jira.suse.com/browse/SES-1050

**Comment by smithfarm** [comment]
**Abhi 12:40 PM**
Lars Marowsky-Brée what is our multisite support policy N-2 -> N+2 compatibility correct?
**Lars Marowsky-Brée 12:51 PM**
Abhi I think that's upstream, in terms of major SES versions I think it's N-1/N

**Comment by smithfarm** [comment]
So, I'm not alone in assuming that SES5 <-> SES7 Multsite replication is not supported. But I don't know if this is explicitly stated, or indeed, where in our documentation such an explicit support statement belongs.

**Comment by asettle** [comment]
> So, I'm not alone in assuming that SES5 <-> SES7 Multsite replication is not supported. But I don't know if this is explicitly stated, or indeed, where in our documentation such an explicit support statement belongs.

This is a release note statement only.

**Comment by smithfarm** [comment]
> This is a release note statement only.

Hm, well, in that case, do we have a place where we track recurring release note statements? Because this one ("our multisite support policy is N-1/N") will need to be added to every product release.

**Comment by asettle** [comment]
> > This is a release note statement only.
> 
> Hm, well, in that case, do we have a place where we track recurring release note statements? Because this one ("our multisite support policy is N-1/N") will need to be added to every product release.

This issue has already been tagged with "release note" label and added to the confluence page. This is sufficient. 

@sknorr is it possible to add the statement "our multisite support policy is N-1/N" to the SES 6 and SES 5 release notes? Thank you.

**Comment by smithfarm** [comment]
> This issue has already been tagged with "release note" label and added to the confluence page. This is sufficient.

Sorry, but can you clarify how that will ensure it gets into the SES8, 9, 10 . . .  release notes?

**Comment by asettle** [comment]
> > This issue has already been tagged with "release note" label and added to the confluence page. This is sufficient.
> 
> Sorry, but can you clarify how that will ensure it gets into the SES8, 9, 10 . . . release notes?

Once this issue has been addressed for SES 7, we can ensure there is a permanent note that lives within the release notes that is not removed each release. As part of the template, if you will.

**Comment by smithfarm** [comment]
@asettle Got it. Thanks!

@l-mb Can you just confirm that we do support only one product release back for RGW Multisite (now and in the future)? @theanalyst tells me there's no technical reason why N-2 <-> N would be expected to not work.

**Comment by smithfarm** [comment]
(For myself, I can say that I looked at upstream's `rgw/multiwsite` teuthology suite and found no indication that it tests anything other than N <-> N)

**Comment by theanalyst** [comment]
though N-2 -> N will work for skip releases we'd end up with an unmaintained N-3, and for the sake of sanity version N would support N-1 and N+1 clusters would be the most compatible testing matrix.

**Comment by smithfarm** [comment]
ok, "support N-1 and N+1" means:

* SES6 RGW Multisite can replicate to SES5 RGW Multisite, and also to SES7 Multisite
* SES7 Multisite can replicate to SES6 and to SES8

This is the same as I meant when I wrote `N-(N-1)`.

**Comment by asettle** [comment]
This has been documented: https://confluence.suse.com/display/SUSEEnterpriseStorage/SES+7+Release+Notes#SES7ReleaseNotes-KnownIssues

Will need to note to @sknorr that this interoperability message needs to stay in place for SES 8
