### ISSUE TITLE
[doc] 19.3.1.1  Additional Notes

### ISSUE THREAD

**Issue by theanalyst** [SUSE/doc-ses#437]
### Type of report
   - [ x ] bug
   - [ ] feature request

### Source Document
19.3.1.1  Additional Notes:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#sec-ceph-rgw-configuration-notes

### Summary

Explain the reasoning behind `rgw dns name`. Its primary use is to allow clients using vhost style buckets to be used. 
vhost style access refers to `<bucketname>.<s3-endpoint>/<object-path>` in comparison to a `<s3-endpoint>/<bucket>/<object>`
This also means that the site must have the dns configured correctly to correctly reroute dns requests of the <bucketname>.<s3-endpoint> style to RGW correctly. This `s3-endpoint` must correspond to the `rgw dns name` configurable

**Comment by asettle** [comment]
@theanalyst for the point of a short and sharp definition in this doc, I'm only going to add "Allows clients to use vhost style buckets to be used." :) thanks for the context!
