### ISSUE TITLE
Drop ceph.conf and document configuration database

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#458]
**Link To Section**
All over the manual

**Summary**
Instead of writing Ceph configuration to /etc/ceph/ceph.conf, configure related keys in the configuration database.

**Notes**
Update all occurences that mention modifying ceph.conf to the conf DB counterpart

- [x] Rewrite most of the section about database configuration
- [ ] Replace all occurencies of `ceph.conf` with the config DB way

**Comment by tbazant** [comment]
In case someone really needs to make changes in the physical `ceph.conf` (maybe he uses a client that does not support reading configs from ceph config ... , he needs call `ceph config set mgr mgr/cephadm/manage_etc_ceph_ceph_conf false` and then he is in charge of maintaining the `ceph.conf` in the whole cluster

**Comment by sebastian-philipp** [comment]
* https://docs.ceph.com/docs/master/rados/configuration/ceph-conf/#monitor-configuration-database
* https://docs.ceph.com/docs/master/cephadm/operations/#etc-ceph-ceph-conf

**Comment by denisok** [comment]
not everything could be configured from configuration DB, so we still need it for small set of configuration parameters, like BlueFS, Bluestore and networking. Also for some troubleshooting, like debug in case of connection to mon is missed.

https://jira.suse.com/browse/SES-2134?focusedCommentId=1016984&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1016984
https://jira.suse.com/browse/SES-2134?focusedCommentId=1017801&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1017801

https://jira.suse.com/browse/SES-2150

**Comment by asettle** [comment]
There are a few use cases where we still need the `ceph.conf`:
1. legacy clients that don#t support fetching config options from the MON
2. Troubleshooting specific problems
3. config options should should be generated automatically,but aren't. (I.e. bugs in the automation)
https://stackoverflow.com/questions/61763230/configure-a-cluster-network-with-cephadm

**Comment by asettle** [comment]
This is complete as of now.
