### ISSUE TITLE
[doc] 2.4.3  Recommended Size for the BlueStore's WAL and DB Device

### ISSUE THREAD

**Issue by lezare** [SUSE/doc-ses#463]
### Type of report
   - [ ] bug
   - [x] feature request

### Source Document
2.4.3  Recommended Size for the BlueStore's WAL and DB Device:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#rec-waldb-size

### Summary
We state there in general a 64GB size for the DB, however, for larger deployments this value is really too conservative.

### Notes
We have seen a number of customers running into spillover and then performance issues over the last couple of months due to too small DB sizes. The problem with this is, it is not always possible to simply resize the DBs since the actual hardware simply does not allow for that. The optimal DB size for larger customers can sometimes be 7x!! the general recommended size of 64GB.

Thus, should we not maybe at least add a note to this part emphasizing that the size takes special consideration and that the general recommendation for larger deployments likely is / can be insufficient / should be more?

**Comment by asettle** [comment]
So, @lezare I spoke to Igor about this issue. 

```64G is currently the best fit for small/average customers. Due to current BlueFS/RocksDB design the next number we can recommend is 250+GB which seems to be pretty high (and expensive) to be a recommended value. We might though have a note recommending that large DB volume for high-load deployments especially ones with massive RGW/CephFS usage. A recommendation to reserve some capacity (slots) to be able to install more HW for adding DB space if needed looks reasonable as well. ```
