### ISSUE TITLE
Failure to recover a reinstalled OSD node

### ISSUE THREAD

**Issue by stwel** [SUSE/doc-ses#468]
**Link To Section**
https://documentation.suse.com/ses/6/html/ses-all/storage-salt-cluster.html#ds-osd-recover

**Summary**
The procedure for recovering a reinstalled OSD node described in the document fails in DeepSea stage 3.
'False' is returned from the reinstalled node during waiting for OSD processes.
This is because the OSD processes are not active on the reinstalled node.
The OSD processes are activated by doing the following steps before running DeepSea stages:

- Create the /etc/ceph/ceph.conf file on the reinstalled node (We copied the ceph.conf file from one of the other nodes).
- Run the command `ceph-volume lvm activate –all` on the reinstalled node.

Please modify the document to encourage readers to perform the above steps between steps 2 and 3 of the document.

**Steps To Reproduce**

1. As written in step 1 of the "2.9 Recovering a Reinstalled OSD Node",
   reinstall SLES15 SP1 on one of OSD nodes. Install the salt-minion 
   packages on the node, delete the old Salt minion’s key, and 
   register the new Salt minion's key with the Salt master.

2. As written in step 2 of the "2.9 Recovering a Reinstalled OSD Node",
   run the following commands:
   ```
   root@master # salt 'osd_node' state.apply ceph.sync
   root@master # salt 'osd_node' state.apply ceph.packages.common
   root@master # salt 'osd_node' state.apply ceph.mines
   root@master # salt 'osd_node' state.apply ceph.updates
   ```

3. As written in step 3 of the "2.9 Recovering a Reinstalled OSD Node",
   run DeepSea stages 1 to 5.
   The error occurs at DeepSea stage 3.

The packages for SES6 are updated during installation, so we use the latest ones.
We hit the issue with the following version of packages.

  Ceph version : 14.2.9.969+g9917342dc8-3.38.1
  DeepSea version : 0.9.30+git.0.e2dea4531-3.18.1

The current document may work with the old packages for SES6, but may not work with latest ones.

**Expected Results**
DeepSea stage 3 is successfully completed.

**Actual Results**
DeepSea stage 3 fails to run.
'False' is returned from the reinstalled node during waiting for OSD processes.
Attached is the standard output when the error occurs during DeepSea stage 3.
[ses_stdout_err_recovering-reinstalled-node.txt](https://github.com/SUSE/doc-ses/files/5088626/ses_stdout_err_recovering-reinstalled-node.txt)

**Notes**
None

**Comment by asettle** [comment]
@swiftgist interesting. Do you know anything about any changes that would impact this in the new DeepSea packages?

**Comment by swiftgist** [comment]
Isn't this related to the one where we added the two commands just recently to the docs?

**Comment by asettle** [comment]
> Isn't this related to the one where we added the two commands just recently to the docs?

Are you referring to? https://github.com/SUSE/doc-ses/pull/413/files

**Comment by asettle** [comment]
Hi @stwel - we have indeed investigated this issue in the past related to an internal Bugzilla report. After investigation, we have added a note to the published documentation here: https://documentation.suse.com/ses/6/single-html/ses-deployment/#upgrade-ntp

Could you please test this action, and let me know if you have any further concerns.

Thank you,

Alex

**Comment by asettle** [comment]
@stwel thank you for your report. Your update has been applied and is available online here: https://susedoc.github.io/doc-ses/ses6/single-html/ses-admin/#ds-osd-recover
This change will be published to _documentation.suse.com_ shortly. 

Please review and let me know if you have any questions or concerns.

Alex

**Comment by stwel** [comment]
Thank you for your update.
This modification to the document is great. I do not have any other concerns.
