### ISSUE TITLE
6.3.2.6 Document /ssh/user

### ISSUE THREAD

**Issue by ricardoasmarques** [SUSE/doc-ses#479]
**Link To Section**
https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-ssh

**Summary**
By default, `ceph-salt` user will be created.
It's possible to set a different SSH user by running `ceph-salt config /ssh/user set <user>`

**Notes**
Note that `/ssh/user` node should be included in the output of all `ceph-salt config ls` calls.

**Comment by smithfarm** [comment]
> Note that /ssh/user node should be included in the output of all ceph-salt config ls calls.

In other words, the following text in the document:

```
master:~ # ceph-salt config /ssh ls
o- ssh .................................................................................................... [Key Pair set]
  o- private_key ....................................................... [b3:0d:69:06:63:27:3b:a8:11:23:e5:ce:c0:0c:29:56]
  o- public_key ........................................................ [b3:0d:69:06:63:27:3b:a8:11:23:e5:ce:c0:0c:29:56]
```

should be changed to:

```
master:~ # ceph-salt config /ssh ls
o- ssh .................................................................................................... [Key Pair set]
  o- private_key ....................................................... [b3:0d:69:06:63:27:3b:a8:11:23:e5:ce:c0:0c:29:56]
  o- public_key ........................................................ [b3:0d:69:06:63:27:3b:a8:11:23:e5:ce:c0:0c:29:56]
  o- user .................................................................................................... [ceph-salt]
```

**Comment by ricardoasmarques** [comment]
We are considering removing `/ssh/user` setting, and always use `cephadm` SSH user so don't work on this issue yet.

**Comment by ricardoasmarques** [comment]
Since https://github.com/ceph/ceph-salt/pull/363 SSH user is no longer configurable, instead, `ceph-salt` will always create and use `cephadm` user.
