### ISSUE TITLE
SES7 Deployment Guide section on preparing for "ceph-salt apply" should mention "log_level: info"

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#489]
**Summary**

The SES7 Deployment Guide definitely contains a chapter on deploying SES7 using ceph-salt and cephadm. This chapter must contain information on setting up Salt in preparation for running "ceph-salt apply".

This section should mention that:

1. the default log level of both salt-master and salt-minion is "WARNING"
2. the default log level is insufficient for debugging issues with Salt and ceph-salt
3. the user should change the log level setting to `log_level: info` for both salt-master and salt-minion
4. this setting should be changed on **all** cluster (minion) nodes

**Comment by asettle** [comment]
@smithfarm looks good to me. Something we don't currently document. 1 question, do we have details on how to change the log level setting for salt-master and salt-minion? Is our log files stored in a standard location, ie `/var/log/salt/master` and `/var/log/salt/minion`?

**Comment by smithfarm** [comment]
So, the logs do get created in those locations, but the configuration files the users will edit are:

    /etc/salt/master
    /etc/salt/minion

These are the files where the users will find the line that says

    #log_level: WARN

and uncomment it and change WARN to INFO
