### ISSUE TITLE
manually deploying MGR in case if orchestration is unavailable

### ISSUE THREAD

**Issue by denisok** [SUSE/doc-ses#493]
**Link To Section**
Probably it should be a new section "Troubleshooting MGR" in https://susedoc.github.io/doc-ses/master/html/ses-troubleshooting/

**Summary**
In case of only one MGR deployed in the cluster and that manager has some issues connecting to the cluster - the whole orchestration is essentially unavailable. It is recommended to have couple of managers for this case, but if there are scenarios where there no active manager, this how MGR could be deployed without `ceph orch` (Ceph Orchestrator)

**Basic Example**
https://confluence.suse.com/display/SUSEEnterpriseStorage/manually+deploying+a+MGR

**Motivation**
Customer to be able to restore cluster functionality without contacting support.

**Notes**

**Comment by sebastian-philipp** [comment]
should probably end up in https://susedoc.github.io/doc-ses/master/html/ses-troubleshooting/bp-troubleshooting-cephadm.html
