### ISSUE TITLE
[doc] 3.2  Prerequisites

### ISSUE THREAD

**Issue by denisok** [SUSE/doc-ses#502]
### Type of report
   - [ ] bug
   - [x] feature request

### Source Document
3.2  Prerequisites:

https://susedoc.github.io/doc-ses/master/single-html/ses-rook/#kube-prereq

### Summary
doc update for the lvm package on the osd nodes

### Steps To Reproduce
Install Rook 1.4

### Expected Results
OSD will be deployed

### Actual Results
OSD fail to deploy because lbm2 package is not installed

### Notes

We need to add to the doc that lvm2 package should be preinstalled on OSD nodes.

```

Rook v1.4 has a breaking change that should be considered before upgrading.

Make sure the lvm2 package is installed on the host where OSDs are running.

If not, the prepare job will fail and the upgrade of OSDs will be blocked.

This only applies to non-PVC OSDs. Beginning in v1.3, OSDs created on PVCs no longer rely on LVM.

```
https://github.com/rook/rook/releases/tag/v1.4.0 : 
```
The operator will require the presence of the lvm2 package on the host where OSDs will run in some scenarios. If not available, the deployment will fail. The package is required for the OSDs to start after a node restart. This does not apply to OSDs created with the storageClassDeviceSet since v1.3.
```

**Comment by asettle** [comment]
@lproven to encorporate when transcribing Rook docs

**Comment by asettle** [comment]
@denisok I've added the prereq to the docs, however your note is best placed in the release notes. Could you please curate for the release notes list on Confluence? Thanks.
