### ISSUE TITLE
[doc] The default-update-no-reboot parameter does not exist.

### ISSUE THREAD

**Issue by s-sagawa** [SUSE/doc-ses#510]
**Link To Section**
https://documentation.suse.com/ja-jp/ses/5.5/single-html/ses-deployment/#ds-disable-reboots

**Summary**
The default-update-no-reboot parameter does not exist. and
The meaning of the parameter is different between Japanese and English.
I think that the following commits are not fixed in the Japanese version.
https://github.com/SUSE/doc-ses/commit/5d0112e1095007e9a69bf7bd066664efe8856983#diff-899b9d9033f577a81a8ff4d60250d288
https://github.com/SUSE/doc-ses/commit/7b7a7578a954be78c7bd6135dddef91a19058c74

Please fixes as follows.

[before]
7.1.5 ステージ0での更新と再起動の無効化
:
ステージ0でクラスタノードが更新または再起動されるのを防ぐには、
/srv/pillar/ceph/stack/ceph/cluster.ymlを編集
:
default-update-no-reboot
ノードが再起動しないようにしますが、パッケージの更新は許可します。

default
ノードによるパッケージの更新とノードの再起動の両方を許可します。

[after]
7.1.5 ステージ0での更新と再起動の無効化
:
ステージ0でクラスタノードが更新または再起動されるのを防ぐには、
/srv/pillar/ceph/stack/global.ymlを編集
:
default-update-reboot
ノードによるパッケージの更新とノードの再起動の両方を許可します。

default
ノードが再起動しないようにしますが、パッケージの更新は許可します。

**Steps To Reproduce**
None

**Comment by asettle** [comment]
Hi @s-sagawa - I have provided the updated text here: https://github.com/SUSE/doc-ses/pull/511

Please review and let me know if this is correct.

Thank you,

Alex

**Comment by s-sagawa** [comment]
Hi @asettle

I appreciate your quick modification, but that is not the change I've intended to make.
Let me get my points straight.

1. Change the file path.
  /srv/pillar/ceph/stack/ceph/cluster.yml -> /srv/pillar/ceph/stack/global.yml

2. Change the available parameters, these order and description as follows.
<pre>
  [before]
   default-no-update-no-reboot
    ノードがパッケージの更新と再起動のどちらも行わないようにします。 
   default-no-update-reboot
    ノードがパッケージを更新しないようにしますが、再起動は許可します。 
   default-update-no-reboot
    ノードが再起動しないようにしますが、パッケージの更新は許可します。 
   default
    ノードによるパッケージの更新とノードの再起動の両方を許可します。
  [after]
   default
     ノードが再起動しないようにしますが、パッケージの更新は許可します。
   default-update-reboot
     ノードによるパッケージの更新とノードの再起動の両方を許可します。
   default-no-update-reboot
     ノードがパッケージを更新しないようにしますが、再起動は許可します。
   default-no-update-no-reboot
     ノードがパッケージの更新と再起動のどちらも行わないようにします。
</pre>

The following is the whole section before and after changes.

<pre>
[before]
7.1.5 ステージ0での更新と再起動の無効化
:
ステージ0でクラスタノードが更新または再起動されるのを防ぐには、
/srv/pillar/ceph/stack/ceph/cluster.ymlを編集し、Salt Master、
すべてのSalt Minion、またはすべてのノードのいずれの動作を変更する必要があるかに応じて、
stage_prep_masterオプションまたはstage_prep_minionオプションを追加します。 

どちらのオプションも以下の値を受け付けます。 


default-no-update-no-reboot
  ノードがパッケージの更新と再起動のどちらも行わないようにします。 
default-no-update-reboot
  ノードがパッケージを更新しないようにしますが、再起動は許可します。 
default-update-no-reboot
  ノードが再起動しないようにしますが、パッケージの更新は許可します。 
default
  ノードによるパッケージの更新とノードの再起動の両方を許可します。 

[after]
7.1.5 ステージ0での更新と再起動の無効化
:
ステージ0でクラスタノードが更新または再起動されるのを防ぐには、
/srv/pillar/ceph/stack/ceph/global.ymlを編集し、Salt Master、
すべてのSalt Minion、またはすべてのノードのいずれの動作を変更する必要があるかに応じて、
stage_prep_masterオプションまたはstage_prep_minionオプションを追加します。 

どちらのオプションも以下の値を受け付けます。 

default
  ノードが再起動しないようにしますが、パッケージの更新は許可します。
default-update-reboot
  ノードによるパッケージの更新とノードの再起動の両方を許可します。
default-no-update-reboot
  ノードがパッケージを更新しないようにしますが、再起動は許可します。
default-no-update-no-reboot
  ノードがパッケージの更新と再起動のどちらも行わないようにします。 
</pre>

Thanks,
Sagawa

**Comment by asettle** [comment]
> Hi @asettle
> 
> I appreciate your quick modification, but that is not the change I've intended to make.
> Let me get my points straight.
> 
> 1. Change the file path.
>    /srv/pillar/ceph/stack/ceph/cluster.yml -> /srv/pillar/ceph/stack/global.yml
> 2. Change the available parameters, these order and description as follows.
> 
>   [before]
>    default-no-update-no-reboot
>     ノードがパッケージの更新と再起動のどちらも行わないようにします。 
>    default-no-update-reboot
>     ノードがパッケージを更新しないようにしますが、再起動は許可します。 
>    default-update-no-reboot
>     ノードが再起動しないようにしますが、パッケージの更新は許可します。 
>    default
>     ノードによるパッケージの更新とノードの再起動の両方を許可します。
>   [after]
>    default
>      ノードが再起動しないようにしますが、パッケージの更新は許可します。
>    default-update-reboot
>      ノードによるパッケージの更新とノードの再起動の両方を許可します。
>    default-no-update-reboot
>      ノードがパッケージを更新しないようにしますが、再起動は許可します。
>    default-no-update-no-reboot
>      ノードがパッケージの更新と再起動のどちらも行わないようにします。
> The following is the whole section before and after changes.
> 
> [before]
> 7.1.5 ステージ0での更新と再起動の無効化
> :
> ステージ0でクラスタノードが更新または再起動されるのを防ぐには、
> /srv/pillar/ceph/stack/ceph/cluster.ymlを編集し、Salt Master、
> すべてのSalt Minion、またはすべてのノードのいずれの動作を変更する必要があるかに応じて、
> stage_prep_masterオプションまたはstage_prep_minionオプションを追加します。 
> 
> どちらのオプションも以下の値を受け付けます。 
> 
> 
> default-no-update-no-reboot
>   ノードがパッケージの更新と再起動のどちらも行わないようにします。 
> default-no-update-reboot
>   ノードがパッケージを更新しないようにしますが、再起動は許可します。 
> default-update-no-reboot
>   ノードが再起動しないようにしますが、パッケージの更新は許可します。 
> default
>   ノードによるパッケージの更新とノードの再起動の両方を許可します。 
> 
> [after]
> 7.1.5 ステージ0での更新と再起動の無効化
> :
> ステージ0でクラスタノードが更新または再起動されるのを防ぐには、
> /srv/pillar/ceph/stack/ceph/global.ymlを編集し、Salt Master、
> すべてのSalt Minion、またはすべてのノードのいずれの動作を変更する必要があるかに応じて、
> stage_prep_masterオプションまたはstage_prep_minionオプションを追加します。 
> 
> どちらのオプションも以下の値を受け付けます。 
> 
> default
>   ノードが再起動しないようにしますが、パッケージの更新は許可します。
> default-update-reboot
>   ノードによるパッケージの更新とノードの再起動の両方を許可します。
> default-no-update-reboot
>   ノードがパッケージを更新しないようにしますが、再起動は許可します。
> default-no-update-no-reboot
>   ノードがパッケージの更新と再起動のどちらも行わないようにします。 
> Thanks,
> Sagawa

Thank you Sagawa! This is immensely helpful :smile: I will update, and ask for your review again shortly.

**Comment by asettle** [comment]
@s-sagawa The update should be ready for your review again. I have had a native Japanese speaker review also to help. Let me know if there's anything else required.

**Comment by s-sagawa** [comment]
Hi @asettle

Great!
I've confirmed that the fix is ​​what I intended.

Thanks,
Sagawa
