### ISSUE TITLE
[doc] 6.3.2.10  Configure Container Registry

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/doc-ses#513]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.3.2.10  Configure Container Registry:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-configure-registry

### Summary

`podman --restart=always` doesn't survive a reboot. 

We need to properly create a systemd service file for this to work.

The systemd unit file we document should be similar to the one generated by `podman generate systemd registry`

note that we should **NOT**  recommend users to run `podman generate systemd registry` by themselves.

**Comment by tbazant** [comment]
@sebastian-philipp It is up to the dev team to create the systemd unit file for podman, right? Once that is done and we know the unit file name, ping me and we can document it

**Comment by jschmid1** [comment]
Ideally this is something `ceph-salt` would do. Agree @ricardoasmarques ?

**Comment by ricardoasmarques** [comment]
If I'm understanding correctly, `podman generate systemd registry --name <name>` should be executed by the one that creates the **local registry** by running `podman run -d --restart=always --net=host --name registry -p 5000:5000 registry:2`.

ATM, `ceph-salt` doesn't configure local registries so it should not run `podman generate ...`, and `cephadm` has an open issue for that https://tracker.ceph.com/issues/47286, but it's not implemented yet.

So I think that for now, the correct place for this is `documentation`.

**Comment by asettle** [comment]
@ricardoasmarques - I'm not sure I understand then. You're saying that `podman generate systemd registry....` should be created by running `podman run -d --restart=always....` except the problem reported here is that `--restart=always` isn't reliable, and therefore we need to _manually_ create a systemd service file for this to work. Is this correct? If so, we cannot document this change until we know the unit file name.

Let me know if I have misunderstood :)

**Comment by ricardoasmarques** [comment]
I mean, if `podman run -d --restart=always ... registry:2` is manually executed by the user, then `podman generate systemd registry...` should also be manually executed by the user, I think.

**Comment by tbazant** [comment]
@jschmid1 @sebastian-philipp 
1) what is the complete command for `podman generate systemd registry` ?
2) where should a user run it? after `podman run -d --restart=always --net=host --name registry -p 5000:5000 registry:2`?

**Comment by tbazant** [comment]
nice example is here https://www.mankier.com/1/podman-generate-systemd#Examples-Generate_and_print_a_systemd_unit_file_for_a_container

**Comment by jschmid1** [comment]
I'd assume this is something like this:

```

podman run -d --restart=always --net=host --name registry -p 5000:5000 registry:2

podman generate systemd registry >  /etc/systemd/system/suse_registry.service

systemctl start suse_registry.service

systemctl enable suse_registry.service

# verify if its running

systemctl status suse_registry.service
```
