### ISSUE TITLE
[doc] 2.9.4  Enabling the Object Gateway Management Front-end

### ISSUE THREAD

**Issue by lezare** [SUSE/doc-ses#522]
### Type of report
   - [x] bug

### Source Document
2.9.4  Enabling the Object Gateway Management Front-end:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#dashboard-ogw-enabling

### Summary
Need to in addition add a note to allow http (or https) with the firewall.

### Notes
By default the firewall is enabled with SLES15SP2, which means for RGW access via the dashboard to succeed the port (80 by default) needs to be allowed (for example: yast firewall > public > add http) on the designated RGW nodes.

**Comment by asettle** [comment]
We do have a firewall recommendation settings (as per SES 6) but this moved: https://susedoc.github.io/doc-ses/master/html/ses-troubleshooting/storage-tips.html#storage-bp-net-firewall

You can see:

```Object Gateway
Open the port where Object Gateway communication occurs. It is set in /etc/ceph.conf on the line starting with rgw frontends =. Default is 80 for HTTP and 443 for HTTPS (TCP).```

I'll add a link between the two.
