### ISSUE TITLE
[doc] 4.4  Moving the Admin Node to a New Server

### ISSUE THREAD

**Issue by dthpulse** [SUSE/doc-ses#526]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
4.4  Moving the Admin Node to a New Server:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#moving-saltmaster

### Summary
section 4.4.6 will not work in case you are using new hostname for the new admin node because exported configuration file contains old admin hostname which ends with 
```
# ceph-salt import cluster.json
Cannot find minion 'master.sestest'
```

One has to edit json file and replace old admin hostname with new one.

### Steps To Reproduce
follow documentation and move admin node to new admin node with different hostname.

### Expected Results
```
# ceph-salt import cluster.json
Configuration imported.
```

### Actual Results
```
# ceph-salt import cluster.json
Cannot find minion 'master.sestest'
```

**Comment by asettle** [comment]
Thanks @dthpulse - I'll add a note in the instructions that saying we need to add a note saying that you must rename the minion id in the json file before importing. Cheers!
