### ISSUE TITLE
[doc] 4.6.1  Starting the Upgrade

### ISSUE THREAD

**Issue by dthpulse** [SUSE/doc-ses#527]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
4.6.1  Starting the Upgrade:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#deploy-cephadm-day2-cephupgrade-start

### Summary
missing parameter to run upgrade.
In documentation:

```
ceph orch upgrade --image REGISTRY_URL
```
which ends with:

```
# ceph orch upgrade --image registry.suse.de/devel/storage/7.0/containers/ses/7/ceph/ceph:latest
no valid command found; 6 closest matches:
orch upgrade check [<image>] [<ceph_version>]
orch upgrade status
orch upgrade start [<image>] [<ceph_version>]
orch upgrade pause
orch upgrade resume
orch upgrade stop
Error EINVAL: invalid command
```

correct is:
```
# ceph orch upgrade start --image registry.suse.de/devel/storage/7.0/containers/ses/7/ceph/ceph:latest
Initiating upgrade to registry.suse.de/devel/storage/7.0/containers/ses/7/ceph/ceph:latest
```

so in documentation it should looks like:

```
ceph orch upgrade start --image REGISTRY_URL
```
### Steps To Reproduce
follow documentation

### Expected Results

`Initiating upgrade to ...`

### Actual Results
`Error EINVAL: invalid command`

**Comment by asettle** [comment]
@sebastian-philipp did we not just fix this? Is `start` the correct syntax? Presumably.

**Comment by asettle** [comment]
@sebastian-philipp please review PR
