### ISSUE TITLE
All coverage of lvmcache should be removed from SES7 documentation (and replaced by a statement of non-support)

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#530]
**Summary**

lvmcache feature was included in SES6 as a tech preview and documented via https://jira.suse.com/browse/SES-268

lvmcache feature has been dropped in SES7 and will not be available at all (not even as a tech preview)

**Steps To Reproduce**

1. read the SES7 documentation
2. presumably encounter mentions of lvmcache feature, which does not exist in SES7

**Expected Results**

I expect to not encounter any mention of the lvmcache feature in the SES7 documentation. Please determine whether it is there and, if it is, remove/revert it. Replace it with a terse statement stating that the lvmcache tech preview in SES6 is no longer available in SES7.

Thanks!

**Comment by asettle** [comment]
Good news @smithfarm - it indeed is not referenced at all within the SES 7 documentation. I can now add this as a release note for SES 7.
