### ISSUE TITLE
[doc] Use helm for uninstall rook docs

### ISSUE THREAD

**Issue by BlaineEXE** [SUSE/doc-ses#541]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
1.6  Uninstalling Rook:

https://susedoc.github.io/doc-ses/master/single-html/ses-rook/#kube-uninstall

### Summary
Uninstall steps will have to be updated to reflect uninstall of the operator using Helm once we have our downstream Helm strategy ironed out. 

Practically, I think what this means is item 3 needs to be
```sh
kubectl delete -f cluster.yaml # or whatever your CephCluster file is
# now uninstall operator via helm uninstall steps
```

Related: https://jira.suse.com/browse/SES-1967

**Comment by asettle** [comment]
Probably also another item for Dirk?

**Comment by asettle** [comment]
I've removed the outdated commands, and left the notes inline for us to address later.

**Comment by asettle** [comment]
Comment from @sebastian-philipp in the JIRA:

```https://documentation.suse.com/ses/6/single-html/ses-deployment/#kube-uninstall is problematic:

It references the upstream documentation's `master` branch, which might change and no longer matches the version we ship in SES-6
It should be complete and also contain steps needed to clean drives on the nodes
export DISK="/dev/vdb"
sgdisk --zap-all $DISK
ls /dev/mapper/ceph-* | xargs -I% -- dmsetup remove %
rm -rf /dev/ceph-*
It is also missing CSI: https://github.com/SUSE-Cloud/socok8s/pull/793/files```
