### ISSUE TITLE
[doc] Update doc links to downstream rather than upstream

### ISSUE THREAD

**Issue by BlaineEXE** [SUSE/doc-ses#542]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
1.5  Using Rook as Storage for Kubernetes Workload:

https://susedoc.github.io/doc-ses/master/single-html/ses-rook/#kube-using-rook

### Summary
Links in this section should be based on upstream v1.4 docs (not v1.0) and should link to our internal downstream docs.

**Comment by asettle** [comment]
Needs to be further verified

**Comment by tbazant** [comment]
> Needs to be further verified

@asettle i went through the whole guide and there os no `http` string that would reference upstream pages. what else needs to be verified?

**Comment by asettle** [comment]
@tbazant then that's all for now :)
