### ISSUE TITLE
[doc] Update kube config docs for helm charts

### ISSUE THREAD

**Issue by BlaineEXE** [SUSE/doc-ses#544]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
1.4.1.2  Operator Configuration:

https://susedoc.github.io/doc-ses/master/single-html/ses-rook/#kube-config-operator

### Summary
This section will change with Helm-based deployment. Suggest maybe changing this to a "TODO: update with helm deploy info soon" or something? 

Related: https://jira.suse.com/browse/SES-1967

**Comment by asettle** [comment]
I've replaced with a placeholder, and nothing more at this stage. This should stay open until the work is complete, however.

**Comment by asettle** [comment]
Helm docs required
