### ISSUE TITLE
[doc] Ensure rook docs reference caasp 4.5 

### ISSUE THREAD

**Issue by BlaineEXE** [SUSE/doc-ses#546]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
1.2  Prerequisites:

https://susedoc.github.io/doc-ses/master/single-html/ses-rook/#kube-prereq

### Summary
Docs currently say
> A running SUSE CaaS Platform 4 cluster

I think for SES7 (at our initial release at least) we should support SUSE CaaSP Platform 4.5 and up. @ajaeger might have better direction. I would say that it is sufficient to say "CaaSP 4.5 and up", but I wonder if we should specify that we don't support versions of CaaSP other than 4.x (i.e., CaaSP v5.0 or whatever comes next isn't supported until we explicitly support it).

**Comment by ajaeger** [comment]
Let's say "SUSE CaaS Platform 4.5 only" - we will change that once we know how the next version looks like and have tested it.
