### ISSUE TITLE
[doc] Remove common.yaml for helm chart docs

### ISSUE THREAD

**Issue by BlaineEXE** [SUSE/doc-ses#547]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
1.4.1.1  Global Configuration:

https://susedoc.github.io/doc-ses/master/single-html/ses-rook/#kube-configure-global

### Summary
> Depending on which features of Rook you intend to use, alter the 'Pod Security Policy' configuration in common.yaml to limit Rook's security requirements. Follow the comments in the manifest file. 

With Helm, we no longer use `common.yaml` for installs. We need to determine these instructions when Helm is involved.

Related: https://jira.suse.com/browse/SES-1967

**Comment by asettle** [comment]
Should Dirk look at this one?
