### ISSUE TITLE
[doc] Remove outdated content related to rook-ceph

### ISSUE THREAD

**Issue by BlaineEXE** [SUSE/doc-ses#549]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
1.4.1.4  Documentation:

https://susedoc.github.io/doc-ses/master/single-html/ses-rook/#kube-config-docs

### Summary
> The Rook-Ceph upstream documentation at https://rook.github.io/docs/rook/master/ceph-storage.html contains more detailed information about configuring more advanced deployments. Use it as a reference for understanding the basics of Rook-Ceph before doing more advanced configurations. 

With us copying the upstream docs we need. This statement is no longer quite right. Or we can self-reference to the current doc to reiterate "please understand the Rook-Ceph docs in full before attempting production configuration."

**Comment by asettle** [comment]
I've actually deleted that whole section, because it's redundant and moved the link to caasp up when it is first mentioned. Cheers.
