### ISSUE TITLE
Document ceph-salt tuned roles

### ISSUE THREAD

**Issue by ricardoasmarques** [SUSE/doc-ses#551]
If already documented for DeepSea, we need to update accordingly.

https://github.com/ceph/ceph-salt/pull/361
https://github.com/ceph/ceph-salt/pull/364

**Comment by asettle** [comment]
@ricardoasmarques this doesn't give me a lot to go on. What is a ceph-salt tuned role? What was the corresponding documentation for DeepSea?

Those PRs you've linked don't contain a lot of information for us. Do you just require us to up date the console output to include a "tuned" role as per: https://user-images.githubusercontent.com/14297426/92003538-12a5dc80-ed39-11ea-9d4b-c6052af0b4e1.png ?

**Comment by asettle** [comment]
In DeepSea tuned profiles were deployed by default in Ceph clusters active on mons, mgr, and OSD nodes: https://susedoc.github.io/doc-ses/ses6/single-html/ses-deployment/#ds-depl-stages

**Comment by asettle** [comment]
similar to this https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-configure-cephadm
`ceph-salt config /ceph_cluster/roles/tuned/latency <minion>`
and
`ceph-salt config /ceph_cluster/roles/tuned/throughput <minion>`
and should be done before `ceph-salt apply`
