### ISSUE TITLE
ceph-salt config '/containers/image/ceph' was moved

### ISSUE THREAD

**Issue by ricardoasmarques** [SUSE/doc-ses#552]
Since https://github.com/ceph/ceph-salt/pull/386, ceph image path config was moved from `/containers/image/ceph` to `/cephadm_bootstrap/ceph_image_path`.

**Comment by asettle** [comment]
We don't document the image path anywhere, I don't think this requires a doc update. @tbazant ?

**Comment by asettle** [comment]
We document `ceph-salt config ls` twice:

1. https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-configure-verify

2. https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-configure-shell

**Comment by asettle** [comment]
@tbazant we need to update the output in option 1 (deploy-cephadm-configure-verify)
