### ISSUE TITLE
ceph.conf and keyring are needed before the driver is installed

### ISSUE THREAD

**Issue by abonillabeeche** [SUSE/doc-ses#558]
https://susedoc.github.io/doc-ses/master/single-html/ceph-windows/#install-config

Replace "After installing" with "Before Installing" Perhaps even better is to put this section above as it is a necessary step to take before installing the driver.

**Comment by asettle** [comment]
@ml8mr do you have any issues with this suggestion? :)

**Comment by ml8mr** [comment]
Alejandro's suggestion is due to an older bug in the installer. This has been fixed, so leaving this as "After installing" is just fine.

Thanks for bringing this up though!
