### ISSUE TITLE
Rewrite and update NFS Gansha chap admin guide

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-ses#563]
From the content created by @mgfritch here: https://confluence.suse.com/pages/viewpage.action?spaceKey=SUSEEnterpriseStorage&title=nfs-ganesha we need to completely update the NFS Ganesha Admin Guide chapter

**Comment by asettle** [comment]
Some key notes from @mgfritch 

1. Native CephFS is always better than via a gateway (NFS) (keep the note at the beginning of the chapter)
2. Move to a more appropriate location: https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-nfsganesha-namespace (or cross ref to https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#sec-ceph-rgw-limits)
3. Can remove this section (mostly): https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-nfsganesha-config the config values are but cephadm will rewrite them and the user doesn't need to know. We used to have the user write the section in the ganesha.conf and now we do that for them automagically but that's true of exports too... etc
4. https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ganesha-nfsport TBD - wants to stream line it so it's just a port listed in the ServiceSpec, but that depends on how fast I can get that upstream. @mgfritch will write up a little manual to do that via a RADOS object on the nfs-ganesha confluence page 
5. there is also this section ... https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-nfsganesha-customrole @mgfritch to provide a quick re-write PR for that (no roles now that DeepSea is gone)
6. Check with @supriti regarding https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ganesha-rgw-supported-operations - most of it should still be true
7. Re-work the chapter to have a better flow. Starting and restarting the service should be priority information at the top
8. Need a replacement for this:
https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-nfsganesha-verify t's NFSv4 only now, so cannot do the `showmount` command
9.

**Comment by mgfritch** [comment]
> 8. Need a replacement for this:
>    https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-nfsganesha-verify t's NFSv4 only now, so cannot do the `showmount` command

added a rough draft here: https://github.com/SUSE/doc-ses/pull/565

**Comment by mgfritch** [comment]
> 5. there is also this section ... https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-nfsganesha-customrole @mgfritch to provide a quick re-write PR for that (no roles now that DeepSea is gone)
> 6. Check with @supriti regarding https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ganesha-rgw-supported-operations - most of it should still be true


draft: https://github.com/SUSE/doc-ses/pull/573
