### ISSUE TITLE
[doc] 14.1.2  Single Gateway Example

### ISSUE THREAD

**Issue by dthpulse** [SUSE/doc-ses#567]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
14.1.2  Single Gateway Example:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#sec-ses-cifs-example

### Summary
samba share with vfs_ceph module cannot use option `ceph: user_id = samba.gw` as mounting share with it causes error `tree connect failed: NT_STATUS_UNSUCCESSFUL`
We should let CephFS to use the process id instead. Means keep it empty or not use it at all.

### Steps To Reproduce
follow documentation

### Expected Results
share is mounted

### Actual Results
tree connect failed: NT_STATUS_UNSUCCESSFUL

**Comment by asettle** [comment]
Thanks @dthpulse - @ddiss is working on updating the docs at the moment :) @ddiss is this section up to date based on the SES 7?

**Comment by dthpulse** [comment]
my bad. I didn't created authentication keyring for smb.gw user. Closing

**Comment by ddiss** [comment]
>  @ddiss is this section up to date based on the SES 7?

yes, the section should still be applicable.
