### ISSUE TITLE
5.3 Shutdown and Restart of the Whole Ceph Cluster in SES7

### ISSUE THREAD

**Issue by ricardoasmarques** [SUSE/doc-ses#584]
**Link To Section**
SES6: https://susedoc.github.io/doc-ses/ses6/html/ses-admin/ceph-operating-services.html#ceph-cluster-shutdown
SES7: https://susedoc.github.io/doc-ses/master/html/ses-admin/cha-ceph-operating.html#ceph-cluster-shutdown

**Summary**
`"Shutdown and Restart of the Whole Ceph Cluster"` section must be updated for cephadm/containers environment.

**Steps To Reproduce**
In SES6, we use a Deepsea runner to guarantee that services are stoped in the correct order:
1. gateways
2. osds
3. mons/mgrs

But we don't guarantee that on SES7 docs.

**Expected Results**
We need to check if current documentation is still valid for `SES7`.

From the links below, the workflow should now be something like:

_1) Get cluster FSID:_
```
# ceph -s
```

_2) Set some OSD flags:_
```
# ceph osd set noout
# ceph osd set nobackfill
# ceph osd set norecover
# ceph osd set norebalance
# ceph osd set nodown
# ceph osd set pause
```

_3) Stop ceph service on all nodes:_
```
# salt TARGET cmd.run "systemctl stop ceph-<fsid>.target"
```

But we are still missing a way to guarantee that services are stopped in the correct order.

We may need a new `ceph-salt` or `cephadm` feature here.

_**(This workflow requires confirmation)**_

**Notes**
Some links that may contain useful information
- https://github.com/ceph/ceph-salt/issues/359
- https://jira.suse.com/browse/SES-2048
- https://ceph.io/planet/how-to-do-a-ceph-cluster-maintenance-shutdown/

**Comment by bloriot** [comment]
Ideally, a procedure to shutdown and restart of the whole Ceph Cluster in a SES7 Rook deployment should be available as well.

**Comment by ricardoasmarques** [comment]
I've now opened the following `ceph-salt` PR that will add a new command to stop all ceph-services: https://github.com/ceph/ceph-salt/pull/404

**Comment by ricardoasmarques** [comment]
@tbazant, this is what we need to change in docs:

1) `# ceph-salt stop` instead of `# salt TARGET cmd.run "systemctl stop ceph.target"`

2) `#salt -G 'ceph-salt:member' cmd.run "shutdown -h"` instead of `#salt TARGET cmd.run "shutdown -h"`

**Comment by ricardoasmarques** [comment]
https://github.com/ceph/ceph-salt/pull/404 has been merged, we can now adapt the documentation

**Comment by asettle** [comment]
@tbazant this needs to be included in the docs for M18 (final feature freeze), which is 30th of Sept
