### ISSUE TITLE
[doc] 11.13.2.7  Start the Gateway

### ISSUE THREAD

**Issue by theanalyst** [SUSE/doc-ses#596]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
11.13.2.7  Start the Gateway:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-rgw-fed-masterzone-startrgw

### Notes

    This should be replaced with the equivalent ceph orch command, and here redeploying the gateway with `ceph orch apply` specifying the rgw zone makes sense

**Comment by theanalyst** [comment]
@matthewoliver @jschmid1 thoughts

**Comment by theanalyst** [comment]
also basically all the ceph.conf sections should be equivalent ceph config commands, here we'd have to kill the default.default rgw service and resurrect a new <realm>.<zone> rgw service

**Comment by asettle** [comment]
> also basically all the ceph.conf sections should be equivalent ceph config commands, here we'd have to kill the default.default rgw service and resurrect a new . rgw service

Identifying the ceph.conf sections for OGW:
- https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-rgw-secondzone-update-config
- https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#id-1.4.5.2.13.4.8
