### ISSUE TITLE
rook: Document adding labels to k8s nodes

### ISSUE THREAD

**Issue by ml8mr** [SUSE/doc-ses#611]
As @thehejik said, we need to include a section on assigning labels to a node for its specific role in the SES cluster.

The following command can be used for this:

 node-role.rook-ceph/cluster=( mon | mgr | osd | mon-mgr-osd | any )

Example for all nodes:
kubectl label nodes --all node-role.rook-ceph/cluster=any

Example for single node:
kubectl label node <node-name> node-role.rook-ceph/cluster=any

**Comment by tbazant** [comment]
@thehejik when looking at https://susedoc.github.io/doc-ses/master/html/ses-rook/, where exactly should i insert the suggested snippets?

**Comment by thehejik** [comment]
> @thehejik when looking at https://susedoc.github.io/doc-ses/master/html/ses-rook/, where exactly should i insert the suggested snippets?

There are already some mentions in section `5.1.3.10 Annotations and Labels` but from the description it's not clear to me that the labels are mandatory for SES deployment.

I would expand section `1.4.1.3 Ceph Cluster Configuration` (deployment on CaaSP) with the provided snippet and description that the labels are mandatory and also I'd add a link to section `5.1.3.10 Annotations and Labels` for more info.
