### ISSUE TITLE
[doc] 6.4.2  Recovering a Monitor's Broken <code class="literal">monmap</code>

### ISSUE THREAD

**Issue by dthpulse** [SUSE/doc-ses#615]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.4.2  Recovering a Monitor's Broken <code class="literal">monmap</code>:

https://susedoc.github.io/doc-ses/master/html/ses-troubleshooting/bp-troubleshooting-monitors.html#broken-mon-map

### Summary

ceph-mon command is not available on nodes but on containers

### Steps To Reproduce

follow documentation and you will get 
```
# ceph-mon
If 'ceph-mon' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf ceph-mon
```

### Expected Results

`ceph-mon` command is available

### Actual Results

```
# ceph-mon
If 'ceph-mon' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf ceph-mon
```

**Comment by asettle** [comment]
Closing as this is currently being tracked actively here: https://bugzilla.suse.com/show_bug.cgi?id=1176405

Until an appropriate resolution is agreed upon by development, documentation can't do anything other than remove the procedure (which we will do)
