### ISSUE TITLE
SES7 Admin Guide: Explain to users how to find out which image tags are available in a container image registry

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#626]
**Link To Section**

Not sure. Leaving that up to you.

**Summary**

The documentation (presumably) does not instruct users how to find out which tags are available for a given remote container image. In other words: the users knows the image patch, but they don't know how to find out which tags are available on the registry for that image.

**Basic Example**

```
# zypper install jq skopeo
$ skopeo inspect docker://registry.suse.de/suse/containers/ses/7/containers/ses/7/ceph/ceph | jq -r .RepoTags
[
  "15.0.0.8588",
  "15.0.0.8588.1.18",
  "15.0.0.9092",
  "15.0.0.9092.1.112",
  "15.0.0.9543",
  "15.0.0.9543.1.147",
  "15.1.0.168",
  "15.1.0.168.1.210",
  "15.1.0.818",
  "15.1.0.818.1.261",
  "15.2.0.108",
  "15.2.0.108.3.78",
  "15.2.1.16",
  "15.2.1.16.3.188",
  "15.2.1.246",
  "15.2.1.246.3.251",
  "15.2.2.60",
  "15.2.2.60.3.326",
  "15.2.3.455",
  "15.2.3.455.3.373",
  "15.2.3.579",
  "15.2.3.579.3.383",
  "15.2.4.381",
  "15.2.4.381.3.399",
  "15.2.4.557",
  "15.2.4.557.3.436",
  "15.2.4.827",
  "15.2.4.827.3.455",
  "15.2.4.944",
  "15.2.4.944.3.483",
  "15.2.5.220",
  "15.2.5.220.3.503",
  "latest",
  "sle15.2.octopus"
]
```

**Motivation**

Users need to find out which tags are available so they can enter the correct one in commands like:

```
ceph orch upgrade start --image registry.suse.de/suse/containers/ses/7/containers/ses/7/ceph/ceph:15.2.5.220
```

**Notes**

Thanks for tackling this. You are awesome.

**Comment by ajaeger** [comment]
I consider this a hack, we need a better solution. I suggest to check whether we can do this better...

**Comment by smithfarm** [comment]
> I consider this a hack, we need a better solution. I suggest to check whether we can do this better...

This is the only supported way that I know of.

**Comment by ajaeger** [comment]
And I ask for a better way - talked with @ml8mr about this as well last week. Let's see whether we have something better - or need to use this hack for now.

**Comment by smithfarm** [comment]
> And I ask for a better way - talked with @ml8mr about this as well last week. Let's see whether we have something better - or need to use this hack for now.

We *could* implement something in `ceph-salt` (e.g. "ceph-salt tags <container_image_path>") which would automate the above procedure and just dump the tags. Would this be sufficiently "less hacky"? Or were you thinking something more graphical, more "in-browser"?

**Comment by asettle** [comment]
AJ's suggestion here: https://confluence.suse.com/pages/viewpage.action?spaceKey=SUSEEnterpriseStorage&title=SES+7+-+Container+Updates
