### ISSUE TITLE
[doc] 1.3  Getting Started with Rook

### ISSUE THREAD

**Issue by dirkmueller** [SUSE/doc-ses#629]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
1.3  Getting Started with Rook:

https://susedoc.github.io/doc-ses/master/single-html/ses-rook/#getting-started-rook

### Summary

What I noticed here is that the "helm install.." etc invocations are referring to "helm", and its not clear that this must be helm3. I recommend to add a command to ensure with "update-alternatives" that "helm" is referring to helm3 as currently things are helm2. 

```
sudo zypper install helm3
sudo update-alternatives --set helm /usr/bin/helm3 || :
```

the ''|| :" ensures that the failure is ignored, just in case there is no update-alternatives support for some reason.

### Notes

see https://github.com/SUSE/doc-caasp/blob/53724eeffb7d3cbd27876d3c8114a0de244b37db/adoc/admin-software-installation.adoc#installing-helm

**Comment by asettle** [comment]
Fortunately, that was already fixed last night: https://susedoc.github.io/doc-ses/master/single-html/ses-rook/#getting-started-rook

Regarding the addition of "update-alternatives" two schools of thought here:

1. We tell the user to install helm3, the assumption in the docs is that the user will have nothing related to helm2. There should be no need to run the "update-alternatives" command.
2. This is what CaaSP documents: https://github.com/SUSE/doc-caasp/blob/53724eeffb7d3cbd27876d3c8114a0de244b37db/adoc/admin-software-installation.adoc#installing-helm

Thoughts @ml8mr @mgfritch ?

**Comment by mgfritch** [comment]
yeah I agree, `update-alternatives` adds more steps that are not related to rook.

Maybe we can simply reference the CaaSP doc for additional details on using `helm` and keep the rook doc scope to the `rook-ceph` chart as much as possible?

**Comment by asettle** [comment]
Perfect. Will do. PR up soon.
