### ISSUE TITLE
[doc] 1.5.6.2  Enable the rbd-mirror Daemon - Add example placement spec

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-ses#642]
### Type of report
   - [X] bug

### Source Document
1.5.6.2  Enable the <code class="systemitem">rbd-mirror</code> Daemon:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#rbd-mirror-daemon-enable

### Summary
We need an example placement specification as at this point we have not enabled the daemon

**Comment by tbazant** [comment]
reopening, like granularity :-)

**Comment by asettle** [comment]
Related: https://bugzilla.suse.com/show_bug.cgi?id=1177308
