### ISSUE TITLE
Introduce new entities for RBD mirroring sections

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#643]
**Link To Section**
https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#ceph-rbd-mirror

**Summary**
Because RBD mirroring uses 'remote' and 'local' host, it is better to use new entities - for example `cephadm@local >` and `cephadm@remote >` - to distinguish between hosts

**Comment by dthpulse** [comment]
actually my fault, once admin has keyring and config file of remote cluster on local he can issue the commands from from local. That means doc is fine.
