### ISSUE TITLE
[doc] 1.5.6  RBD Mirroring

### ISSUE THREAD

**Issue by dthpulse** [SUSE/doc-ses#646]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
1.5.6  RBD Mirroring:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#dash-rbd-mirror

### Summary

Missing instructions to copy _ceph.conf_ and _keyring_ from primary to secondary cluster.

So that in example that is used in doc (these commands are run from secondary node)

```
cephadm@secondary > rbd --cluster primary mirror pool enable image-pool image
cephadm@secondary > rbd --cluster secondary mirror pool enable image-pool image
```

so on secondary it should looks like 

```
/etc/ceph/primary.conf
/etc/ceph/primary.client.admin.keyring
/etc/ceph/secondary.conf
/etc/ceph/secondary.client.admin.keyring
```

**Comment by asettle** [comment]
So, my understanding is that one way is to manually peer the cluster: https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#rbd-mirror-peer-bootstrap The resulting keyring should be copied to the other cluster’s rbd-mirror daemon hosts. Like so:

`rbd mirror pool peer add {pool-name} {client-name}@{cluster-name}`

Otherwise, the peer cluster’s monitor and/or client key can be securely stored within the local Ceph monitor config-key store. For example:

```$ cat <<EOF > remote-key-file
AQAeuZdbMMoBChAAcj++/XUxNOLFaWdtTREEsw==
EOF
$ rbd --cluster site-a mirror pool peer add image-pool client.rbd-mirror-peer@site-b --remote-mon-host 192.168.1.1,192.168.1.2 --remote-key-file remote-key-file
$ rbd --cluster site-a mirror pool info image-pool --all
Mode: pool
Peers:
  UUID                                 NAME   CLIENT                 MON_HOST                KEY
  587b08db-3d33-4f32-8af8-421e77abb081 site-b client.rbd-mirror-peer 192.168.1.1,192.168.1.2 AQAeuZdbMMoBChAAcj++/XUxNOLFaWdtTREEsw==```

Do you want to test those, @dthpulse ?

**Comment by asettle** [comment]
@dthpulse have you tested either of those options? If not, please do. Preferably the last option, and I will document which works best.

Thanks!

**Comment by dthpulse** [comment]
> So, my understanding is that one way is to manually peer the cluster: https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#rbd-mirror-peer-bootstrap The resulting keyring should be copied to the other cluster’s rbd-mirror daemon hosts. Like so:
> 
> `rbd mirror pool peer add {pool-name} {client-name}@{cluster-name}`
> 
> Otherwise, the peer cluster’s monitor and/or client key can be securely stored within the local Ceph monitor config-key store. For example:
> 
> ```
> AQAeuZdbMMoBChAAcj++/XUxNOLFaWdtTREEsw==
> EOF
> $ rbd --cluster site-a mirror pool peer add image-pool client.rbd-mirror-peer@site-b --remote-mon-host 192.168.1.1,192.168.1.2 --remote-key-file remote-key-file
> $ rbd --cluster site-a mirror pool info image-pool --all
> Mode: pool
> Peers:
>   UUID                                 NAME   CLIENT                 MON_HOST                KEY
>   587b08db-3d33-4f32-8af8-421e77abb081 site-b client.rbd-mirror-peer 192.168.1.1,192.168.1.2 AQAeuZdbMMoBChAAcj++/XUxNOLFaWdtTREEsw== ```
> ```

this part you're mentioning here is documented and it's clear and working.

But this bug is about something different. It's already mentioned in documentation that both clusters needs to have an access to each other. It's good to give an example. So to continue with more detail on what I wrote first it should looks like:

```
cephadm@secondary > cp /etc/ceph/ceph.conf /etc/ceph/primary.conf
cephadm@secondary > cp /etc/ceph/ceph.admin.client.keyring /etc/ceph/primary.client.admin.keyring
cephadm@secondary > scp primary:/etc/ceph/ceph.conf /etc/ceph/secondary.conf
cephadm@secondary > scp primary:/etc/ceph/ceph.client.admin.keyring /etc/ceph/secondary.client.admin.keyring
```

**Comment by tbazant** [comment]
still waiting for PR merge
