### ISSUE TITLE
How are the schema images produced?

### ISSUE THREAD

**Issue by vmoutoussamy** [SUSE/doc-ses#647]
**Link To Section**
https://documentation.suse.com/ses/6/single-html/ses-deployment/#id-1.4.2.10

**Summary**
Might be interesting to explain how you produce the schema images in the doc, which tool are you using?

**Comment by asettle** [comment]
@vmoutoussamy - this is particularly out of scope for this repo. @sknorr where should such a request go? DAPs?

**Comment by sknorr** [comment]
Well, it's content from this repo, so arguably in scope. We do have intro content in the [doc-kit repo](https://github.com/openSUSE/doc-kit), too though. But that is not used here, otherwise the section would not exist in this document at all.

I always figured most of our customers would rather see a shorter preface than learn what software we use for making things -- if I want to learn about what people do to create their PDFs, I usually just go to the PDF viewers properties window (and close it in disappointment when it says Microsoft Word). This solution of course does not work for finding out what diagrams are made with.

(Also, Alex, that spelling of DAPS is _triggering_ me. ^^)

**Comment by asettle** [comment]
> Well, it's content from this repo, so arguably in scope. We do have intro content in the [doc-kit repo](https://github.com/openSUSE/doc-kit), too though. But that is not used here, otherwise the section would not exist in this document at all.
> 
Sure. @tbazant  thoughts?

> I always figured most of our customers would rather see a shorter preface than learn what software we use for making things -- if I want to learn about what people do to create their PDFs, I usually just go to the PDF viewers properties window (and close it in disappointment when it says Microsoft Word). This solution of course does not work for finding out what diagrams are made with.
> 

I'd agree with this, tbh. 

> In addition, the content is also often false--the only documents we run through XEP these days are the Arabic ones. Everything else always goes through FOP.

Can be fixed. 

> 
> (Also, Alex, that spelling of DAPS is _triggering_ me. ^^)

Fixed :P

**Comment by vmoutoussamy** [comment]
> I always figured most of our customers would rather see a shorter preface than learn what software we use for making things -- if I want to learn about what people do to create their PDFs, I usually just go to the PDF viewers properties window (and close it in disappointment when it says Microsoft Word). This solution of course does not work for finding out what diagrams are made with.

I agree, please checkout https://bugzilla.suse.com/show_bug.cgi?id=1176438 - Move "About this guide" section at the end of the documentation.

Still I created this issue here because a pre-sales asked me how you guys produce the schema. So it's useful to know for our colleagues and maybe customers/partners.

**Comment by sknorr** [comment]
Depends on the diagram, but usually either LibreOffice or Dia (in those cases, where a ODG or DIA file is available in the repo). In some cases, Inkscape (when there is only a SVG file available).

**Comment by vmoutoussamy** [comment]
> Depends on the diagram, but usually either LibreOffice or Dia (in those cases, where a ODG or DIA file is available in the repo). In some cases, Inkscape (when there is only a SVG file available).

thanks! forwarded to pre-sale guy !

**Comment by asettle** [comment]
@vmoutoussamy do you require anything else here? Otherwise, this can probably be closed (or left open for a rainy day?)

**Comment by vmoutoussamy** [comment]
I think it would be great "to let this opened for a rainy day". I remember seeing a customer showing us their internal documentation that was trying to mimic ours, so in that regard giving them the opportunity to learn really briefly how we produce images/schemas, would be a nice addition and allow them to produce schema similar to our "style".

**Comment by tbazant** [comment]
interesting thread, will apply doc-kit soon, closing as there's nothing to be done IMHO
