### ISSUE TITLE
[doc] Part&nbsp;I  Introducing SUSE Enterprise Storage (SES) 

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#648]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
Part&nbsp;I  Introducing SUSE Enterprise Storage (SES) :

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#part-ses

### Summary

This sentence is missing something (a `)` ?):
```
The cluster scales up well to thousands of servers (later on referred…

```

**Comment by toabctl** [comment]
Oh. This is just a part of the whole section. So I need to click on the link (https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#cha-storage-about ) to get to the whole text.
A bit confusing imo...

**Comment by asettle** [comment]
@toabctl these are simply introductory paragraphs that are generated from grabbing the text that's in the actual section. They are not designed by us. @tbazant could you think of another way to display these? Otherwise, this is displaying exactly how we intend it to and it's not a bug.

**Comment by toabctl** [comment]
Feel free to close it then. Thanks!

**Comment by asettle** [comment]
No worries, thanks @toabctl :)
