### ISSUE TITLE
[doc] 1.5  Additional Information - Link should be for octopus, not master

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#649]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
1.5  Additional Information:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#storage-moreinfo

### Summary
There is a link to https://docs.ceph.com/en/master/ , but given that SES7 is based on Octopus, should that link be https://docs.ceph.com/en/octopus/ ?

**Comment by asettle** [comment]
Fixed, thanks: https://github.com/SUSE/doc-ses/commit/c3b1695c82910dbc27ec7f67297d15e823812b06
