### ISSUE TITLE
[doc] 2.1.1  Network Recommendations - typo "Bonding two or mor network"

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#650]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
2.1.1  Network Recommendations:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#ceph-install-ceph-deploy-network

### Summary
There is a missing `e` in `more`: `Bonding two or mor network`

**Comment by asettle** [comment]
Fixed, thanks: https://github.com/SUSE/doc-ses/commit/a8e9caed7f36ec52579899fdbf9bc6d9ce2f0580
