### ISSUE TITLE
[doc] 2.3.3  Configuring Multipath - Link to multipath SLES docs is for 12SP4

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#651]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
2.3.3  Configuring Multipath:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deployment-hw-multipath

### Summary
The link to the SLES docs is for SLE12SP4 but we are using SLE15SP2 . So the link should be https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-multipath.html#sec-multipath-lvm

**Comment by asettle** [comment]
Fixed, thanks: https://github.com/SUSE/doc-ses/commit/9c455ec5470ef98563e06b0cb517a0c89d0017f8
