### ISSUE TITLE
[doc] 2.4.3  Recommended Size for the BlueStore's WAL and DB Device - DEAD LINK

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#652]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
2.4.3  Recommended Size for the BlueStore's WAL and DB Device:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#rec-waldb-size

### Summary
There is a dead link:

```Find more information about specifying an OSD layout in DEAD LINK.```

**Comment by asettle** [comment]
Fixed, thanks: https://github.com/SUSE/doc-ses/commit/7ee8be69d604a78f1844482ace5cd1b5db5b30b8
