### ISSUE TITLE
[doc] 10.4.1.1  Enable Mirroring on a Pool

### ISSUE THREAD

**Issue by dthpulse** [SUSE/doc-ses#654]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
10.4.1.1  Enable Mirroring on a Pool:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#id-1.4.4.5.10.8.6

### Summary

Again missing deployment steps for rbd-mirror daemon. Otherwise this wouldn't work.

**Comment by asettle** [comment]
We do not need this bug duplicated, thanks Denis: https://bugzilla.suse.com/show_bug.cgi?id=1177308
