### ISSUE TITLE
[doc] 3.2  Building a HA Cluster with the Admin Node - Links to 15SP1 but we use 15SP2 and a  DEAD LINK.

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#655]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
3.2  Building a HA Cluster with the Admin Node:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#admin-ha-cluster

### Summary
There are links to 15SP1:

- https://documentation.suse.com/sles/15-SP1/single-html/SLES-virtualization/#sec-libvirt-inst-virt-install
- https://documentation.suse.com/sle-ha/15-SP1/single-html/SLE-HA-guide/#cha-conf-hawk2
-  DEAD LINK (```...services you need there. Follow the relevant steps in DEAD LINK. At the sam...```

**Comment by asettle** [comment]
Fixed, updated: https://github.com/SUSE/doc-ses/commit/de7e6f134e148c535efd5d9121734b2587225339
