### ISSUE TITLE
[doc] 10.4.1.4  Add Cluster Peer

### ISSUE THREAD

**Issue by dthpulse** [SUSE/doc-ses#656]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
10.4.1.4  Add Cluster Peer:

https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#id-1.4.4.5.10.8.9

### Summary

This wouldn't work as in example the non existing client is used (client.remote, client.local).
We can see the client name by running command on both sites:

```
# ceph auth get-or-create client.rbd-mirror-peer
[client.rbd-mirror-peer]
        key = AQC1WHxf90D2BRAAtdnCgcUIoZhN7GJIMEFtDw==
```

so example should looks like:

```
rbd --cluster local mirror pool peer add POOL_NAME client.rbd-mirror-peer@remote
rbd --cluster remote mirror pool peer add POOL_NAME client.rbd-mirror-peer@local
```

It's described in nice detail in official doc:

https://docs.ceph.com/en/latest/rbd/rbd-mirroring/#add-cluster-peer-manually

**Comment by asettle** [comment]
@dthpulse - I'm going to combine this issue with the larger RBD issue we have: https://github.com/SUSE/doc-ses/issues/346 and track everything there. Please update this bug with more of your findings.

**Comment by tbazant** [comment]
still waiting for PR merge
