### ISSUE TITLE
[doc] 2.1.1.1  Adding a Private Network to a Running Cluster

### ISSUE THREAD

**Issue by swiftgist** [SUSE/doc-ses#658]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
2.1.1.1  Adding a Private Network to a Running Cluster:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#storage-bp-net-private

### Summary
Incorrect command

### Steps To Reproduce
Run the command

### Expected Results
Run without error

### Actual Results
```
# ceph config  osd cluster_network 172.16.22.0/24
no valid command found; 10 closest matches:
config show <who> [<key>]
config show-with-defaults <who>
config set <who> <name> <value> [--force]
config rm <who> <name>
config get <who> [<key>]
config dump
config help <key>
config ls
config assimilate-conf
config log [<num:int>]
Error EINVAL: invalid command
```

### Notes
The correct command has the keyword `set`.

`# ceph config set osd cluster_network 172.16.22.0/24`

**Comment by asettle** [comment]
Fixed, thanks: https://github.com/SUSE/doc-ses/commit/0c549bea87da2e025b2584f97d3fc17b4dca7e52
