### ISSUE TITLE
15.7.3 vs 15.7.2 -> why do we need to run stage 2 in 15.7.3 but not in 15.7.2?

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#660]
**Link To Section**
https://documentation.suse.com/ses/6/html/ses-all/cha-ceph-gw.html#ogw-ssl-simple
https://documentation.suse.com/ses/6/html/ses-all/cha-ceph-gw.html#ogw-ssl-advanced

**Summary**
It is unclear why we have to run stage 2 in the simple but not in the advanced section

**Expected Results**
I believe the stages that need to be executed should be the same in both sections.

**Comment by asettle** [comment]
@swiftgist could you please take a look at this? Thanks!

**Comment by swiftgist** [comment]
It's inconsistent, the advanced section should run Stage 2 as well.

**Comment by asettle** [comment]
Fixed, thanks: https://github.com/SUSE/doc-ses/commit/abbdb4e3dbab626547069ccdd8d54d708bb717f7
