### ISSUE TITLE
[doc] 5.3  Deploying the Ceph Cluster

### ISSUE THREAD

**Issue by soothill** [SUSE/doc-ses#675]
### Type of report
   - [ x ] bug
   - [ ] feature request

### Source Document
5.3  Deploying the Ceph Cluster:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-day1

### Summary
There is no mention of needing to run SUSEConnect to register SES as a product to allow the installation of the Ceph-salt package.

### Steps To Reproduce
zypper install ceph-salt 
This command fails if the system has not been registered through SUSEConnect

**Comment by asettle** [comment]
Hi @soothill - The documentation actively describes the setup here: https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-os before you have started to deploy salt. This documentation links you to the registration documentation: https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-register-sle.html

Let me know if you have any further questions.
