### ISSUE TITLE
SES7 Troubleshooting Guide does not mention "systemd-coredump"

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#678]
**Link To Section**

https://susedoc.github.io/doc-ses/master/single-html/ses-troubleshooting/

**Summary**

In order to get coredumps when containerized daemons (MON, MGR, OSD, NFS-Ganesha, etc.) crash, the package `systemd-coredump` must be installed **on the host** (not inside the container) where the container is running.

It's up to the user to install this.

The package must be installed **BEFORE** the crash happens. Otherwise a coredump will not be collected.

**Comment by smithfarm** [comment]
@denisok Can you check if what I wrote above is correct?

**Comment by denisok** [comment]
and node needs to be rebooted so `systemd-coredump` changes would be applied. Otherwise correct.

**Comment by smithfarm** [comment]
@denisok Should we also say something `ulimit` setting, to prevent truncation of coredumps on machines with lots of RAM?

**Comment by asettle** [comment]
@smithfarm we have to be aware of the barrier to entry here. The user should install, _fine_, but we should be careful not to encourage the user to play around with the core dump settings. I'd be fine with including it as a recommendation (with no instructions), but support should know how to work with the customer to handle this. Keep in mind that processing a core dump happens when the customer cannot resolve the issue themselves, and turns to support. The support tech should initiate the core dump, not the user.

**Comment by smithfarm** [comment]
@denisok Wouldn't it be simpler just to have `ceph-salt` install this RPM on all cluster nodes?

**Comment by smithfarm** [comment]
There is also the option of not documenting coredumps at all - and leave it to support to make sure they are getting collected.

But then it is pretty much assured that the **first** crash (the immediate cause for the customer calling support) will not get any coredump collected. That means we will have to ask the customer to reproduce the crash in order to analyze it.

**Comment by asettle** [comment]
> There is also the option of not documenting coredumps at all - and leave it to support to make sure they are getting collected.

This is what I said in the JIRA issue, to be fair :eyes: 
> 
> But then it is pretty much assured that the **first** crash (the immediate cause for the customer calling support) will not get any coredump collected. That means we will have to ask the customer to reproduce the crash in order to analyze it.

When the customer is deploying, the customer should be advised by a specialist to ensure they have this backup. It's not a end user function.

**Comment by smithfarm** [comment]
OK, I'm fine to just close this.
