### ISSUE TITLE
[doc] 5.3.2.13  Configure the Cluster Network

### ISSUE THREAD

**Issue by dthpulse** [SUSE/doc-ses#680]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
5.3.2.13  Configure the Cluster Network:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-enable-network

### Summary

Cluster network has to be defined under 'osd' not 'global'

```
ceph-salt config /cephadm_bootstrap/ceph_conf add osd
ceph-salt config /cephadm_bootstrap/ceph_conf/osd set cluster_network NETWORK_ADDR
```

**Comment by smithfarm** [comment]
> Cluster network has to be defined under 'osd' not 'global'

@dthpulse What error do you get when it is defined under `global`?

**Comment by dthpulse** [comment]
looking into ceph doc https://docs.ceph.com/en/latest/rados/configuration/network-config-ref/#cluster-network - it's correct.
