### ISSUE TITLE
Document config-key store

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#698]
enhance this chapter https://susedoc.github.io/doc-ses/master/html/ses-admin/cha-ceph-configuration.html and include:
* general information about using `ceph config-key` to store and retrieve saved values for ceph application
* description of config-key store keys for specific application, such as ceph-iscsi in #669

**Comment by tbazant** [comment]
Can you contribute with key for RGW, NFS, RBD, RBD-MIRROR etc if applicable?
@theanalyst @trociny @dthpulse @ddiss @jschmid1 @matthewoliver

**Comment by trociny** [comment]
rbd and  rbd-mirror may use config-key store for peer configuration, but one should use (higher level) `rbd` cli to update this configuration, which is documented in rbd/rbd-mirror documentation. So I think nothing rbd/rbd-mirror specific should be mentioned in this section: users are expected to use `rbd` cli and not low level `ceph config-key` for this.
