### ISSUE TITLE
[doc] 3  Documentation Conventions

### ISSUE THREAD

**Issue by jhhudso** [SUSE/doc-ses#706]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
3  Documentation Conventions:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#id-1.3.2.9

### Summary
Documentation example doesn't match statement.
"Alt, Alt–F1: a key to press or a key combination; keys are shown in uppercase as on a keyboard"
In that example, Alt, Alt-F1 is not shown in uppercase as on keyboard like the statement claims it is. Either change it to ALT, ALT-F1 or alter the statement to match the example.

### Steps To Reproduce
N/A

### Expected Results
N/A

### Actual Results
N/A

**Comment by asettle** [comment]
The documentation statement is designed to clarify the example - @tbazant any thoughts on updating this?

**Comment by asettle** [comment]
Done: https://github.com/SUSE/doc-ses/commit/37ba12c8c542548f3e8f86d66e69254197207327
