### ISSUE TITLE
[doc] 5  Commands and Command Prompts Used in This Guide

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#708]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
5  Commands and Command Prompts Used in This Guide:

https://susedoc.github.io/doc-ses/master/single-html/ses-rook/#id-1.7.2.13

### Summary
Does it make sense to have the `5.1 Salt Related Commands` and `5.2 Ceph Related Commands` in the rook guide? 
When deploying with rook, there is no salt involved. Also `cephadm` is not there afaiu.

Instead, there is the toolbox container

**Comment by asettle** [comment]
Not at all, makes sense :) these are templated beginnings for all guides. I'll create something new
