### ISSUE TITLE
Document deploying services other than OSDs via the Dashboard

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-ses#713]
This functionality has not been merged into Ceph Octopus yet, so it's not part of SES7 so far but it will be. Will update with more information.

**Comment by asettle** [comment]
Related to: SES-1129, SES-859

Upstream backport: https://github.com/ceph/ceph/pull/37456

**Comment by asettle** [comment]
Upstream tracker issue: https://tracker.ceph.com/issues/44831

Basically, we would need to document this "ServiceSpec" and then provide concrete examples on how to deploy specific services.
As the backport PR has not been merged yet, updating the docs probably has no real urgency at this point

**Comment by asettle** [comment]
@LenzGr any update?

**Comment by asettle** [comment]
Removing Lenz and adding @callithea :)

**Comment by callithea** [comment]
> Removing Lenz and adding @callithea :)

Thank you, @asettle :)
I'm still working on the backport, unfortunately there are a lot of differences in octopus compared to the original PR targeting master and I'm still addressing those. I'll post an update as soon as possible!

**Comment by asettle** [comment]
Awesome, thanks @callithea !

**Comment by asettle** [comment]
I can't see us going forward with this update after the recent announcement. Let me know if anything changes, @callithea but closing for now.

**Comment by callithea** [comment]
> I can't see us going forward with this update after the recent announcement. Let me know if anything changes, @callithea but closing for now.

Hi @asettle, unfortunately I got stuck with some dashboard frontend migration issues in my PR and now Volker took over, a new PR has been opened: https://github.com/ceph/ceph/pull/38888
