### ISSUE TITLE
[doc] Part&nbsp;II  Administrating Ceph on SUSE CaaS Platform 

### ISSUE THREAD

**Issue by toabctl** [SUSE/doc-ses#725]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
Part&nbsp;II  Administrating Ceph on SUSE CaaS Platform :

https://susedoc.github.io/doc-ses/master/single-html/ses-rook/#rook-ses-admin

### Summary
`The toolbox is based on CentOS, so more tools of your choosing can be installed with yum`
This is wrong. Our toolbox container is based on SLES

**Comment by asettle** [comment]
This has been fixed previously: 

```7 Ceph Toolbox
The Rook toolbox is a container with common tools used for rook debugging and testing. The toolbox is based on SUSE Linux Enterprise Server, so more tools of your choosing can be installed with zypper.```

I did fix one last mention of yum: https://github.com/SUSE/doc-ses/commit/a08eecc6d849e70cc74993f1a1a2fc761de2ff35

Closing as done :) thanks!
