### ISSUE TITLE
[doc] 5.4.3.3  Deploy Metadata Servers

### ISSUE THREAD

**Issue by mvangool** [SUSE/doc-ses#730]
### Type of report
   - [ ] bug

### Source Document
5.4.3.3  Deploy Metadata Servers:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#deploy-cephadm-day2-service-mds

### Summary
This is about the first paragraph in this section:

"CephFS requires one or more Metadata Server (MDS) services. These are automatically deployed when you create the CephFS. To create a CephFS, first create MDS servers by applying the following specification:"

First we say: These are automatically deployed when you create the CephFS.
Than the very next line we contradict with saying these need to be manually created :  To create a CephFS, first create MDS servers by applying the following specification

### Expected Results
This is confusing.
Are the MDS servers automatically created or do they need to be created manually using the steps as outlined in the docs?

**Comment by LenzGr** [comment]
Looks like we should explain this in more detail in the SES docs. The [upstream docs](https://docs.ceph.com/en/latest/cephadm/install/#deploy-mdss) explain this as follows:
> These are created automatically if the newer `ceph fs volume` interface is used to create a new file system."

**Comment by LenzGr** [comment]
Also see the [FS volumes](https://docs.ceph.com/en/latest/cephfs/fs-volumes/#fs-volumes) documentation:
>  It can also try to create MDSes for the filesystem using the enabled ceph-mgr orchestrator module (see Orchestrator CLI), e.g. rook.

**Comment by smithfarm** [comment]
Just drop the sentence "These are created automatically if the newer ceph fs volume interface is used to create a new file system."

Then it will make sense.

**Comment by tbazant** [comment]
fixed by https://github.com/SUSE/doc-ses/commit/144c9c45dae059b6c4552f7390cd4e82a3c51ea1
