### ISSUE TITLE
[doc] Part IV Upgrading from Previous Releases has bizarre page break

### ISSUE THREAD

**Issue by tserong** [SUSE/doc-ses#731]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
Part IV  Upgrading from Previous Releases :

https://documentation.suse.com/ses/7/html/ses-all/ses-upgrade.html#

### Summary
When viewed as multi-page HTML, the text says "This chapter introduces steps to upgrade SUSE Enterprise Storage 6 to version 7. Upgrading from 6 to 7 means the following:", and then... nothing. So somehow there's a page break being injected before the list which appears properly on the following page (https://documentation.suse.com/ses/7/html/ses-all/cha-ceph-upgrade.html#).
Here's a screenshot, in case my description isn't clear:
![ses7-upgrade-weird-section-break](https://user-images.githubusercontent.com/754700/97669669-bf51cf80-1ad8-11eb-83d0-a3705bf828b9.png)

I'd expect either that sentence *and* the list to appear on the first page, or, to have the page just be completely blank.

**Comment by tbazant** [comment]
hopefully fixed by https://github.com/SUSE/doc-ses/commit/ca7cb740b97bb2ddeb80cfb1738719c429b00f00
