### ISSUE TITLE
[doc] 1.5  RADOS Block Device (RBD)

### ISSUE THREAD

**Issue by yule-sun** [SUSE/doc-ses#739]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
1.5  RADOS Block Device (RBD):

https://documentation.suse.com/ses/7/html/ses-all/windows-ses.html#rados-block-device

### Notes

I think this should not be a bug, but I don’t know how to solve this problem.
After I installed SES4Win.msi and configured the ceph.conf and keyring files in the C:\ProgramData\Ceph directory, I ran the rbd command and got an error like this.
![image](https://user-images.githubusercontent.com/37107125/99022523-dba44080-259d-11eb-8c7e-76a83244c01e.png)

The configuration of ceph.conf and keyring is like this, I don't know what went wrong, I hope to get your help, thank you very much.
![image](https://user-images.githubusercontent.com/37107125/99022361-89fbb600-259d-11eb-9654-5a609e2509c7.png)
![image](https://user-images.githubusercontent.com/37107125/99022415-a7308480-259d-11eb-9122-8814f6d49826.png)

**Comment by ml8mr** [comment]
That is very strange...  I wonder if there is a problem with some character in your key string. Can you replace the key in your keyring file with the one from the documentation:

  key = ADCyl77eBBAAABDDjX72tAljOwv04m121v/7yA==

I realize you won't be able to actually connect to the cluster using that key, but it would be interesting to see if that resolves the malformed input problem. Another possibility could be hidden characters in the file. Did you copy the keyring directly from one of your Ceph admin nodes?

We should also track this through bugzilla.suse.com. If there is a bug, we should fix it before the next rev of the product (which should happen soon).

**Comment by yule-sun** [comment]
Thank you sir,Thank you very much for your kind help.
I updated the key value in the keyring file, but still got the same error.
![image](https://user-images.githubusercontent.com/37107125/99026728-9a645e80-25a6-11eb-9d32-5af5f4aee5f6.png)

And this key is copied directly from the ceph mon node.
![image](https://user-images.githubusercontent.com/37107125/99026804-cd0e5700-25a6-11eb-8537-b39c64b9b021.png)

Are there any requirements on the format or permissions of the keyring file, for example, if each line starts with 5 spaces or a tab？ I modified the file grant everyone can read and execute the keyring file.
And my ceph cluster is enabled with cephx authentication, will this affect it?

Here is the ceph.conf on my ceph_mon node ,cloud help me, thank you very much~
![image](https://user-images.githubusercontent.com/37107125/99027391-10b59080-25a8-11eb-88a4-2a329c966ddc.png)

**Comment by ml8mr** [comment]
I may have been able to duplicate your problem. The keyring file must have a hard return after the last line - so the final line of the file is just an empty line. Can you try adding that and see if it fixes the problem? If so, this is a bug that we'll get fixed (and documented).

For the record, there shouldn't be any space or tab requirements in the configuration files. However, must be uniformly indented.

**Comment by yule-sun** [comment]
Yes,Yes, sir. It works now. Thank you very much.
I add a empty line at the end of the keyring file , make sure there is a blank line at the end of it, and it works now.
![image](https://user-images.githubusercontent.com/37107125/99033437-d521c300-25b5-11eb-933e-6ac426ee4a84.png)

**Comment by yule-sun** [comment]
Sorry sir , I have to trouble you again.
I can connect the ceph cluster ,and create a rbd vlume ,but when i'm use the rbd-wnbd to map the volume ,i got an error like this.
![image](https://user-images.githubusercontent.com/37107125/99035331-67c46100-25ba-11eb-9413-6af73c620a47.png)

**Comment by asettle** [comment]
Thanks all. Closing as complete :)
