### ISSUE TITLE
[doc] 5.3.2.11  Configure Container Registry

### ISSUE THREAD

**Issue by dirkmueller** [SUSE/doc-ses#740]
### Type of report
   - [ ] bug
   - [x] feature request

### Source Document
5.3.2.11  Configure Container Registry:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#deploy-cephadm-configure-registry

### Summary
This section already covers a couple of tips on how to setup a registry mirror. all of them are great. This issue is about adding *another* option  called SUSE Private Registry, which we documented in the suse best practices section: 

https://documentation.suse.com/sbp/all/single-html/SBP-Private-Registry/

**Comment by asettle** [comment]
@dirkmueller rather than documenting it in a second place, would a cross-reference be a suitable alternative? You know, something like, "For information on how to setup another option called the SUSE Private Registry, see <blah> for more details."

**Comment by dirkmueller** [comment]
yes, similar to how the tip "Registry Cache", which reads

> To avoid re-syncing the local registry when new updated containers appear, you can configure a registry cache. Find more information about containers and air-gapped scenarios in https://documentation.suse.com/suse-caasp/4.5/single-html/caasp-airgap/.

we could add a similar blob of text documenting suse private registry.
