### ISSUE TITLE
[doc] 5.3.2.11  Configure Container Registry

### ISSUE THREAD

**Issue by rhafer** [SUSE/doc-ses#741]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
5.3.2.11  Configure Container Registry:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#deploy-cephadm-configure-registry

### Summary

The command given to start the registry is a bit missleading I think:

`podman run -d --restart=always --net=host --name registry -p 5000:5000 registry:2`

When using host networking (`--net host`) I think the port forwarding (`-p 5000:5000`) is kind of redundant. I'd suggest to not use host networking (i.e. remove the `--net host` ) to provide better isolation for the container.

**Comment by asettle** [comment]
@smithfarm what do you think?

**Comment by smithfarm** [comment]
More a question for @mgfritch and/or @ricardoasmarques ?

**Comment by smithfarm** [comment]
Ah, I see @sebastian-philipp is back - he's another candidate to review this.

**Comment by sebastian-philipp** [comment]
relates to https://bugzilla.suse.com/show_bug.cgi?id=1177210

**Comment by sebastian-philipp** [comment]
#799

**Comment by smithfarm** [comment]
> @smithfarm what do you think?

I think that, in general, the SES7 development effort did not foresee that nearly every user would decide to use a local container registry.

**Comment by smithfarm** [comment]
I'm still not convinced that administration of container registries (local or remote) is in-scope for the SES product/project.

**Comment by sebastian-philipp** [comment]
> I'm still not convinced that administration of container registries (local or remote) is in-scope for the SES product/project.

I think it is. I think we have to move this uppstream

**Comment by asettle** [comment]
I am going to close this issue. We only need to track comments in _one_ place and this is not a documentation issue until the technical issues have been resolved. I am writing a comment in the BZ ticket.
