### ISSUE TITLE
Verify SSL needs to be disabled when configuring the RGW with a self signed certificate

### ISSUE THREAD

**Issue by lezare** [SUSE/doc-ses#744]
**Link To Section**
https://documentation.suse.com/ses/6/single-html/ses-admin/#ogw-ssl-simple

**Summary**
If the RGW is configured to use SSL with a self signed certificate as per the above documentation, then it is also required to disable SSL verififcation else dashboard access will fail with a non descriptive error message simply stating:

`Sorry, we could not find what you were looking for`

**Steps To Reproduce**
Follow the documentation above to enable SSL access for the RGW.

**Expected Results**
Dashboard access should not fail after taking the above steps.

**Notes**
See also: https://bugzilla.suse.com/show_bug.cgi?id=1178355#c7
To resolve this, the following step needs to be added to the documentation:

Finally run:

`ceph dashboard set-rgw-api-ssl-verify False`

**Comment by asettle** [comment]
@theanalyst could you please verify? :) thank you!

**Comment by theanalyst** [comment]
Yeah this is true, unless we have installed the self signed certificate that the dashboard needs in the dashboard node

**Comment by asettle** [comment]
@theanalyst same for SES 6 and 7?
