### ISSUE TITLE
[doc] 3.3  Removing Nodes

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/doc-ses#745]
### Type of report
   - [X] bug
   - [ ] feature request

### Source Document
3.3  Removing Nodes:

https://susedoc.github.io/doc-ses/master/html/ses-admin/storage-salt-cluster.html#salt-node-removing

### Summary

From:

https://tracker.ceph.com/issues/48260
https://bugzilla.suse.com/show_bug.cgi?id=1176265

After removing all OSDs on a single host, the user has to manually remove the "host" from the crush map.

**Comment by asettle** [comment]
@sebastian-philipp could you please provide accurate steps on how to do so.

**Comment by sebastian-philipp** [comment]
I'm sure we're talking about https://docs.ceph.com/en/latest/rados/operations/crush-map/#remove-a-bucket here. @jecluis correct?

**Comment by smithfarm** [comment]
> I'm sure we're talking about https://docs.ceph.com/en/latest/rados/operations/crush-map/#remove-a-bucket here. 

Correct. In other words:

1. find name of bucket to be removed
2. `ceph osd crush remove {bucket-name}`

That's the essence of https://github.com/SUSE/DeepSea/pull/1297 which fixed the issue in DeepSea.
