### ISSUE TITLE
[doc] 3.9  Removing an Entire Ceph Cluster

### ISSUE THREAD

**Issue by votdev** [SUSE/doc-ses#752]
### Type of report
   - [ ] bug
   - [ ] feature request
   - [x] discussion

### Source Document
3.9  Removing an Entire Ceph Cluster:

https://documentation.suse.com/ses/7/html/ses-all/storage-salt-cluster.html#ceph-cluster-purge

### Summary
I think we need to discuss the word `runner` in the sentence `The ceph-salt purge runner removes the entire Ceph cluster.` and the use of this in the whole documentation which is related to `ceph-salt`.

Is it possible that this is a holdover from SES6 and DeepSea where `runner` is correct and part of the SaltStack terminology. In SES7 `ceph-salt` is a standalone CLI application where `command` makes more sense.

**Comment by asettle** [comment]
@votdev Thanks for bringing this up. We intend to clean-up and clarify language changes from SES 6 -> 7 after this doc day. This is a good example. I'll make sure to grep through the guide.

**Comment by ricardoasmarques** [comment]
@votdev you are rigth, it should be `command` instead of `runner`.
