### ISSUE TITLE
[doc] 6.1.2  Deploying Using Custom or Local Images

### ISSUE THREAD

**Issue by l-mb** [SUSE/doc-ses#753]
### Type of report
   - [X] bug

### Source Document
6.1.2  Deploying Using Custom or Local Images:

https://documentation.suse.com/ses/7/single-html/ses-admin/#monitoring-custom-images

### Summary
The documentation specifies the actual version strings for the images as examples. I expect these will change over the course of SES 7.

Should we drop that here and instead provide a command that lists the current defaults and overrides, if any (including example output)?

**Comment by asettle** [comment]
Previously, we've always listed the actual version strings. Do we have a command? If so, I'm unaware of it and would appreciate the command and example output to replace it with.

**Comment by asettle** [comment]
@tbazant  thoughts?

**Comment by asettle** [comment]
@p-se could you please take a look at this?

**Comment by p-se** [comment]
That's a great idea I also have already thought about. However, there's no such command at the moment.

**Comment by asettle** [comment]
If there's no such command at the moment, closing as a WONTFIX.

Thanks.
