### ISSUE TITLE
[doc] 3.10  Distributing a Program Temporary Fix (PTF)

### ISSUE THREAD

**Issue by l-mb** [SUSE/doc-ses#754]
### Type of report
   - [X] Feature request

### Source Document
3.10  Distributing a Program Temporary Fix (PTF):

https://documentation.suse.com/ses/7/single-html/ses-troubleshooting/#bp-troubleshooting-ptfs

### Summary

We describe how to redeploy a given daemon with a specific container image as a PTF. The only section that describes how to set the global image that I could find is actually within our upgrade process (https://documentation.suse.com/ses/7/single-html/ses-deployment/#upgrade-cephsalt).

We need to describe how this will interact - will the next ceph-salt or orch upgrade run overwrite the PTF, or is it sticky? If the latter, how to find/list overridden daemons easily and how to reset them to the default?

What values are acceptable for `daemon`?

@sebastian-philipp ?

**Comment by asettle** [comment]
@sebastian-philipp

**Comment by sebastian-philipp** [comment]
me?

**Comment by asettle** [comment]
@sebastian-philipp see the question from Lars in the description

**Comment by sebastian-philipp** [comment]
> We need to describe how this will interact - will the next ceph-salt or orch upgrade run overwrite the PTF, or is it sticky? 

* `ceph-salt update` will not touch those services
* `ceph orch upgrade ...` will upgrade those manually deployed daemons. 


> If the latter, how to find/list overridden daemons easily and how to reset them to the default?

`ceph orch ps` shows all container images. 

> What values are acceptable for `daemon`?

`ceph orch ps` shows all daemons known to ceph.

**Comment by asettle** [comment]
Then I don't think anything needs to be changed, thanks @sebastian-philipp - is this suitable, @l-mb ?

**Comment by l-mb** [comment]
So we need to document that a customer would need to either undo the changes, or run `ceph orch upgrade` on them explicitly for `ceph-salt update` to complete entirely?
We should probably at least document that `ceph-salt update` will not overwrite such manual changes.
