### ISSUE TITLE
[doc] Part&nbsp;II  Deploying Ceph Cluster 

### ISSUE THREAD

**Issue by jan--f** [SUSE/doc-ses#760]
We only ship one way of deploying the cluster I assume? Probably left over from earlier.    

 ### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
Part&nbsp;II  Deploying Ceph Cluster :

https://documentation.suse.com/ses/7/html/ses-all/ses-deployment.html#

**Comment by asettle** [comment]
@jan--f I think this is about to become two, based on whether or not https://github.com/ceph/ceph/pull/37456 merges. But I'll keep this open, we should have removed that regardless (and should do so, until otherwise)

**Comment by asettle** [comment]
The complete sentence says more:

```Since SUSE Enterprise Storage 7, Ceph services are deployed as containers instead of packages. There are two ways to deploy the cluster:
- By using cephadm. Find more details in Chapter 5, Deploying with cephadm.
- On top of a SUSE CaaS Platform cluster. Find more details in Chapter 1, Quick Start.```

I'll clarify this, however.
