### ISSUE TITLE
[doc] 15.7.1  Supported Object Gateway Operations

### ISSUE THREAD

**Issue by supriti** [SUSE/doc-ses#764]
https://documentation.suse.com/ses/7/single-html/ses-admin/#ganesha-rgw-supported-operations

For ses7, we support only nfs-ganesha with cephfs. There is no support for deployment of nfs-ganesha and rgw (object gateway). AFAIK there is work upstream to have this support. It may land later. Need to verify with Michael Fritch about the final decision on this.

**Comment by asettle** [comment]
Good catch, we removed most mentions, but clearly missed this.

**Comment by asettle** [comment]
Looks like we missed it in a few places: https://documentation.suse.com/ses/7/single-html/ses-admin/#ceph-nfsganesha-customrole

I'll grep through
