### ISSUE TITLE
SES7: 1  Available Documentation does not explain how to install the documentation

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#766]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
1  Available Documentation:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#id-1.3.2.4

### Summary

This section of the Deployment Guide says: "In addition, the product documentation is usually available in your installed system under /usr/share/doc/manual."

I find this statement ambiguous - especially the word "usually". What does that mean? Instead of "are usually installed" could we say: "Once one or more product documentation RPMs have been installed in your system, the documentation it contains will be available under /usr/share/doc/manual"?

Even that seems lacking in substance, however - almost as if we are saying between the lines: "Go and find out for yourself!" Can we link to a discussion of what the product documention RPMs are (their names and what they contain)?

Imagine I'm a reader who wants to install the product documentation in their system and then read it there. How do I proceed?

**Comment by asettle** [comment]
@tbazant would you be able to look after this update? :)
