### ISSUE TITLE
[doc] 15.2  Create an NFS Service

### ISSUE THREAD

**Issue by supriti** [SUSE/doc-ses#770]
### Source Document
15.2  Create an NFS Service:

https://documentation.suse.com/ses/7/single-html/ses-admin/#ceph-nfsganesha-nfservice

I think this section should be mentioned at start of NFS-Ganesha section (after short introduction about NFS-Ganesha). One needs to be sure that nfs-ganesha is already deployed before trying to do any of the configurations.

**Comment by mgfritch** [comment]
https://github.com/SUSE/doc-ses/pull/785
