### ISSUE TITLE
[doc] 4.3.1  An OSD Will Not Start

### ISSUE THREAD

**Issue by l-mb** [SUSE/doc-ses#771]
### Type of report
   - [X] bug
   - [X] feature request

### Source Document
4.3.1  An OSD Will Not Start:

https://documentation.suse.com/ses/7/single-html/ses-troubleshooting/#troubleshooting-osd-start

### Summary
This documents how to adjust /etc/sysctl.conf, however we do deploy `/etc/sysctl.d/90-ceph-osd.conf` that we should modify.

However, we also have https://github.com/SUSE/ceph/blob/ses7/etc/sysctl/CMakeLists.txt which suggests to me we already include exactly this setting.

Maybe the entire section can just be dropped in the docs?

Further, I'm a bit confused what "_Kernel Version: Identify the kernel version and distribution you are using. Ceph uses some third party tools by default, which may be buggy or may conflict with certain distributions or kernel versions._" is asking one of our customers to do.

As for segmentation faults, these should result in a coredump and I think we should instead provide guidance on how to check if they've been generated and how to submit them to SUSE? Perhaps via supportconfig?

@smithfarm @jan--f, thoughts? @tserong?

**Comment by asettle** [comment]
@l-mb regarding coredump, this is completely out of scope for a traditional user, and should only really be conducted by support staff. We noted this in the relevant JIRA: https://jira.suse.com/browse/SES-1340 (in summary, by the time you are required to perform a core dump, you should be on the phone to support and they can take you through this action, this is too indepth). My comment on that is here: https://jira.suse.com/browse/SES-1340?focusedCommentId=1029608&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1029608

For kernel stuff, @luis-henrix could you take a look?

**Comment by luis-henrix** [comment]
Yeah, that text seems to come from upstream docs (troubleshooting-osd.rst) but it doesn't really make sense here.  AFAIK only clients (CephFS, rbd) accessing the cluster *may* use other distros; OSDs (or any other ceph daemons) are supposed to be deployed in well-known distributions running well-know kernel versions ;-)

So my opinion is to drop that bullet point.

**Comment by smithfarm** [comment]
If coredumps are out of scope for a traditional user, then isn't tweaking sysctl settings also out of scope?

Also, `/etc/sysctl.d/90-ceph-osd.conf` is owned by the ceph-osd package, which means it is installed only inside the OSD container. Do sysctl settings done inside a container have any effect on the kernel? I would expect the answer to be "no", but I've encountered stranger things than that in the world of Linux...

**Comment by smithfarm** [comment]
I see I already opened an upstream issue for this: https://tracker.ceph.com/issues/47873

This issue title is: "/usr/lib/sysctl.d/90-ceph-osd.conf getting installed in container, rendering it ineffective"

**Comment by smithfarm** [comment]
I would support either (a) dropping the entire section or (b) reducing it to a statement that if an OSD refuses to start and you can't figure out why that is, generate a supportconfig and open a support ticket.

**Comment by smithfarm** [comment]
Another idea would be to point the user to the section that explains how to display the log of a particular OSD, and how to "turn the logging up (if it isn't already)" (as the third bullet point currently says, rather unhelpfully).

**Comment by asettle** [comment]
> If coredumps are out of scope for a traditional user, then isn't tweaking sysctl settings also out of scope?

I'd say so, tbh.

> 
> Also, `/etc/sysctl.d/90-ceph-osd.conf` is owned by the ceph-osd package, which means it is installed only inside the OSD container. Do sysctl settings done inside a container have any effect on the kernel? I would expect the answer to be "no", but I've encountered stranger things than that in the world of Linux...
