### ISSUE TITLE
[doc] 10.2  Mounting and Unmounting

### ISSUE THREAD

**Issue by trociny** [SUSE/doc-ses#777]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
10.2  Mounting and Unmounting:

https://documentation.suse.com/ses/7/single-html/ses-admin/#storage-bp-integration-mount-rbd

### Summary
Can we replace all usage of `rbd map` to `rbd device map`, `rbd unmap` to `rbd device unmap`, and `rbd showmapped` to `rbd device list`? Although the old commands are still working, the new ones are preferred to use. See e.g. the upstream doc [1].

[1] https://docs.ceph.com/en/octopus/rbd/rbd-ko/

**Comment by asettle** [comment]
@trociny should `rbd list` be `rbd device list` also?

**Comment by asettle** [comment]
Also, would `rbd resize` follow the same conventions?
