### ISSUE TITLE
[doc] 10.4.4  <code class="systemitem">rbd-mirror</code> Daemon

### ISSUE THREAD

**Issue by trociny** [SUSE/doc-ses#779]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
10.4.4  <code class="systemitem">rbd-mirror</code> Daemon:

https://documentation.suse.com/ses/7/single-html/ses-admin/#rbd-mirror-daemon

### Summary
This section is outdated. It describes a way to deploy rbd-mirror daemon that is not used in SES7. The correct way is described in SES7 deployment guide [1]. So we should either entirely remove this section or remove the outdated contents and just add the reference to the deployment guide.

[1] https://documentation.suse.com/ses/7/single-html/ses-deployment/#deploy-cephadm-day2-service-rbdmirror

**Comment by asettle** [comment]
@trociny I'll remove this. It doesn't suit our structured format.
