### ISSUE TITLE
[doc] 5.2  Deploy Salt

### ISSUE THREAD

**Issue by holgis** [SUSE/doc-ses#787]
### Type of report
   - [X] bug
   - [ ] feature request

### Source Document
5.2  Deploy Salt:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#deploy-salt

### Summary
Default entry in /etc/salt/master is different as described:
do states:
_Edit /etc/salt/master and uncomment the following line:_ 
`#log_level_logfile: WARN`
while my /etc/salt/master file contains:
`#log_level: warning`

### Steps To Reproduce
Open file /etc/salt/master on admin node

### Expected Results
Check which is the correct value for `log_level:` and update doc or create bug report for salt package

### Actual Results
I dod not test, but maybe `WARN` will not be interpreted as the same value as `warning`

### Notes
-

**Comment by asettle** [comment]
@smithfarm I believe we went through this and WARN was fine, any thoughts?

**Comment by smithfarm** [comment]
@asettle @ricardoasmarques is the expert here, but I do believe the doc should say:

"Edit /etc/salt/master and uncomment the following line:

```
#log_level_logfile: warning
```
"

This `#log_level_logfile: warning` is what I see in my ses7 deployment (created using `sesdev`). I assume @holgis 's deployment was done using Autoyast, which might explain the difference. 

@holgis Is there really no `#log_level_logfile:` line in your /etc/salt/master? 

If not, can you post here the output of `rpm -V salt-master`? If it shows the file has been modified, perhaps check how Autoyast is modifying it in your case?

**Comment by smithfarm** [comment]
@asettle In short, I believe the doc should be corrected to:

```
#log_level_logfile: warning
```

But please let @ricardoasmarques confirm before taking any action.

**Comment by smithfarm** [comment]
@holgis It's a little confusing, because the file /etc/salt/master has two very similar settings:

1. `log_level`
2. `log_level_logfile`

Easy to confuse the two. Maybe the documentation should mention this, @asettle?

**Comment by asettle** [comment]
@smithfarm definitely, good idea. I'll wait till @ricardoasmarques confirms, and we'll make the changes. Do we need to document anything regarding `log_level` or just changing `log_level_logfile`?

**Comment by smithfarm** [comment]
@asettle I was thinking something along the lines of a "Tip" or "Information" box saying:

"The /etc/salt/master file contains two similar configuration parameters - `log_level` and `log_level_logfile` - make sure you are changing the correct one."

**Comment by holgis** [comment]
> @holgis Is there really no `#log_level_logfile:` line in your /etc/salt/master?
> 
> If not, can you post here the output of `rpm -V salt-master`? If it shows the file has been modified, perhaps check how Autoyast is modifying it in your case?

There is, here is what I stated initially:
```
[...]
while my /etc/salt/master file contains:
#log_level: warning

```

**Comment by smithfarm** [comment]
@holgis I guess what I'm trying to say is: the `log_level` setting is not important. What is important is the `log_level_logfile` setting.

**Comment by holgis** [comment]
OK, also the `log_level_logfile` is around and not using `WARN` but `warning` as default entry:
`#log_level_logfile: warning
`

**Comment by smithfarm** [comment]
`log_level` controls which log messages will be displayed on the screen
`log_level_logfile` controls which log messages will be written to `/var/log/salt/master`

**Comment by holgis** [comment]
Sorry, now I realized that I just copied the wrong line to the issue in the beginning. The but report is corruct but my quote should not be
`#log_level: warning
`but
`#log_level_logfile: warning `

**Comment by smithfarm** [comment]
@asettle Please change "WARN" to "warning" here:

```
2. Edit /etc/salt/master and uncomment the following line:

#log_level_logfile: WARN
```

and, a little further down, also change "WARN" to "warning" *and* "INFO" to "info" in this bit:

```
6. Edit /etc/salt/minion and uncomment the following line:

#log_level_logfile: WARN

Change the WARN log level to INFO. 
```

That, I believe, will fix the bug. Consider also adding the information tip I suggested, since it's easy to get "log_level" confused with "log_level_logfile".
