### ISSUE TITLE
Missing Dashboard howto on iSCSI management

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#792]
**Link To Section**
https://documentation.suse.com/ses/6/html/ses-all/cha-ceph-iscsi.html#

**Summary**
It seems we are missing the explanation on how to create a new RBD and export it via the Dashboard.
Or where can this be found?

**Comment by asettle** [comment]
@Martin-Weiss here we go: https://documentation.suse.com/ses/6/single-html/ses-admin/#dashboard-rbds-create

Let me know if you see any improvements to be made here.

**Comment by Martin-Weiss** [comment]
Hm - maybe https://documentation.suse.com/ses/6/html/ses-all/book-storage-admin.html needs to be updated... CTRL-F can not find the iSCSI chapter for RBD export via dashboard.. and https://documentation.suse.com/ses/6/single-html/ses-admin/#dashboard-rbds-create - is is really strange when I access this link - Firefox ends up at a total wrong place and when searching there for iSCSI I can not find the chapter.. not sure what is going on, here

**Comment by asettle** [comment]
Hmm @Martin-Weiss I'm not sure what improvements to suggest, unless you have something in particular? I easily found the chapter you needed by using CTRL+F.

**Comment by Martin-Weiss** [comment]
When I use firefox or chrome and open https://documentation.suse.com/ses/6/single-html/ses-admin/#book-storage-admin and then do CTRL-F "iscsi" I do NOT find a chapter on iSCSI management via the dashboard ..

I just find iSCSI here:
![grafik](https://user-images.githubusercontent.com/13362573/99954020-68ab7e80-2d82-11eb-80d9-fda7da9eb34a.png)

and in figures:
![grafik](https://user-images.githubusercontent.com/13362573/99954082-7bbe4e80-2d82-11eb-9bac-5b1eb3069e42.png)

--> do you find the iSCSI management chapter via dashboard in the TOC?

**Comment by asettle** [comment]
In fairness, we're searching differently :) I went: Dashboard -> RADOS Block Device and was easily able to find the section you requested. 

As you note, if you search for "iscsi" you're not going to find iscsi management in the table of contents, but you will find the section by looking through the full document. 

The table of contents only displays up to 2 levels. So it will not show the third sub-section - this is a style standard, so we're not going to change this. 

I don't think it's unfair to suggest individuals looking for Dashboard applications would search for "Dashboard" first. This is a matter of opinion on how you perform the search.

**Comment by Martin-Weiss** [comment]
So do we recommend to always download the full document before searching?

IMO we should have this also in the TOC.. end user was searching for iSCSI in the TOC to find out how to create a new iSCSI LUN.. so at the moment IMO the TOC needs to get some more content or we should always force the end user do download the full guide.

**Comment by Martin-Weiss** [comment]
Any idea why we do not have a complete TOC and why we limit this to 2 levels, only?

**Comment by asettle** [comment]
We have no recommendations for how a user is to search and manage their consumption of material. That's entirely up to the individual. For example, I tend to stick to using the single-html page so I am able to search. This option is available on all our sites (doc.suse.com and susedoc.github.io), including the option to download a PDF, epub, or use a HTML page. 

The TOC should not be the single source of information when searching, there is no possible way to condense everything into a table of contents. The section is named appropriately. 

Regarding why do we not have a "complete" TOC vs. limiting the options, this is just to keep the table of contents under control. It is already extensive in size, by adding all of the levels nested below two headings, we'd have pages and pages simply dedicated to the TOC. Working a page search on TOC pages would be nice, but it's not something we have.

**Comment by Martin-Weiss** [comment]
Thanks for the explanations - basically I see room for improvement in usability as the customer I am in contact with just did not find what he was looking for and I can understand how he thinks and was going through the TOC.. it is a bit strange that we find iSCSI in the TOC for some operations and not for some other operations.. On the other hand I also understand the limit in resources and the workload - so maybe just maybe keep this wish (list and allow browser based search all chapters in TOC) in mind for the next major changes in documentation ;-).

**Comment by asettle** [comment]
Absolutely, will do! Thanks for the report, it helps us for the next time. Hopefully the changes we made in SES 7 improved the search as well :)
