### ISSUE TITLE
[doc] 19.1  Balancer

### ISSUE THREAD

**Issue by soothill** [SUSE/doc-ses#798]
### Type of report
   - [ X ] bug
   - [ ] feature request

### Source Document
19.1  Balancer:

https://documentation.suse.com/ses/7/single-html/ses-admin/#mgr-modules-balancer

### Summary
There is a section in the documentation here that mentions about upmap not being supported.

Jan Fajerski thinks this is an overhang from SES 6 and probably just needs updating.

**Comment by asettle** [comment]
@jan--f I think we can simply remove this section, no?

**Comment by jan--f** [comment]
Yes I believe we fully support the upmap balancer in SES7. @l-mb any objections?

**Comment by asettle** [comment]
Cool. I can simply remove the note :+1:
