### ISSUE TITLE
[doc] 3  Troubleshooting cephadm

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/doc-ses#809]
### Type of report
   - [ ] bug
   - [X] feature request

### Source Document
3  Troubleshooting cephadm:

https://documentation.suse.com/ses/7/html/ses-all/bp-troubleshooting-cephadm.html#

### Summary

> From: https://bugzilla.suse.com/show_bug.cgi?id=1179187

In case adding hosts in cephadm fail, like so:

```
$ ceph orch host add <hostname>
Failed to connect to <hostname> (<fqdn>).
  Please make sure that the host is reachable and accepts connections using the cephadm SSH key
```
Try:

1. follow the debug steps as printed in the error message

2. Add the host manually

* In case `hostname` prints a fqdn, try adding the host using the fqdn: `ceph orch host add <fqdn>`
* In case `hostname` prints a bare hostname, try adding the host using the fqdn: `ceph orch host add <hostname> <fqdn>`

If this succeeds, there might be a problem with ceph-salt.

3.  Add the host by IP:

* `ceph orch host add <hostname> <IP>`

If this succeeds, the cluster does not have proper name resolution. See: https://documentation.suse.com/ses/7/html/ses-all/deploy-cephadm.html#deploy-os

**Comment by tbazant** [comment]
@sebastian-philipp we do not mention `ceph orch host add` in our docs as we recommended YAML based deployments. Do we plan to include cmdline approach as well as is suggested in this issue? If yes, i should document that first and then add the troubleshooting tip. Agree?

**Comment by sebastian-philipp** [comment]
some more context:

When [adding a new node](https://susedoc.github.io/doc-ses/master/single-html/ses-admin/#adding-node)

A user might get an error from cephadm that it can't add a host. In such a case, users should try addnig the host manually with `ceph orch host add <hostname>` to see if this fails. Then, follow the steps above.
