### ISSUE TITLE
SES7 deployment fails with "Timeout value reached. in find an admin host"

### ISSUE THREAD

**Issue by nistiwar** [SUSE/doc-ses#814]
**Link To Section**
5.3.3 Update Nodes and Bootstrap Minimal Cluster, Deployment guide 

**Summary**
Following the documentation from the start, when trying to bootstrap minimal cluster, it times out waiting for admin node.

**Steps To Reproduce**
Install sles15sp2 on various nodes and follow the deployment guide

**Expected Results**
Minimal cluster is installed and bootstrapped.

**Actual Results**
Minimal cluster bootstrapping failed with a timeout at finding admin node for all nodes in the cluster
**Notes**
Could not find the function **set_admin_host** being called by salt under-the-hood in ceph_orch module. Details:
Ceph-Admin-2:~ # salt \* sys.list_functions ceph_orch
*:
    - ceph_orch.ceph_configured
    - ceph_orch.configured
    - ceph_orch.fsid
    - ceph_orch.host_ls
	
Ceph-Admin-2:~ # salt \* sys.list_functions ceph_salt
*:
    - ceph_salt.begin_stage
    - ceph_salt.begin_step
    - ceph_salt.end_stage
    - ceph_salt.end_step
    - ceph_salt.get_remote_grain
    - ceph_salt.hostname
    - ceph_salt.is_safety_disengaged
    - ceph_salt.probe_dns
    - ceph_salt.probe_fqdn
    - ceph_salt.probe_ntp
    - ceph_salt.probe_time_sync
    - ceph_salt.ssh
    - ceph_salt.sudo_rsync

Ceph-Admin-2:/usr/share/salt-formulas/states/ceph-salt/apply # cat -n  cephconfigure.sls |more
     1  {% import 'macros.yml' as macros %}
     2
     3  {% if 'cephadm' in grains['ceph-salt']['roles'] or 'admin' in grains['ceph-salt']['roles'] %}
     4
     5  find an admin host:
     **6    ceph_orch.set_admin_host:**
     7      - failhard: True
     8
     9  {% endif %}
    10

Ceph-Admin-2:/var/log # zypper search -i ceph-salt
Loading repository data...
Reading installed packages...

S  | Name              | Summary                          | Type
---+-------------------+----------------------------------+--------
i+ | ceph-salt         | CLI tool to deploy Ceph clusters | package
i  | ceph-salt-formula | Ceph Salt Formula                | package
Ceph-Admin-2:/var/log # rpm -qa | grep -i ceph-salt
ceph-salt-formula-15.2.14+1603183994.g323e812-1.2.noarch
ceph-salt-15.2.14+1603183994.g323e812-1.2.noarch

**Comment by tbazant** [comment]
@sebastian-philipp is it a software bug or can we help by aligning the documentation?

**Comment by smithfarm** [comment]
Firewall was interfering with the deployment. Not a doc issue.
