### ISSUE TITLE
[doc] 7.2  Upgrade the Salt Master

### ISSUE THREAD

**Issue by dasrohr** [SUSE/doc-ses#815]
### Type of report
   - [ x ] bug
   - [ ] feature request

### Source Document
7.2  Upgrade the Salt Master:

https://documentation.suse.com/ses/7/html/ses-all/cha-ceph-upgrade.html#upgrade-salt-master

### Summary
wrong config example in documentations
`salt HOST_NAME state.apply ceph.upgrade.ses7.adopt` failes with `Unable to manage file: Jinja variable 'dict object' has no attribute 'location'`

### Steps To Reproduce
follow the steps as described in the docs
salt bails at 7.3.3

### Expected Results
salt runs without error, node gets updated

### Actual Results
`Unable to manage file: Jinja variable 'dict object' has no attribute 'location'`

### Notes
the example config given in the documentation declares `ses7_container_registries` as a list in 7.2.3, which is fine. but every entry has to represent a repository with the key-values of location and insecure for Jinja to resolve the template `/srv/salt/ceph/upgrade/ses7/files/registries.conf.j2` successfully.

**Comment by asettle** [comment]
@ricardoasmarques could you please take a look at this?

**Comment by asettle** [comment]
@tserong could you also please take a look? Thank you

**Comment by dasrohr** [comment]
just a note:
using
```
   registries:
   - location: host:port/registry.suse.com
     insecure: true
```

instead of
```
   registries:
   - location: host:port/registry.suse.com
   - insecure: true
```
fixes the issue. so config that is shown in the docs are wrong

**Comment by asettle** [comment]
> just a note:
> using
> 
> ```
>    registries:
>    - location: host:port/registry.suse.com
>      insecure: true
> ```
> 
> instead of
> 
> ```
>    registries:
>    - location: host:port/registry.suse.com
>    - insecure: true
> ```
> 
> fixes the issue. so config that is shown in the docs are wrong

This is likely the issue. Thanks @dasrohr :)

**Comment by asettle** [comment]
@dasrohr the docs are correctly displayed at present: 
![Screenshot from 2020-12-08 09-38-48](https://user-images.githubusercontent.com/1987994/101466575-36308280-3939-11eb-93c8-4f6469a60a14.png)

Are you potentially referring to a different section? This is the only instance of that code snippet, and it's correctly aligned

```
ses7_container_image: 192.168.121.1:5000/my/ceph/image
ses7_container_registries:
  - location: 192.168.121.1:5000
  - insecure: true```

**Comment by dasrohr** [comment]
the alignment is not the issue.
the issue is that `insecure` is defined as a separate list, althought it should be part of a dict together with `location`, so that the template at `/srv/salt/ceph/upgrade/ses7/files/registries.conf.j2` can resolve properly

**Comment by tserong** [comment]
@dasrohr is correct. It might look weird, but there should *not* a '-' before insecure. The example should be changed to:
```
ses7_container_image: 192.168.121.1:5000/my/ceph/image
ses7_container_registries:
  - location: 192.168.121.1:5000
    insecure: true```
```

**Comment by asettle** [comment]
Apologies, means I misunderstood. Thanks for reporting @dasrohr - it has been fixed here: https://github.com/SUSE/doc-ses/commit/ff9c1c6f4892fb5c3cb3576f4a0f6473863086dc
