### ISSUE TITLE
[doc] 7.4  Install <code class="systemitem">ceph-salt</code> and Apply the Cluster Configuration

### ISSUE THREAD

**Issue by dasrohr** [SUSE/doc-ses#816]
### Type of report
   - [ x] bug
   - [ ] feature request

### Source Document
7.4  Install <code class="systemitem">ceph-salt</code> and Apply the Cluster Configuration:

https://documentation.suse.com/ses/7/html/ses-all/cha-ceph-upgrade.html#upgrade-cephsalt

### Summary
unable to install `zypper install ceph-salt`
conflicts with deepsea-cli

### Steps To Reproduce
```
zypper remove deepsea
zypper install ceph-salt
```

### Expected Results
ceph-salt is getting installed

### Actual Results
```
Problem: ceph-salt-15.2.14+1603183994.g323e812-1.2.noarch conflicts with deepsea-cli provided by deepsea-cli-0.9.33+git.0.ed16d26e-3.27.1.noarch
 Solution 1: deinstallation of deepsea-cli-0.9.33+git.0.ed16d26e-3.27.1.noarch
 Solution 2: do not install ceph-salt-15.2.14+1603183994.g323e812-1.2.noarch
```

### Notes
need to run `zypper remove deepsea*` to remove deepsea-cli as well to make install of ceph-salt possible without error

**Comment by asettle** [comment]
@dasrohr before going to this step, you should have run through: https://documentation.suse.com/ses/7/html/ses-all/cha-ceph-upgrade.html#upgrade-salt-master here, it outlines how to disable deepsea stages to avoid accidental use.

This may be related to your other issue #815

**Comment by dasrohr** [comment]
> @dasrohr before going to this step, you should have run through: https://documentation.suse.com/ses/7/html/ses-all/cha-ceph-upgrade.html#upgrade-salt-master here, it outlines how to disable deepsea stages to avoid accidental use.
I did those steps before proceeding, just as advised by the docs.

I updated the op as the formatting was bad, so the reported error from zypper is better to read

**Comment by asettle** [comment]
Thanks @dasrohr - I'll check in with @ricardoasmarques and see if we can test this.

@tserong also

**Comment by tserong** [comment]
This is technically a bug in the deepsea-cli packaging, i.e. deepsea-cli should specify "Requires: deepsea", so that it's automatically removed when deepsea itself is removed. I've opened https://github.com/SUSE/DeepSea/pull/1864 to fix that, which will land in a maintenance update eventually. Immediately though, I see no problem changing the docs to say `zypper rm 'deepsea*'` to avoid the conflicts problem - just make sure the 'deepsea*' bit has the single quotes around it.

**Comment by asettle** [comment]
Updated the docs to reflect @tserong 's comment: https://github.com/SUSE/doc-ses/commit/47197125b4dcce2efed3824c7f4c10aa2481e663

Thanks for reporting @dasrohr - your other issue will be tracked in the DeepSea repo as linked by Tim.
