### ISSUE TITLE
different output format of `ceph orch device ls`

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#820]
(originated in https://bugzilla.suse.com/show_bug.cgi?id=1179718)

According to the recent docs https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#deploy-cephadm-day2

it says that:

```

5.4.1.2 Listing Devices, Services, and Daemons REPORT DOCUMENTATION BUG#EDIT SOURCE
File Name: deploy_cephadm.xml
ID: deploy-cephadm-day2-orch-list
To run ceph-volume on all nodes and list all disk devices, run:

ceph orch device ls
HOST        PATH      TYPE   SIZE  DEVICE  AVAIL  REJECT REASONS
ses-master  /dev/vda  hdd   16.0G          False  locked
ses-min1    /dev/vdb  hdd   20.0G          True
ses-min1    /dev/vda  hdd   16.0G          False  locked
ses-min2    /dev/vdb  hdd   20.0G          True
[...]


```

however on the test cluster deployed using Devel 7 artifacts, I can see the following output of `ceph orch device ls`:

```
# ceph orch device ls
Hostname        Path      Type  Serial                Size   Health   Ident  Fault  Available  
target-ses-090  /dev/vdb  hdd   0d8a57dc-1ea0-488b-8  10.7G  Unknown  N/A    N/A    No         
target-ses-090  /dev/vdc  hdd   8304795e-0343-481b-a  10.7G  Unknown  N/A    N/A    No         
target-ses-090  /dev/vdd  hdd   7b81e45c-0cdb-4ec2-a  10.7G  Unknown  N/A    N/A    No         
target-ses-090  /dev/vde  hdd   7cba8cc4-2434-4d22-8  10.7G  Unknown  N/A    N/A    No         
```

The header has different column titles, different register, for example AVAIL vs Available.
On the real cluster there are new columns like Serial, Health, Ident, Fault. And I don't see Reject and Reasons.
Also values in the cells of the Available has different style No instead of False and I gues Yes instead of True.

PS: This is report from a user standpoint, so I don't know how it should be, the issue is in the discrepancy.
PS: I didn't go through all the docs, but probably there similar discrepancy can be found.

**Comment by tbazant** [comment]
@jan--f @sebastian-philipp can you confirm that the new listing is correct or provide the latest version here please?

**Comment by asettle** [comment]
@tbazant according to https://github.com/ceph/ceph/blob/master/src/pybind/mgr/orchestrator/module.py#L401-L402 that's correct.
