### ISSUE TITLE
Docs say 'salt-run upgrade.status' will run after upgrade but this requires minion_id file which may not be present

### ISSUE THREAD

**Issue by TimShaw61** [SUSE/doc-ses#826]
**Link To Section**
https://documentation.suse.com/ses/6/html/ses-all/cha-ceph-upgrade.html#upgrade-adm

**Summary**
Docs say that 'salt-run upgrade.status' will run after upgrade to SES 6 but this command requires the presence of the /etc/salt/minion_id file which may not be present

**Steps To Reproduce**
Upgrade to SES 6 and try running salt-run upgrade.status

**Expected Results**
The newest installed software versions are:
  ceph: ceph version 14.2.13-450-g65ea1b614d (65ea1b614db8b6d10f334a8ff67c4de97f73bcbf) nautilus (stable)
  os: SUSE Linux Enterprise Server 15 SP1
.... [more lines describing the cluster nodes]

**Actual Results**
Exception occurred in runner upgrade.status: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 385, in low
    data['return'] = func(*args, **kwargs)
  File "/srv/modules/runners/upgrade.py", line 220, in status
    master_minion = __salt__['master.minion']()
  File "/srv/modules/modules/master.py", line 33, in minion
    with open(id_file, 'r') as id_fd:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/salt/minion_id'

**Notes**
Creating the /etc/salt/minion_id file with the value of id: found in /etc/salt/minion fixes the problem

**Comment by asettle** [comment]
@tserong will have a look into this for you

**Comment by tserong** [comment]
@TimShaw61 can you please tell me a bit more about your environment? I assume you're upgrading from SES 5 to 6. If you had an existing SES 5 deployment, I'd expect both salt-master and salt-minion packages to be installed, and those services be running on your salt master node. So /etc/salt/minion_id should already be present, and should actually contain the hostname of that node.

**Comment by TimShaw61** [comment]
Tim

Yes - SES5 to 6 upgrade Salt master and minion are installed but I had
no minion_id file.  This does not appear to have affected the operations
in the last 2 years of use until after the upgrade when this script
obviously requires it
Salt minions and salt-master both running on the admin node

Perhaps my situation is not normal and in any case SES5 is out of
support shortly so spending time on this may be pointless

T
 


>>> Tim Serong <notifications@github.com> 10/12/2020 10:56 >>>
@TimShaw61<https://github.com/TimShaw61> can you please tell me a bit
more about your environment? I assume you're upgrading from SES 5 to 6.
If you had an existing SES 5 deployment, I'd expect both salt‑master and
salt‑minion packages to be installed, and those services be running on
your salt master node. So /etc/salt/minion_id should already be present,
and should actually contain the hostname of that node.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on
GitHub<https://github.com/SUSE/doc‑ses/issues/826#issuecomment‑742446570>,
or
unsubscribe<https://github.com/notifications/unsubscribe‑auth/AEHVBG3NHR3YMNGM6MOMAMLSUCSPVANCNFSM4USFLZ3Q>.

**Comment by tserong** [comment]
salt-minion is responsible for creating /etc/salt/minion_id. It gets created automatically when the salt-minion service starts. For example, on my test system:

```
admin:~ # systemctl stop salt-minion
admin:~ # rm /etc/salt/minion_id
admin:~ # cat /etc/salt/minion_id
cat: /etc/salt/minion_id: No such file or directory
admin:~ # systemctl start salt-minion
admin:~ # cat /etc/salt/minion_id
admin.ceph
```

You should never need to create this file manually. If this file is missing, it's either a bug in salt, or something extremely peculiar in your environment :-/ Either way though, I don't think this belongs with SES docs.
