### ISSUE TITLE
[doc] 5.4.1.2  Listing devices, services, and daemons

### ISSUE THREAD

**Issue by phakkarainen** [SUSE/doc-ses#840]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
5.4.1.2  Listing devices, services, and daemons:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#deploy-cephadm-day2-orch-list

### Summary
You run a different command (copy-paste from v6) and the output of the new command is different.

**Comment by asettle** [comment]
@phakkarainen - could you please be more explicit here? I do not know what v6 is, I'm not sure what output you're considering to be incorrect (which, I imagine it is, we're constantly updating the outputs). Please make sure you provide all the information in your reports.

**Comment by phakkarainen** [comment]
Yes, I can, sorry.

The text reads:
`To run **ceph-volume** on all nodes and list all disk devices, run:`

The command box reads:
`**ceph orch device ls**`

So the commands are different, and I suspect the first being from SES v6 docs.

The output format of `ceph orch device ls` is also different that is show in the box. (My system is currently down, so I can't give you an example.)

**Comment by phakkarainen** [comment]
```ceph orch device ls
Hostname  Path      Type  Serial   Size   Health   Ident  Fault  Available  
data1     /dev/vdb  hdd   Unknown  21.4G  Unknown  N/A    N/A    No         
data1     /dev/vdc  hdd   Unknown  21.4G  Unknown  N/A    N/A    No         
data1     /dev/vdd  hdd   Unknown  21.4G  Unknown  N/A    N/A    No         
data2     /dev/vdb  hdd   Unknown  21.4G  Unknown  N/A    N/A    No         
data2     /dev/vdc  hdd   Unknown  21.4G  Unknown  N/A    N/A    No         
data2     /dev/vdd  hdd   Unknown  21.4G  Unknown  N/A    N/A    No         
data3     /dev/vdb  hdd   Unknown  21.4G  Unknown  N/A    N/A    No         
data3     /dev/vdc  hdd   Unknown  21.4G  Unknown  N/A    N/A    No         
data3     /dev/vdd  hdd   Unknown  21.4G  Unknown  N/A    N/A    No ```
