### ISSUE TITLE
[doc] 1.3  Getting started with Rook - helm chart operations not detailed/working

### ISSUE THREAD

**Issue by bloriot** [SUSE/doc-ses#855]
### Type of report
   - [x] bug
   - [x] improvement

### Source Document
1.3  Getting started with Rook:

https://documentation.suse.com/ses/7/single-html/ses-rook/#getting-started-rook

### Summary

Missing arguments documentation or detailed explanation on how to use the following commands:

```
helm3 chart pull REGISTRY_URL
helm3 chart export REGISTRY_URL
```

Does not work when using as stated above.

**Comment by ml8mr** [comment]
The missing bit is the REGISTRY_URL itself. The command should look like:

`helm3 chart pull registry.suse.com/ses/7/charts/rook-ceph:latest
helm3 chart export registry.suse.com/ses/7/charts/rook-ceph:latest`

There are a number of things that need to be improved and clarified in the docs regarding these charts. I hope to get to them before too long.
