### ISSUE TITLE
[doc] 1.3  Getting started with Rook - default rook-ceph image version is incorrect

### ISSUE THREAD

**Issue by bloriot** [SUSE/doc-ses#856]
### Type of report
   - [x] bug

### Source Document
1.3  Getting started with Rook:

https://documentation.suse.com/ses/7/single-html/ses-rook/#getting-started-rook

### Summary
Rook-ceph Image tag provided in helm chart is not correct.

### Steps To Reproduce

```
ses7-master-0:~ # helm3 repo add suse https://kubernetes-charts.suse.com
"suse" has been added to your repositories

ses7-master-0:~ # helm3 search repo |grep rook
suse/rook-ceph              	0.0.1             	v1.4.3     	File, Block, and Object Storage Services for yo...

ses7-master-0:~ # helm3 inspect values suse/rook-ceph |grep -B3 tag
image:
  prefix: rook
  repository: registry.suse.com/ses/7/rook/ceph
  tag: 1.4.3

ses7-master-0:~ # docker pull registry.suse.com/ses/7/rook/ceph:1.4.3
Error response from daemon: manifest for registry.suse.com/ses/7/rook/ceph:1.4.3 not found: manifest unknown: manifest unknown
```

### Expected Results
```
ses7-master-0:~ # docker pull registry.suse.com/ses/7/rook/ceph:1.4.7
1.4.7: Pulling from ses/7/rook/ceph
b4e8b82d181b: Pull complete 
58f0dd6ff66d: Pull complete 
ca03f63f002f: Pull complete 
Digest: sha256:2909e8d841f858c9dcd4645f37d9543ded743ccc7cc3ea818b7bddcb9ac37f94
Status: Downloaded newer image for registry.suse.com/ses/7/rook/ceph:1.4.7
registry.suse.com/ses/7/rook/ceph:1.4.7
```

### Notes

**rook/ceph:1.4.3** is not available in registry.suse.com.
Default value in helm chart should be version **1.4.7** (latest version as of today).

**Comment by tbazant** [comment]
@bloriot is there a better and more generic way than to specify a version number? some `latest` tag?

**Comment by tbazant** [comment]
BTW i cant find these snippets anywhere in rook docs, will close as WONTFIX

**Comment by ml8mr** [comment]
The issue that Benoit is reporting is really that the helm2 chart in kubernetes-charts.suse.com is stale, and based on rook 1.4.3. Our docs only show the helm3 process, so this older repository is not really support. However, I will try to update the helm2 chart in the near future. (This isn't a documentation problem, so it is correct to close this.)
