### ISSUE TITLE
Samba upgrade docs require cross-ref

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-ses#862]
**Link To Section**
https://documentation.suse.com/ses/7/single-html/ses-deployment/#upgrade-gateways

**Summary**
The upgrade procedure for the Samba Gateway is the same as the SES 6; It's basically just an OS upgrade.

**Comment by tserong** [comment]
So I guess this belongs in the new (brief) section I'm proposing in #896 ?

**Comment by tbazant** [comment]
Is it then enough to inlcude SAMBA GW in https://susedoc.github.io/doc-ses/main/html/ses-deployment/cha-ceph-upgrade.html#upgrade-gateway-nodes ? That's it?

**Comment by tserong** [comment]
That's my understanding, yes.
