### ISSUE TITLE
[SES6] SES5 -> 6 upgrade chapter: not clear which release notes are intended to be read

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#863]
There is a fundamental problem with "Read the Release Notes" subsection of the SES5 -> 6 upgrade chapter:

```
6.2 Steps to Take before Upgrading the First Node

6.2.1 Read the Release Notes

In the release notes, you can find additional information on changes since the previous release of 
SUSE Enterprise Storage. Check the release notes to see whether:

* Your hardware needs special considerations
* Any used software packages have changed significantly
* Special precautions are necessary for your installation.

The release notes also provide information that could not make it into the manual on time. They 
also contain notes about known issues. After having installed the package release-notes-ses, find 
the release notes locally in the directory /usr/share/doc/release-notes or online at 
https://www.suse.com/releasenotes/.
```

The problem, as I see it, is as follows: this subsection tells the reader to "Read the Release Notes", but it's not clear what is meant by "the release notes"! This is a section of the SES6 documentation so it would be reasonable for the reader to assume the SES6 release notes are meant.

However, this subsection is - damningly - part of a larger section entitled "Steps to Take before Upgrading the First Node". That means: when the reader is taking this step, all cluster nodes are still on SES5. The text does not make it clear, but the implication is that the reader is to read the SES6 release notes **before** upgrading the first node. Yet, if the reader follows what is written ("after having installed the package release-notes-ses...") the SES5 release notes are installed. This is clearly wrong, since the SES5 release notes say nothing about SES6 or the implications of upgrading the cluster to it.

Therefore, I propose the following changes to this section:

1. change each instance of "the release notes" to "the SES6 release notes" (for clarity)
2. delete the passage instructing the reader to install the release-notes-ses package and consult the directory /usr/share/doc/release-notes
3. inform the reader that she should read the SES6 release notes online (since this reading of the SES6 release notes is supposed to take place **before** the upgrade, it doesn't make sense to give instructions for local reading that only work **after** the upgrade of at least one node has been completed)

**Comment by tbazant** [comment]
fixed in https://github.com/SUSE/doc-ses/pull/880/files
