### ISSUE TITLE
"ceph orch restart rgw" in the upgrade procedure does not work.

### ISSUE THREAD

**Issue by knkonishi** [SUSE/doc-ses#864]
**Link to Section**
SUSE Enterprise Storage 7 Deployment Guide
7.6.1 Upgrading the Object Gateway
https://documentation.suse.com/ses/7/html/ses-all/cha-ceph-upgrade.html#upgrade-ogw

**Summary**
I'm trying to upgrade SES6 to SES7 following the document.
It says `ceph orch restart rgw` should be executed to have the Object Gateway service containerized.
But this command does not containerize or start the Gateway service.
In the first place, the Object Gateway service stops when running "zypper dup" to upgrade the OS from SLES15SP1 to SLES15SP2..
So I don't think "restart" is suitable to be used in this situation.
Actually, running `ceph orch apply rgw ${realm} ${zone}` instead of `ceph orch restart rgw` successfully containerizes and starts the Gateway service.
If this is the correct command to run, I would like to see the document corrected.
Please tell me your opinion on this issue.

**Steps To Reproduce**
Follow the upgrade procedure described in the document up to Section 7.6.1.

**Expected Results**
The Object Gateway service starts successfully.

**Actual Results**
The Object Gateway service does not start.

**Notes**
The installed software version is:
ceph-base-15.2.5.667+g1a579d5bf2-3.5.1.x86_64

**Comment by theanalyst** [comment]
Yes this seems about right as the restart wouldn't actually already have the service defintions, so `ceph orch apply` is needed as a step before restart. @sebastian-philipp am I correct?

**Comment by sebastian-philipp** [comment]
> Yes this seems about right as the restart wouldn't actually already have the service defintions, so `ceph orch apply` is needed as a step before restart. @sebastian-philipp am I correct?

correct. But I'd use yaml:


```yaml
service_type: rgw
service_id: realm.zone
placement: ...
spec: ...
```
```
ceph orch apply -i rgw.yaml
```

**Comment by knkonishi** [comment]
@tbazant Thank you for the update.
When will this update be reflected to https://documentation.suse.com/ses/7/html/ses-all/book-storage-deployment.html ?
I've been waiting for an update of the documentation.
