### ISSUE TITLE
[doc] 7.2  Upgrading the Salt Master - add "salt '*' saltutil.sync_all" before "salt-run upgrade.status"

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#865]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
7.2  Upgrading the Salt Master:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#upgrade-salt-master

### Summary

See bug https://bugzilla.suse.com/show_bug.cgi?id=1181092

### Steps To Reproduce
apply patches on ses-admin then zypper dup/migrate ses-admin and then execute the salt-run upgrade.status

### Expected Results
correct result

### Actual Results
'osd.require_osd_release' is not available.'

**Comment by asettle** [comment]
Going to close this as a duplicate - let's keep one location. I've added @tbazant to the BZ.
