### ISSUE TITLE
[doc] 7.3  Upgrading the MON, MGR, and OSD nodes - replace hostname with minion-id

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#866]
### Type of report
   - [x ] bug
   - [ ] feature request

### Source Document
7.3  Upgrading the MON, MGR, and OSD nodes:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#upgrade-mon-mgr-nodes

### Summary
We must not use the "hostname" - we have to use "minionid"

salt HOST_NAME state.apply ceph.upgrade.ses7.adopt -> HOST_NAME must be "minion_id" or similar

**Comment by tbazant** [comment]
@tserong what exactly is the MINION_ID? can i obtain it as an output of some command?

**Comment by tserong** [comment]
The minion ID is what salt thinks the minion is called, as reported when running `salt-key -L` on the salt master (on each minion, you can also check the contents of /etc/salt/minion_id to see what an individual minion ID is). Usually the minion ID should be the same as the system FQDN, but occasionally it's not.
