### ISSUE TITLE
[doc] 7.2  Upgrading the Salt Master - add information on how to specify registry credentials

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#868]
### Type of report
   - [x ] bug
   - [ ] feature request

### Source Document
7.2  Upgrading the Salt Master:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#upgrade-salt-master

### Summary
We just have documented how to specify the on-premise registry:

ses7_container_image: 192.168.121.1:5000/my/ceph/image
ses7_container_registries:
  - location: 192.168.121.1:5000

BUT - how can we configure the credentials that are required to pull from the on-premise registry?

**Comment by sebastian-philipp** [comment]
ceph-salt uses the pillar data from

* ceph-salt/container/auth/registry
* ceph-salt/container/auth/username
* ceph-salt/container/auth/password

But I don't think this is added to the ceph-salt config UI

**Comment by Martin-Weiss** [comment]
I believe at this stage - we talk about pillar data that is used by deepsea before / as part of the upgrade to SES 7.. so not sure how deepsea is able to use the registry credentials and how...

**Comment by tbazant** [comment]
> ceph-salt uses the pillar data from
> 
>     * ceph-salt/container/auth/registry
> 
>     * ceph-salt/container/auth/username
> 
>     * ceph-salt/container/auth/password
> 
> 
> But I don't think this is added to the ceph-salt config UI

@sebastian-philipp how can i integrate modifying these credentials in the upgrade process?

**Comment by sebastian-philipp** [comment]
as Martin said, this is independent of deepsea. We need to add those credentials to the ceph-salt pillar data **after** there is ceph-salt pillar data to work with and **before** we're setting the container_image.

**Comment by tbazant** [comment]
@sebastian-philipp How do i set/read these values? By `ceph-salt /ceph-salt/container/auth/registry <registry_url>`?

**Comment by sebastian-philipp** [comment]
I  think  you'll have to directly modify the salt pillar data @smithfarm ?

**Comment by tbazant** [comment]
@smithfarm  @sebastian-philipp we do not have this covered in the deployment process neither, i'll extend a section there and then link to it from the upgrade chapter, ok?
