### ISSUE TITLE
[doc] 7.5  Upgrading and adopting the monitoring stack - grafana image name wrong

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#869]
### Type of report
   - [x ] bug
   - [ ] feature request

### Source Document
7.5  Upgrading and adopting the monitoring stack:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#upgrade-cephsalt-monitoring

### Summary
This example is wrong:

192.168.121.1:5000/ses/7/ceph/grafana:7.0.3 \

AFAIK this should be

192.168.121.1:5000/caasp/4.5/grafana:7.0.3 \

**Comment by p-se** [comment]
I admit, that it is confusing to obtain three images from `caasp` and only one from `ses`. However, this is correct. We do not require any changes in the images from CaaSP, that's why we can safely use them without having to build and provide our own. This is different for Grafana, as the Grafana dashboards we provide have to be included in the container image, for instance.

**Comment by Martin-Weiss** [comment]
From a usability point of view this is a nightmare for customers as it is neither logical nor easy to understand...

Why can´t we have all required SES images from SES namespace on the registry?

**Comment by tbazant** [comment]
> I admit, that it is confusing to obtain three images from `caasp` and only one from `ses`. However, this is correct. We do not require any changes in the images from CaaSP, that's why we can safely use them without having to build and provide our own. This is different for Grafana, as the Grafana dashboards we provide have to be included in the container image, for instance.

@p-se do i need to change anything in the docs in regards to thus issue?

**Comment by p-se** [comment]
> @p-se do i need to change anything in the docs in regards to thus issue?

No, current documentation might be a little bit confusing but is correct and works.

**Comment by tbazant** [comment]
WONTFIX
