### ISSUE TITLE
[doc] 5.3.2.11  Configuring the container registry

### ISSUE THREAD

**Issue by bwgartner** [SUSE/doc-ses#870]
### Type of report
   - [X] bug
   - [ ] feature request

### Source Document
5.3.2.11  Configuring the container registry:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#deploy-cephadm-configure-registry

### Summary

Creating a local registry as documented, by default seems to make HTTP as the protocol for getting the images, but cephadm, by default, wants to use HTTPS

### Steps To Reproduce

Follow the document as is, yields failure (see Actual Results)

### Expected Results

Current documented process should yield a successful, complete ceph-salt apply with a local registry for base, required container images

### Actual Results

Follow the document as is, yields failure (and hint from ceph-salt.log):
```
"stderr": "Pulling container image registry.suse.com/ses/7/ceph/ceph...
Non-zero exit code 125 from /usr/bin/podman pull registry.suse.com/ses/7/ceph/ceph
/usr/bin/podman:stderr Trying to pull registry.suse.com/ses/7/ceph/ceph...
/usr/bin/podman:stderr   Get https://192.168.8.66:5000/v2/: http: server gave HTTP response to HTTPS client
/usr/bin/podman:stderr Error: unable to pull registry.suse.com/ses/7/ceph/ceph: Error initializing source docker://registry.suse.com/ses/7/ceph/ceph:latest: error pinging docker registry 192.168.8.66:5000: Get https://192.168.8.66:5000/v2/: http: server gave HTTP response to HTTPS client
Traceback (most recent call last):
  File \"/usr/sbin/cephadm\", line 6114, in <module>
    r = args.func()
  File \"/usr/sbin/cephadm\", line 1381, in _infer_image
    return func()
  File \"/usr/sbin/cephadm\", line 2677, in command_pull
    _pull_image(args.image)
  File \"/usr/sbin/cephadm\", line 2700, in _pull_image
    raise RuntimeError('Failed command: %s' % cmd_str)
RuntimeError: Failed command: /usr/bin/podman pull registry.suse.com/ses/7/ceph/ceph"

```
### Notes

Follow the document as is, but had to modify 5.3.2.11 step 5 to get ceph-salt apply complete successfully (based upon guess from https://www.projectatomic.io/blog/2018/05/podman-tls/, aka [registries.insecure]
ceph-salt config /containers/registries_conf/registries add prefix=registry.suse.com insecure=true location=<LOCAL_REGISTRY_HOST_IP>:5000/registry.suse.com

**Comment by sebastian-philipp** [comment]
just to confirm, https://documentation.suse.com/sbp/all/single-html/SBP-Private-Registry/ defaults to create a HTTP registry?

**Comment by tbazant** [comment]
@bwgartner i'm looking at section 5.3.2.11, but there is no step 5. can you please suggest the needed changes more precisely?

**Comment by tbazant** [comment]
@bwgartner , @ml8mr Does https://github.com/SUSE/doc-ses/pull/941 resolve this issue?

**Comment by tbazant** [comment]
solved by https://github.com/SUSE/doc-ses/commit/f48d47a65572b4abb662427c0dd96273b20b66cc
