### ISSUE TITLE
[doc] 7.7  Post-upgrade Clean-up - ceph osd set require-min-compat-client luminous -> invalid command

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#873]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
7.7  Post-upgrade Clean-up:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#upgrade-post-cleanup

### Summary

ses-5-admin:~ # ceph osd set require-min-compat-client luminous
Invalid command: require-min-compat-client not in full|pause|noup|nodown|noout|noin|nobackfill|norebalance|norecover|noscrub|nodeep-scrub|notieragent|nosnaptrim|pglog_hardlimit
osd set full|pause|noup|nodown|noout|noin|nobackfill|norebalance|norecover|noscrub|nodeep-scrub|notieragent|nosnaptrim|pglog_hardlimit [--yes-i-really-mean-it] :  set <key>
Error EINVAL: invalid command

--> seems the documentation has a command that is not available or has a typo
    

Assumption is that the required command is:

ceph osd set-require-min-compat-client luminous

**Comment by tserong** [comment]
> ceph osd set-require-min-compat-client luminous

Yup, that's correct (missing hyphen).
