### ISSUE TITLE
[doc] 7.7  Post-upgrade Clean-up - mention a bit more about pg_autoscaler

### ISSUE THREAD

**Issue by tserong** [SUSE/doc-ses#893]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
7.7  Post-upgrade Clean-up:

https://susedoc.github.io/doc-ses/main/single-html/ses-deployment/#upgrade-post-cleanup

### Summary
We need to add a bit more information to the post-upgrade cleanup section:

"Step 3. Enable the autoscaler module" says to enable the autoscaler module, which is fine, but we should add a note to say that the default in SES6 was for pools to be set to pg_autoscale_mode warn (so autoscaling doesn't actually happen, there's just a warning message if there's a suboptimal number of PGs), whereas the default in SES7 is pg_autoscale_mode on, for new pools, so PGs will actually autoscale. The upgrade process will _not_ automatically change the pg_autoscale_mode of existing pools. If you want to change it to "on", to get the full benefit of the autoscaler, do so following the instructions in section 17.4.12 Enabling the PG auto-scaler of the admin guide.

**Comment by tbazant** [comment]
update included by https://github.com/SUSE/doc-ses/commit/a78cd71ca2adb15f577663b25e48b540e127bf89
