### ISSUE TITLE
[doc] 7.4  Installing ceph-salt and applying the cluster configuration needs a couple more steps

### ISSUE THREAD

**Issue by tserong** [SUSE/doc-ses#894]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
7.4  Installing <code class="systemitem">ceph-salt</code> and applying the cluster configuration:

https://susedoc.github.io/doc-ses/main/single-html/ses-deployment/#upgrade-cephsalt

### Summary
We need a couple more steps here. It doesn't really matter what order these go in, but I think it probably makes sense to get rid of the cron jobs _first_, and to stop and disable the ceph-crash daemons _last_, which all the other steps remaining as is in between.

* Remove the DeepSea-created rbd_exporter and rgw_exporter cron jobs.
On the salt-master, as root, run `crontab -e` to edit the crontab. Delete the following items if present:

```
# SALT_CRON_IDENTIFIER:deepsea rbd_exporter cron job
*/5 * * * * /var/lib/prometheus/node-exporter/rbd.sh > /var/lib/prometheus/node-exporter/rbd.prom 2> /dev/null
# SALT_CRON_IDENTIFIER:Prometheus rgw_exporter cron job
*/5 * * * * /var/lib/prometheus/node-exporter/ceph_rgw.py > /var/lib/prometheus/node-exporter/ceph_rgw.prom 2> /dev/null
```

* Stop and disable the SES6 ceph-crash daemons (new containerized forms of these will be started later automatically)

```
# salt '*' service.stop ceph-crash
# salt '*' service.disable ceph-crash
```

**Comment by tbazant** [comment]
update included in https://github.com/SUSE/doc-ses/commit/927bb323f2545739d61ef968c32a56de07ecc1ac
