### ISSUE TITLE
[doc] 7.1.1  Points to consider - add more points

### ISSUE THREAD

**Issue by tserong** [SUSE/doc-ses#895]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
7.1.1  Points to consider:

https://susedoc.github.io/doc-ses/main/single-html/ses-deployment/#upgrade-consider-points

### Summary

Please the following additional points:

* Read section 5 "Deploy with cephadm" to familiarise yourself with ceph-salt and the Ceph orchestrator, and in particular the information on service specifications.

(The above should go after the "Read the release notes" point, I think.)

* Upgrade of core services (MON, MGR, OSD) will happen in-place, in a rolling fashion, so these services will always be available during the upgrade. Gateway services (Metadata Servers, Object Gateways, NFS Ganesha, iSCSI Gateway) need to be redeployed once the core services are upgraded, so there will be a certain amount of downtime for each of these:
  * Metadata Servers and Object Gateways will be down from the time their nodes are upgraded from SLE 15 SP1 to SLE 15 SP2, until those services are redeployed at the end of the upgrade procedure. This is particularly important to bear in mind if these services are colocated with MONs, MGRs or OSDs, because in this case they may be down for the entire duration of the cluster upgrade. If this is going to be a problem, consider deploying these services separately on additional nodes _before_ upgrading, so that they are down for the least amount of time possible (i.e. just the duration of the upgrade of the gateway nodes, not the duration of the upgrade of the entire cluster).
  * NFS Ganesha and iSCSI Gateways will be down only while nodes are rebooting during upgrade from SLE 15 SP1 to SLE 15 SP2, and again briefly when each service is redeployed in containerized mode.

(That giant blob should probably go at the end.)

**Comment by tbazant** [comment]
update included in https://github.com/SUSE/doc-ses/commit/09aaaf54c9f91406d98bf7a4bad4713ffc607ea6
