### ISSUE TITLE
[doc] 7.3  Upgrading the MON, MGR, and OSD nodes - insert new "Upgrading Gateway nodes" section

### ISSUE THREAD

**Issue by tserong** [SUSE/doc-ses#896]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
7.3  Upgrading the MON, MGR, and OSD nodes:

https://susedoc.github.io/doc-ses/main/single-html/ses-deployment/#upgrade-mon-mgr-nodes

### Summary

Please add a new section between the existing "7.3 Upgrading the MON, MGR, and OSD nodes" and "7.4 Installing ceph-salt and applying the cluster configuration" sections, entitled "Upgrading Gateway nodes". We may also want to rename the existing "Gateway upgrades" section to something like "Gateway service redeployment".

So the new ordering will be:

7.3 Upgrading the MON, MGR and OSD nodes
7.4 Upgrading Gateway nodes
7.5 Installing ceph-salt and applying the cluster configuration
7.6 Upgrading and adopting the monitoring stack
7.7 Gateway service redeployment [or whatever makes sense]

Here's the proposed text for the new 7.4 Upgrading Gateway nodes section:

If you have separate gateway nodes (Metadata server, Object Gateway, NFS Ganesha, iSCSI Gateway), these must be upgraded next. For each of these nodes, upgrade the underlying OS to SLE 15 SP2:

* If the cluster's nodes are all registered with SCC, run `zypper migration`.
* If the cluster's nodes have software repositories assigned manually, run `zypper dup` followed by `reboot`.

This step also applies for any nodes that are notionally part of the cluster, but don't yet have any roles assigned (if in doubt, check the list of hosts provided by `salt-key -L` and compare it to the output of `salt-run upgrade.status`)

Once the OS is upgraded on all nodes in the cluster, the next step is to install ceph-salt and apply the cluster configuration. The actual gateway services themselves will be redeployed in containerized mode at the end of the upgrade procedure.

_Note: Metadata Server and Object Gateway services will be unavailable from the time of upgrading to SLE 15 SP2, until they are redeployed at the end of the upgrade procedure_

**Comment by tbazant** [comment]
update included in https://github.com/SUSE/doc-ses/commit/32d32edb1fdba548baf10c39b02bebbafa5d8fcb
