### ISSUE TITLE
formatting tool for contributors

### ISSUE THREAD

**Issue by p-se** [SUSE/doc-ses#901]
Do we have a formatting tool that is correctly configured so that it automatically corrects and unifies the formatting (especially indentation)? If so, where can I find it and how to use it? And would it make sense to add this reference then to the README?

**Comment by tbazant** [comment]
@p-se  does `daps-xmlformat` satisfy your needs here? can we close this one?

**Comment by p-se** [comment]
@tbazant Sure it does, though, wouldn't it make sense to have that mentioned in the README?

**Comment by tbazant** [comment]
BTW we're working on auto-xml-format GitHub workflow action that would automatically format each modified XML file after a PR is created. Still in testing phase.

**Comment by tbazant** [comment]
Good new, the auto xmlformat workflow action is installed on SES repo. It is triggered by creating a pull request or making commits inside PR branch. Therefore, no matter how you format the XML file you're editing, it will be re-formatted after being commited.
