### ISSUE TITLE
[doc] 1.4  Deploying Ceph with Rook

### ISSUE THREAD

**Issue by rabueker** [SUSE/doc-ses#933]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
1.4  Deploying Ceph with Rook:

https://documentation.suse.com/ses/7/single-html/ses-rook/#rook-deploy-ceph

### Summary

Point 4: The command to create the cluster is:
kubectl create -f cluster.yaml

### Steps To Reproduce

Using the given description would try to install rook-ceph a second time, which will not work.

### Expected Results

After running the command to deploy the cluster the cluster should be deployed.

### Actual Results

Getting an error that namespace is already in use.

**Comment by ml8mr** [comment]
Are you saying that these steps work fine the first time, but the second time it won't work? (If so, we could add a note about it...)
