### ISSUE TITLE
IDs in DC-ses-man make GitHub Actions fail

### ISSUE THREAD

**Issue by sknorr** [SUSE/doc-ses#944]
GitHub Actions now checks `DC-ses-man` which apparently was not checked before.
It finds a couple of IDs that still use underscores in there:

```
  Fatal error: The following IDs contain unwanted characters:
  man-ganesha-config-export_defaults
  man-ganesha-config-nfs_core_param
  man-ganesha-config-nfs_ip_name
  man-ganesha-config-nfs_krb5
  man-ganesha-config-proxy_v3
  man-ganesha-config-proxy_v4
  man-ganesha-core-config-nfs_core_param
  man-ganesha-core-config-nfs_ip_name
  man-ganesha-core-config-nfs_krb5
  man-ganesha-core-config-rados_kv
  man-ganesha-core-config-rados_urls
  man-ganesha-export-config-export_defaults
```

@tbazant Can you take care?

(The action has a setting to disable the ID check but it would be applied to all documents of the repo which I don't think you'd want.)

**Comment by tbazant** [comment]
fixed by https://github.com/SUSE/doc-ses/commit/ada9a141696f117f6b58924648f6a1a67c794184
