### ISSUE TITLE
lproven no longer with the company, don't assign reviews to him

### ISSUE THREAD

**Issue by sknorr** [SUSE/doc-ses#963]
.github/auto_assign.yml has this review assignment:

https://github.com/SUSE/doc-ses/blob/f5246e545252885483015e69794cf14bb0b77d00/.github/auto_assign.yml#L11-L12

Not sure if you want to replace him in any way. (Also, if you only need a single reviewer, it's probably easier to use a CODEOWNERS file which is supported natively by GitHub rather than a separate bot. [Example](https://github.com/SUSE/doc-slert/blob/main/.github/CODEOWNERS))

**Comment by tbazant** [comment]
fixed by 2101846802
