### ISSUE TITLE
Hardware coniguration of SES documentation is slighly different from upstream.

### ISSUE THREAD

**Issue by shinkichi23** [SUSE/doc-ses#968]
**Link To Section**
Please provide a link to the section or chapter you are reporting this bug for.

https://documentation.suse.com/ses/6/single-html/ses-deployment/#sysreq-mon

**Summary**

Regarding the hardware-recommendations of physical RAM in case the both mon and mgr are working in the node.
Does it require 4GB in total for ceph Service that according to the SES6 documentation stated as below.

[From SES6]
2.5 Monitor Nodes
https://documentation.suse.com/ses/6/single-html/ses-deployment/#sysreq-mon
4 GB of RAM.
Mixing OSD, monitor, or Object Gateway nodes is only supported if sufficient hardware resources are available. That means that the requirements for all services need to be added up.

------------------

BTW, The nautilus documentation states 5-10GB is recommended for large clusters.
[From Nautilus]
MONITORS AND MANAGERS (CEPH-MON AND CEPH-MGR)
https://docs.ceph.com/en/nautilus/start/hardware-recommendations/#ram
Monitor and manager daemon memory usage generally scales with the size of the cluster. For small clusters, 1-2 GB is generally sufficient. For large clusters, you should provide more (5-10 GB). You may also want to consider tuning settings like mon_osd_cache_size or rocksdb_cache_size.

**Steps To Reproduce**
Steps to reproduce the behavior.

**Expected Results**

It would be better to state at least the RAM size depends on the cluster size and workload.

**Actual Results**
Explain what actually happened when the steps were executed, and if applicable, add screenshots to help explain your problem.

**Notes**

**Comment by tbazant** [comment]
fixed by https://github.com/SUSE/doc-ses/commit/7e7623faf810a6646cbdf524e86c4176ca0ff6a8
