### ISSUE TITLE
[doc] 3.5  Listing configured container images

### ISSUE THREAD

**Issue by hansvdh** [SUSE/doc-ses#992]
### Type of report
   - [X ] bug
   - [ ] feature request

### Source Document
3.5  Listing configured container images:

https://documentation.suse.com/ses/7/html/ses-all/bp-troubleshooting-cephadm.html#bp-troubleshooting-cephadm-configured-container-images

### Summary
The Notes section says this:
mgr/cephadm/container_image_base is the default Ceph conatiner image used by all services except the monitoring stack
There is a typo in the word "conatiner"

### Steps To Reproduce
See above

### Expected Results
The word should read "container"

### Actual Results
![image](https://user-images.githubusercontent.com/19544950/157311522-84c2da97-18e1-437a-8ca1-732ed7900b01.png)

### Notes
Thank you !

**Comment by tbazant** [comment]
fixed in https://github.com/SUSE/doc-ses/commit/2c690a7c2a24cd15a9bf64814d2ff661ea89d796
