### ISSUE TITLE
[doc] 10.4  Enabling the Object Gateway management front-end

### ISSUE THREAD

**Issue by trociny** [SUSE/doc-ses#996]
### Type of report
   - [ ] bug
   - [ ] feature request

### Source Document
10.4  Enabling the Object Gateway management front-end:

https://documentation.suse.com/ses/7/single-html/ses-admin/#dashboard-ogw-enabling

### Summary

These commands are outdated:

  ceph dashboard set-rgw-api-access-key ACCESS_KEY
  ceph dashboard set-rgw-api-secret-key SECRET_KEY
  
For security reasons it has been disallowed to provide ACCESS_KEY and SECRET_KEY params via command line arguments. Instead they should be provided via file:

  ceph dashboard set-rgw-api-access-key -i ACCESS_KEY_FILE
  ceph dashboard set-rgw-api-secret-key -i SECRET_KEY_FILE

### Steps To Reproduce

master:~ # ceph dashboard set-rgw-api-access-key "BNN6J1LWPRFLGUO15G5Z"
Invalid command: unused arguments: ['BNN6J1LWPRFLGUO15G5Z']
dashboard set-rgw-api-access-key :  Set the RGW_API_ACCESS_KEY option value read from -i <file>
Error EINVAL: invalid command

master:~ # echo BNN6J1LWPRFLGUO15G5Z > access_key
master:~ # ceph dashboard set-rgw-api-access-key -i access_key 
Option RGW_API_ACCESS_KEY updated

**Comment by tbazant** [comment]
@trociny please review https://github.com/SUSE/doc-ses/pull/1000
